### DISCUSSION TITLE
The OVN DHCP still doesn't work with ovs-dpdk

### DISCUSSION THREAD

**Discussion by carezkh** [kubeovn/kube-ovn#1958] [Q&A] [answered]
I notice there is a patch #1853 fixed this error, but when i tested with Kube-OVN 1.10.6, it seems OVN DHCP is still not working!

The ovs-ovn reported with `2022-10-12T11:18:20.430Z|00006|pinctrl(ovn_pinctrl1)|WARN|Invalid or incomplete DHCP packet received, bad data length`

My subnet manifest

```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: sn-dhcp
spec:
  cidrBlock: "172.18.0.0/16"
  default: false
  namespaces:
    - default
  disableGatewayCheck: true
  disableInterConnection: false
  excludeIps:
    - 172.18.0.1
  gateway: 172.18.0.1
  gatewayType: distributed
  natOutgoing: true
  protocol: IPv4
  provider: ovn
  vpc: ovn-cluster
  enableDHCP: true
  dhcpV4Options: "server_id=172.18.0.100,server_mac=00:00:00:2E:2F:B8,lease_time=3600,router=172.18.0.1,netmask=255.255.0.0"
```

Is there something wrong?
