### DISCUSSION TITLE
docs/v1.11.x/advance/multi-nic/

### DISCUSSION THREAD

**Discussion by giscus** [kubeovn/kube-ovn#2810] [Announcements]
# docs/v1.11.x/advance/multi-nic/

https://kubeovn.github.io/docs/v1.11.x/advance/multi-nic/

**Comment by Git4Mark** [comment]
multus多网卡管理，使用ovn作为附加网卡时，是否能通过某种方式指定路由？
类似这种
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.2.0/24",
        "rangeStart": "192.168.2.200",
        "rangeEnd": "192.168.2.216",
        "routes": [
          { "dst": "0.0.0.0/0" }
        ],
        "gateway": "192.168.2.1"
      }
    }'
```
