### DISCUSSION TITLE
Setting up Kube-Ovn on AWS EKS

### DISCUSSION THREAD

**Discussion by rkesters** [kubeovn/kube-ovn#3452] [Q&A]
Hi, 

I have an EKS cluster that is running Kubvirt to host VM on bare metal servers. I also have container loads running on normal EC2 nodes. I have a deployment (call the Srv1) that is deployed in the ovn-default subnet (10.251.0.0/16) and I have my VM deploy in subnet (192.168.1.0/24) . 

I can connect from Srv1's POD tot ge VM via the virtctl vnc command , but I can not connect to via the virtctl ssh command or port-forward.  I have confirmed that sshd is running on the vm and on port 22. 

I not sure how to troubleshoot the issue, any help would be awesome.

**Comment by zbb88888** [comment]
is subnet（192.168.1.0/24）in the vpc `ovn-cluster` ?

**Reply by rkesters** [reply]
Yes, 

```sh
NAME                                   PROVIDER                                               VPC           PROTOCOL   CIDR             PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS        U2OINTERCONNECTIONIP
join                                   ovn                                                    ovn-cluster   IPv4       100.64.0.0/16    false     false   false     distributed   3        65530         0        0             ["100.64.0.1"]
ovn-default                            ovn                                                    ovn-cluster   IPv4       10.254.0.0/16    false     true    true      distributed   19       65514         0        0             ["10.254.0.1"]
sub-eb814be3ca3b78c0734c560518be2a03   sub-eb814be3ca3b78c0734c560518be2a03.namespace-1.ovn   ovn-cluster   IPv4       192.168.1.0/24   false     false   false     distributed   3        250           0        0             ["192.168.1.1"]
```

（192.168.1.0/24）was created in nd namespace-1

```yaml
apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      friendly_name: Main
    name: sub-eb814be3ca3b78c0734c560518be2a03
    namespace: namespace-1
  spec:
    config: '{ "cniVersion": "0.3.0", "type": "kube-ovn", "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "sub-eb814be3ca3b78c0734c560518be2a03.namespace-1.ovn" }'
```

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  annotations:
    friendly_name: Main
  finalizers:
  - kube-ovn-controller
  generation: 2
  name: sub-eb814be3ca3b78c0734c560518be2a03
  cidrBlock: 192.168.1.0/24
  default: false
  enableDHCP: true
  excludeIps:
  - 192.168.1.1
  gateway: 192.168.1.1
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: sub-eb814be3ca3b78c0734c560518be2a03.namespace-1.ovn
  vpc: ovn-cluster
status:
  activateGateway: ""
  conditions:
  - lastTransitionTime: "2023-11-16T19:57:16Z"
    lastUpdateTime: "2023-11-22T19:31:44Z"
    reason: ResetLogicalSwitchAclSuccess
    status: "True"
    type: Validated
  - lastTransitionTime: "2023-11-16T19:57:16Z"
    lastUpdateTime: "2023-11-16T19:57:16Z"
    reason: ResetLogicalSwitchAclSuccess
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-11-16T19:57:16Z"
    lastUpdateTime: "2023-11-16T19:57:16Z"
    message: Not Observed
    reason: Init
    status: Unknown
    type: Error
  dhcpV4OptionsUUID: 5928ee1b-5149-432d-a034-adc60f01b473
  dhcpV6OptionsUUID: ""
  u2oInterconnectionIP: ""
  u2oInterconnectionVPC: ""
  v4availableIPs: 250
  v4usingIPs: 3
  v6availableIPs: 0
  v6usingIPs: 0

```

is there documentation that explains the meaning/use of each field the kube-ovn CRD. I've read through the docs, but I can't find a single page that lists all the fields and their use.
