### DISCUSSION TITLE
docs/v1.13.x/guide/qos/

### DISCUSSION THREAD

**Discussion by giscus** [kubeovn/kube-ovn#4802] [Announcements]
# docs/v1.13.x/guide/qos/

None

https://kubeovn.github.io/docs/v1.13.x/guide/qos/

**Comment by kldancer** [comment]
请问一下，如果一个pod是多网卡部署的方式。想要使用最大带宽限制的QoS的话。是否注释就应该写成类似这样：
```yaml
      annotations:
        ovn.kubernetes.io/logical_switch: ovn-default
        k8s.v1.cni.cncf.io/networks: kube-system/subnet-73vt64fs
        ovn.kubernetes.io/egress_rate: "10"
        subnet-73vt64fs.kube-system.ovn.kubernetes.io/egress_rate: "10"
```
这样网卡1、网卡2的QoS规则会生效吗？
