### ISSUE TITLE
kube-ovn-cni readiness/liveness probe optimization

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1150]
`kube-ovn-cni` now use exec probe to detect readiness and liveness below and it should be replaced by tcpprobe.

```     
       readinessProbe:
          exec:
            command:
              - nc
              - -z
              - -w3
              - 127.0.0.1
              - "10665"
          periodSeconds: 3
        livenessProbe:
          exec:
            command:
              - nc
              - -z
              - -w3
              - 127.0.0.1
              - "10665"
          initialDelaySeconds: 30
          periodSeconds: 7
          failureThreshold: 5
```
