### ISSUE TITLE
Pod使用 provider !="ovn"的subnet，controller为pod加的annotation和判断pod annotation取的key不一致

### ISSUE THREAD

**Issue by chestack** [kubeovn/kube-ovn#1210]
复现方法：
pod.yml
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    v1.multus-cni.io/default-network: secure-container/kube-ovn
    ovn.kubernetes.io/eip: 172.35.0.19
  name: kata-eip-nginx
  labels:
    app: kata-eip-nginx
spec:
  runtimeClassName: rune
  containers:
  - name: kata-eip-nginx
    image: docker.io/captain/nginx:1.13
```

net-attach-def.yml
```
config: '{
    "name": "kube-ovn",
    "cniVersion": "0.3.1",
    "plugins": [
        {
            "type": "kube-ovn",
            "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
            "provider": "kube-ovn.secure-container.ovn"
        },
        
    ]
}'
```

问题现象：
eip的pod没有执行 lr-route-add 和 lr-nat-add

可能原因：
pod 没有被updatePodQueue.Add(key)，导致没有走到 handleUpdatePod()，导致没有执行 lr-route-add

判断pod 是否 updatePodQueue.Add(key) 取的key是  ovn.kubernetes.io/allocated: "true" [controller/pod.go#L229-L241](https://github.com/kubeovn/kube-ovn/blob/master/pkg/controller/pod.go#L229-L241)

而 pod实际annotation是 kube-ovn.secure-container.ovn.kubernetes.io/allocated: "true",  这个改动来自 https://github.com/kubeovn/kube-ovn/pull/1188
```
    kube-ovn.secure-container.ovn.kubernetes.io/allocated: "true"
    kube-ovn.secure-container.ovn.kubernetes.io/cidr: 10.16.0.0/16
    kube-ovn.secure-container.ovn.kubernetes.io/gateway: 10.16.0.1
    kube-ovn.secure-container.ovn.kubernetes.io/ip_address: 10.16.0.2
```
