### ISSUE TITLE
Accessing nodePort service, the ingress path maybe different from the egress path

### ISSUE THREAD

**Issue by chestack** [kubeovn/kube-ovn#1235]
# Steps to Reproduce the Problem

1.  node-1/2/3 are gateway nodes  of ovn-default
    
    lr-route-list ovn-cluster
```
             10.16.0.0/16                100.64.0.2 src-ip ecmp
             10.16.0.0/16                100.64.0.3 src-ip ecmp
             10.16.0.0/16                100.64.0.4 src-ip ecmp
```

    ipset ovn40subnets-nat on nodes
```
Name: ovn40subnets-nat
Type: hash:net
...
Members:
10.16.0.0/16
```

    RETURN rule of POSTROUTING chain match set ovn40subnets-nat
```
Chain POSTROUTING (policy ACCEPT 37 packets, 2827 bytes)
   67  4620 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ! match-set ovn40subnets src ! match-set ovn40other-node src match-set ovn40subnets-nat dst
```

2. create nodePort svc with ovn-default
```
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  selector:
    app: pod-nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-nginx
  template:
    metadata:
      labels:
        app: pod-nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: test
        ports:
        - containerPort: 80
```

3. accessing nodePort svc with destination node-1:  ```curl ${node-1-ip}:port```

# Actual Behavior
the ingress path:  ```client -> node-1 -> ovn0 --> pod```. The packet **will not SNAT but return** through POSTROUTING, because of the iptables rule mentioned in step1.

the egress path: ```pod -> ovn-cluster -> ecmp route -> node-1/2/3```

```tcpdump -i ovn0``` on all node-1/2/3, found that all nodes ovn0 receive the reply and the curl client won't get the reply until the reply be routed to node-1 ovn0 after pod retry.

<img width="1910" alt="WeChat50fb2d060c0424275489be6f8e15394f" src="https://user-images.githubusercontent.com/6983751/148341622-9a0e89fb-5183-44f7-b4af-76c89a079fbc.png">

# Expected Behavior
curl client gets the reply immediately, egress path is the same with ingress path.

# Additional Info
the RETURN rule from PR: https://github.com/kubeovn/kube-ovn/pull/937
