### ISSUE TITLE
How to create a mirror (span) port and move the mirror into a pod

### ISSUE THREAD

**Issue by l-rossetti** [kubeovn/kube-ovn#1288]
### Feature request

Is it possible to add a mirror port into the ovs bridge and then to inject a veth pair into a pod (via specific annotation) to allow this  pod to make network monitoring?
I've seen that the mirroring can be enabled both globally (mirroring the traffic of each pod) or selectively for specific pods via an annotation. But as far as I understand from kube-ovn documentation, this traffic can be monitored only by directly accessing the kubernetes node running the ovs-bridge, while I need the mirrored traffic to be available in a specific pod. 

If my understanding is correct, the only way I see to dump the mirrored traffic from a pod is to run a pod within the root network namespace of the node. But this way the pod would be able to "see" all the interface cards which are present on the node.

### Use case

To monitor the traffic of a set of pods from within a specific pod that runs a network monitoring application (e.g. ntopng). The pod executing the monitoring must be able to "see" only the mirror interface and not all the interfaces of the kubernetes node (e.g. if the pod runs in host network namespace).

**Comment by l-rossetti** [comment]
> It's an interesting use case. One manually method I came up with is to run your monitor pod in container network and then use linux commands to move the mirror0 interface into the pod network ns.

That's exactly what I'm doing right now: I'm manually moving mirror0 into the monitoring pod net-ns. But I'm facing an issue: do you have any clue on how to move mirror0 by using a pod configured with `hostNetwork: true` but `hostPID: false`? 
With this configuration I can mount the `/var/run/netns` hostPath so that `ip netns list` shows the list of netns and then I can run ip link set mirror0  netns <NET_NS> but I don't know which namespace to target (e.g. the ns of the pod running the monitoring):
```
cni-86407706-0954-f561-6849-d965713dcaee (id: 4)
cni-1c986c9b-79a2-f399-1bc5-b6330c469bf2 (id: 1)
cni-5a5cd4ce-8f39-016a-f17a-b50693bbe105 (id: 14)
cni-fd36118f-f851-f735-0122-faf7920a8ba6 (id: 15)
cni-c98d5df0-86af-877a-9fbb-4e5a80a5a4e5 (id: 12)
```


>  I think we can add a new annotation, when a pod carry it, then the CNI move mirror0 into it. Is this what you expect?

This what I expect! Moreover it would be very useful to allow the creation of multiple mirror ports. For example I would like to have the traffic of pod0 and pod1 mirrored to mirror0 and the traffic of all pods (so pod0, pod1, podN) to mirror1. This way a tenant could monitor its pods, while the SOC team could monitor the whole node.
Do you think it's reasonable?

**Comment by oilbeater** [comment]
> But I'm facing an issue: do you have any clue on how to move mirror0

I run `ip link set mirror0 netns /proc/<Pod PID>/ns/net` to move mirror0 into a running pod and then `nsenter --net=/proc/<Pood PID>/ns/net ip link set mirror0 up` it works. It doesn't need special hostNetwork or hostPID configure for pod.

Different levels of mirror is a much more complex work, it requires another set of CRDs and controllers to implement. As it only affect ovs mirror config, I prefer to use another program to do all the advanced mirror configure.

**Comment by l-rossetti** [comment]
> I run ip link set mirror0 netns /proc/<Pod PID>/ns/net to move mirror0 into a running pod and then nsenter --net=/proc/<Pood PID>/ns/net ip link set mirror0 up it works. It doesn't need special hostNetwork or hostPID configure for pod.

Are you running these cmds from the node or from a pod? Cause in my case I'm running from a pod with the following setup:
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ovs-mirror-setup
  labels:
    tier: node
    app: ovs-mirror-setup
spec:
  selector:
    matchLabels:
      app: ovs-mirror-setup
  template:
    metadata:
      labels:
        tier: node
        app: ovs-mirror-setup
    spec:
      hostNetwork: true
      containers:
      - image: alpine
        command: ["/bin/sh"]
        args: ["-c", "/run.sh"]
        imagePullPolicy: IfNotPresent
        name: ovs-mirror-setup
        securityContext:
          capabilities:
            add: ["NET_ADMIN", "SYS_ADMIN"]
        volumeMounts:
        - mountPath: /var/run/openvswitch
          name: ovs-var-run
        - mountPath: /var/run/netns
          name: netns
      volumes:
      - name: ovs-var-run
        hostPath:
          path: /var/run/openvswitch
          type: ""
      - name: netns
        hostPath:
          path: /var/run/netns
          type: ""
```
By adding  `SYS_ADMIN` capability I'm able to run `nsenter --net=/var/run/netns/cni-86407706-0954-f561-6849-d965713dcaee  ip a`, while without it `nsenter` returns `operation not permitted`.  
The only way I can interact with the NS keeping only `NET_ADMIN` cap and `hostNetwork: true` is to avoid `nsenter` and run `ip link set mirror0 netns <NAMESPACE_NAME>.` This way it doesn't require to have access to the host pids, but I don't know how to understand which namespace_ID is related to which pod. 

I'm trying to avoid having a pod with high level privileges
