### ISSUE TITLE
New Created Subnet unable connect to Internet

### ISSUE THREAD

**Issue by ikandars** [kubeovn/kube-ovn#1294]
Hi,

I was successfully created new subnet `subnet-gateway` under default VPC (ovn-cluster). The manifest like:

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet-gateway
spec:
  protocol: IPv4
  default: false
  namespaces:
  - default
  cidrBlock: 10.10.0.0/16
  gateway: 10.10.0.1
  excludeIps:
  - 10.10.0.1
  private: true
  allowSubnets:
  - 10.16.0.0/16
  - 10.18.0.0/16
  gatewayType: distributed
  natOutgoing: false
```

when I run `kubectl get subnet` the results is:

```bash
NAME             PROVIDER   VPC           PROTOCOL   CIDR            PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS
join             ovn        ovn-cluster   IPv4       100.64.0.0/16   false     false   false     distributed   1        65532         0        0             ["100.64.0.1"]
ovn-default      ovn        ovn-cluster   IPv4       10.0.0.0/16     false     true    true      distributed   24       65509         0        0             ["10.0.0.1"]
subnet-gateway   ovn        ovn-cluster   IPv4       10.10.0.0/16    true      false   false     distributed   1        65532         0        0             ["10.10.0.1"]
```

When I create a new pod under `default` namespace, the pod has correct IP, which is `10.10.0.2`. The problem is, I'm not able to make a request to internet from within the pod. But, when I create a pod under default subnet (ovn-default) everything works as expected.

Any ide, where I did some wrong?
