### ISSUE TITLE
 vlan do not  work

### ISSUE THREAD

**Issue by yuchen-sun** [kubeovn/kube-ovn#1302]
# Expected Behavior
vlan work
# Actual Behavior

# Steps to Reproduce the Problem

1. create a pr and vlan.
```yaml
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: public-ip
spec:
    defaultInterface: bond0.1101

---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan1
spec:
  id: 1101
  provider: public-ip
```
2. create subnet and a pod
```yaml
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net1
spec:
  cidrBlock: 10.181.2.0/24
  provider: public-ip.default.ovn
  gateway: 10.181.2.254
  disableGatewayCheck: true
  vlan: vlan1
```
3. create pod
```yaml
...
   annotations:
        public-ip.default.ovn.kubernetes.io/allow_live_migration: 'true'
        public-ip.default.ovn.kubernetes.io/default_route: "true"
        public-ip.default.ovn.kubernetes.io/ip_address: 10.181.2.15
        public-ip.default.ovn.kubernetes.io/logical_switch: net1
        public-ip.default.ovn.kubernetes.io/mac_address: '00:00:00:28:28:30'
...
```
4. pod network do not work, can't ping the gateway

# Additional Info

- Kubernetes version:

```bash
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6", GitCommit:"f59f5c2fda36e4036b49ec027e556a15456108f0", GitTreeState:"clean", BuildDate:"2022-01-19T17:26:47Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}  

```

- kube-ovn version:
  
```bash
v1.9.0
```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
```bash
4.18.0-348.el8.0.2.x86_64
 ```

route -n 
```
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.81.128.254   0.0.0.0         UG    300    0        0 bond0
0.0.0.0         10.181.2.254    0.0.0.0         UG    400    0        0 bond0.1101
10.16.0.0       100.64.0.1      255.255.0.0     UG    0      0        0 ovn0
10.81.128.0     0.0.0.0         255.255.255.0   U     300    0        0 bond0
10.181.1.0      100.64.0.1      255.255.255.0   UG    0      0        0 ovn0
10.181.2.0      100.64.0.1      255.255.255.0   UG    0      0        0 ovn0
10.181.2.0      0.0.0.0         255.255.255.0   U     400    0        0 bond0.1101
100.64.0.0      0.0.0.0         255.255.0.0     U     0      0        0 ovn0
```
