### ISSUE TITLE
Ask: ConfigMap example to run Distributed External Gateway

### ISSUE THREAD

**Issue by ikandars** [kubeovn/kube-ovn#1306]
Hi,

In this page https://github.com/kubeovn/kube-ovn/blob/master/docs/snat-and-eip.md it provide an example configMap to run centralized external gateway. Can you also provide distributed type external gateway configMap example?

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  type: "distributed"
  external-gw-nodes: "kube-ovn-worker"  # which node name should I put in this directive?
  external-gw-nic: "eth1"               # this nic name should be same for all node right?
  nic-ip: "172.56.0.1/16"               # what about this nec IP
  nic-mac: "16:52:f3:13:6a:25"          # and what about this nec mac?
```

thanks in advanced
