### ISSUE TITLE
When use multus with default-network annotation, controller addds wrong address annotations 

### ISSUE THREAD

**Issue by oilbeater** [kubeovn/kube-ovn#1341]
# Expected Behavior
kube-ovn-controller should add annotations with `ovn.kubernetes.io`
# Actual Behavior
kube-ovn-controller adds annotations with `default.default.kubernetes.io` and pods cannot running
# Steps to Reproduce the Problem

1. create NetworkAttachmentDefinition
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: default
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox.com/cx5_sriov_switchdev
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "kube-ovn",
    "plugins":[
        {
            "type":"kube-ovn",
            "server_socket":"/run/openvswitch/kube-ovn-daemon.sock"
        },
        {
            "type":"portmap",
            "capabilities":{
                "portMappings":true
            }
        }
    ]
}'

```
2. create a pod
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    v1.multus-cni.io/default-network: default
spec:
  containers:
  - name: nginx
    image: nginx:alpine
```
