### ISSUE TITLE
kubeovn通过Pod注解来固定Pod ip，但是kubevirt的launcher pod是自动创建的，如何设置launcher pod的注解呢

### ISSUE THREAD

**Issue by hurdonkey** [kubeovn/kube-ovn#1374]
请问是否有配合kubevirt使用的相关文档呢，非常感谢！目前只找到这个热迁移文档 https://github.com/fanriming/kube-ovn/wiki/kubevirt-%E8%99%9A%E6%9C%BA%E7%83%AD%E8%BF%81%E7%A7%BB
对于该文档有些疑问，kubevirt的launcher Pod是自动创建的，而且每次重启虚机Pod会销毁再重新创建，请问kube-ovn相关的注解是如何设置到kubevirt的launcher Pod中呢。

本地测试将注解设置到VM并未生效，创建文件如下：

``` yaml
# Kube-OVN 类型的网络
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: attachnet-kubeovn
  namespace: kubevirt-demo
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "attachnet-kubeovn.kubevirt-demo.ovn"
    }'
# 以kube-ovn作为附加网卡, provider 应该设置为对应的 NetworkAttachmentDefinition的<name>.<namespace>.ovn,要以ovn作为后缀结束, 用kube-ovn提供附加网卡，创建subnet示例如下
---
apiVersion: "kubeovn.io/v1"
kind: Subnet
metadata:
  name: attachnet-kubeovn-subnet
spec:
  protocol: IPv4
  provider: attachnet-kubeovn.kubevirt-demo.ovn
  cidrBlock: 172.17.0.0/16
  excludeIps:
  - 172.17.0.0..172.17.0.10
  gateway: 172.17.0.1
  gatewayType: distributed   # 分布式网关
  natOutgoing: true
```

``` yaml
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: img-centos-7-cloudimage-v1-vm
  namespace: kubevirt-demo
  annotations:
    # attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/logical_switch: net1
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/allow_live_migration: 'true'    # allow_live_migration 则不做地址冲突检查
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/default_route: 'true'           # 为非默认网卡指定默认路由
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/ip_address: 172.17.0.200
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/mac_address: '00:00:00:28:28:30'
  labels:
    kubevirt.io/vm: img-centos-7-cloudimage-v1-vm
spec:
  running: true
  # runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: img-centos-7-cloudimage-v1-vm
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 1024M

        devices:
          disks:
          - disk:
              bus: virtio
            name: disk-system

          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk

          interfaces:
          - name: default
            masquerade: {}

      networks:
      - name: default
        pod: {}

      volumes:
      - persistentVolumeClaim:
          claimName: img-centos-7-cloudimage-v1    # new image template pvc name
        name: disk-system

      - cloudInitNoCloud:
          userData: |
            #cloud-config
            #hostname: vm1
            ssh_pwauth: True
            disable_root: false
            password: 123456
            chpasswd: { expire: False }
        name: cloudinitdisk
```

以下是生成的launcher Pod 注解, 还是使用了自动分配的IP

```
metadata:
  annotations:
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/allocated: "true"
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/cidr: 172.17.0.0/16
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/gateway: 172.17.0.1
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/ip_address: 172.17.0.14
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/logical_router: ovn-cluster
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/logical_switch: attachnet-kubeovn-subnet
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/mac_address: 00:00:00:E4:EE:18
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/network_type: geneve
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/pod_nic_type: veth-pair
    attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/routed: "true"
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "kube-ovn",
          "ips": [
              "192.168.0.107"
          ],
          "default": true,
          "dns": {}
      },{
          "name": "attachnet-kubeovn",
          "ips": [
              "172.17.0.14"
          ],
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","name":"attachnet-kubeovn","namespace":"kubevirt-demo"}]'
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "kube-ovn",
          "ips": [
              "192.168.0.107"
          ],
          "default": true,
          "dns": {}
      },{
          "name": "attachnet-kubeovn",
          "ips": [
              "172.17.0.14"
          ],
          "dns": {}
      }]
    kubevirt.io/domain: img-centos-7-cloudimage-v2-vm
    kubevirt.io/migrationTransportUnix: "true"
    ovn.kubernetes.io/allocated: "true"
    ovn.kubernetes.io/cidr: 192.168.0.0/16
    ovn.kubernetes.io/gateway: 192.168.0.1
    ovn.kubernetes.io/ip_address: 192.168.0.107
    ovn.kubernetes.io/logical_router: ovn-cluster
    ovn.kubernetes.io/logical_switch: ovn-default
    ovn.kubernetes.io/mac_address: 00:00:00:5E:6E:FF
    ovn.kubernetes.io/network_type: geneve
    ovn.kubernetes.io/pod_nic_type: veth-pair
    ovn.kubernetes.io/routed: "true"
    post.hook.backup.velero.io/command: '["/usr/bin/virt-freezer", "--unfreeze", "--name",
      "img-centos-7-cloudimage-v2-vm", "--namespace", "kubevirt-demo"]'
    post.hook.backup.velero.io/container: compute
    pre.hook.backup.velero.io/command: '["/usr/bin/virt-freezer", "--freeze", "--name",
      "img-centos-7-cloudimage-v2-vm", "--namespace", "kubevirt-demo"]'
    pre.hook.backup.velero.io/container: compute
  creationTimestamp: "2022-03-10T07:31:09Z"
  generateName: virt-launcher-img-centos-7-cloudimage-v2-vm-
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/created-by: 83cf349a-0b08-48ba-8a38-5583d2b51c5a
    kubevirt.io/vm: img-centos-7-cloudimage-v2-vm
```
