### ISSUE TITLE
kubevirt使用kube-ovn固定虚机IP和热迁移相关问题

### ISSUE THREAD

**Issue by hurdonkey** [kubeovn/kube-ovn#1376]
kubevirt使用kube-ovn固定虚机IP和热迁移相关问题
kubevrit版本0.49，kube-ovn版本1.9.0

1. kubevrit使用kubeovn固定IP，测试热迁移失败
VM配置如下，给multus网卡分配kubeovn子网并固定IP，开启迁移选项allow_live_migration
```
  template:
    metadata:
      annotations:
        attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/logical_switch: attachnet-kubeovn-subnet
        attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/allow_live_migration: 'true'    # allow_live_migration 则不做地址冲突检查
        attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/default_route: 'true'           # 为非默认网卡指定默认路由
        attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/ip_address: 172.17.0.203
        attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/mac_address: '00:00:00:53:6B:B6'
    spec:
      evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 1
        resources:
          requests:
            memory: 1024M

        devices:
          disks:
          - disk:
              bus: virtio
            name: disk-system

          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk

          interfaces:
          - name: attachnet-kubeovn
            bridge: {}

      networks:
        - multus:
            networkName: kubevirt-demo/attachnet-kubeovn
          name: attachnet-kubeovn
```

如图，创建的虚机成功获取到了固定IP
![image](https://user-images.githubusercontent.com/12184093/157817318-b51845f2-a3c2-4701-ba7d-58add6a76ffe.png)

执行热迁移命令，新创建的launcher Pod无法启动

``` bash
virtctl migrate img-centos-7-cloudimage-v4-vm
```
![image](https://user-images.githubusercontent.com/12184093/157817483-7e58815a-5baf-446a-9cb0-655752c5611d.png)

应该是在multus网卡获取IP处报错了
![image](https://user-images.githubusercontent.com/12184093/157817243-46180d3f-8c12-49f9-8e56-d7d1663e9bb6.png)

2. 另外当虚机中只加固定MAC的注解不加固定IP的注解时，发现并没有使用指定的MAC地址，和文档第三条说明不符
https://github.com/kubeovn/kube-ovn/wiki/Pod-%E5%9B%BA%E5%AE%9A-IP-%E5%92%8C-Mac

``` yaml
        attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/logical_switch: attachnet-kubeovn-subnet
        attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/allow_live_migration: 'true'    # allow_live_migration 则不做地址冲突检查
        attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/default_route: 'true'           # 为非默认网卡指定默认路由
        # attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/ip_address: 172.17.0.203
        attachnet-kubeovn.kubevirt-demo.ovn.kubernetes.io/mac_address: '00:00:00:53:6B:B6'
```

如图，VMI的上有MAC相关注解
![image](https://user-images.githubusercontent.com/12184093/157819685-49d3f454-978d-45a7-9c21-38fff94ddc4a.png)

但是launcher Pod 注解和 虚机内部并没有使用该MAC地址
![image](https://user-images.githubusercontent.com/12184093/157819815-39dc199c-cb2e-4cb8-8567-f911e0577369.png)

![image](https://user-images.githubusercontent.com/12184093/157819902-388d777c-7dd8-4831-bb36-70e492188da5.png)

3. 请问OVN是否可以设置根据MAC地址来绑定IP地址，这样是否可以在固定IP的同时 也能够用ovn的dhcp分配的IP
