### ISSUE TITLE
External network connection problem

### ISSUE THREAD

**Issue by mkcetinkaya** [kubeovn/kube-ovn#1469]
Hello,

If we use isolation between subnets/namespaces, then we could not reach internet also. As far as I see from documentation, only allowed subnet is reachable but there is no way to define internet like 0.0.0.0. 

So could you please help us to find a solution for only isolating subnets without preventing access to internet?

Thanks and regards

**Comment by oilbeater** [comment]
@mkcetinkaya we have implemented a new ACL function in master branch which provide fine-grained access control like below 
```yaml
spec:
  acls:                                                
  - action: reject
    direction: to-lport
    match: ip4.src==10.16.0.12 && ip4.dst==2.2.0.3
    priority: 2022
  - action: allow
    direction: to-lport
    match: ip4.src==10.16.0.12 && ip4.dst==2.2.0.2
    priority: 2222
```

Maybe this new function can help you
