### ISSUE TITLE
Do not Recreate Logical_Router_Port when Vpc recreated

### ISSUE THREAD

**Issue by lrh3321** [kubeovn/kube-ovn#1569]
# Expected Behavior

```shell
$ kubectl-ko nbctl show alpine-vpc
router abae48a2-6e93-4338-a586-0a720e29eea6 (alpine-vpc)
    port alpine-vpc-alpine-subnet-2
        mac: "00:00:00:92:35:DB"
        networks: ["172.24.0.1/16"]
    port alpine-vpc-alpine-subnet-1
        mac: "00:00:00:47:C9:3D"
        networks: ["172.23.0.1/16"]
```

# Actual Behavior

```shell
$ kubectl-ko nbctl show alpine-vpc
router abae48a2-6e93-4338-a586-0a720e29eea6 (alpine-vpc)
```

# Steps to Reproduce the Problem

1. `kubectl create -f vpc-subnet.yaml`
2. `kubectl delete vpc alpine-vpc`
3. `kubectl apply -f vpc-subnet.yaml`

`vpc-subnet.yaml`

```yaml
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: alpine-vpc
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: alpine-subnet-1
spec:
  cidrBlock: 172.23.0.0/16
  default: false
  disableGatewayCheck: false
  disableInterConnection: false
  gateway: 172.23.0.1
  gatewayNode: ""
  gatewayType: distributed
  logicalGateway: false
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: alpine-vpc
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: alpine-subnet-2
spec:
  cidrBlock: 172.24.0.0/16
  default: false
  disableGatewayCheck: false
  disableInterConnection: false
  gateway: 172.24.0.1
  gatewayNode: ""
  gatewayType: distributed
  logicalGateway: false
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: alpine-vpc
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

  ```

- kube-ovn version:
  
  ```
  v1.10.0
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  "CentOS Stream 8"
  5.4.181-1.el8.elrepo.x86_64
  ```
