### ISSUE TITLE
kube-ovn 1.10.3 probably occurs that vpc router port created failled

### ISSUE THREAD

**Issue by bobz965** [kubeovn/kube-ovn#1695]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1. create a vpc with 8 subnets (8 lrps)

we tested 3 times, 4/8 2/8 1/8 lrp created failed

2. create a vpc with 4 subnets 

also, 1/4 lrp create failed

3. not occured in kube-ovn 1.10.0 (first version)

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version:
  
  ```
1.10.3  


  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
CentOS Stream
5.4.205-1.el8.elrepo.x86_64

  ```

# our test yaml
``` yaml

[root@hci-ctrl-1 yealink]# cat 00.namespace.yaml 
apiVersion: v1
kind: Namespace
metadata:
  name: vpc-yealink



[root@hci-ctrl-1 yealink]# cat 01.vpc.yaml
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc-yealink
spec:
  namespaces:
  - vpc-yealink
  staticRoutes:
  # 出口路由设置
  - cidr: 172.17.0.0/16
    nextHopIP: 172.17.0.2
    policy: policySrc

  - cidr: 172.18.0.0/16
    nextHopIP: 172.18.0.2
    policy: policySrc

  - cidr: 172.19.0.0/16
    nextHopIP: 172.19.0.2
    policy: policySrc

  - cidr: 172.20.0.0/16
    nextHopIP: 172.20.0.2
    policy: policySrc

  - cidr: 172.21.0.0/16
    nextHopIP: 172.21.0.2
    policy: policySrc

  - cidr: 172.22.0.0/16
    nextHopIP: 172.22.0.2
    policy: policySrc

  - cidr: 172.23.0.0/16
    nextHopIP: 172.23.0.2
    policy: policySrc

  - cidr: 172.24.0.0/16
    nextHopIP: 172.24.0.2
    policy: policySrc

  - cidr: 172.25.0.0/16
    nextHopIP: 172.25.0.2
    policy: policySrc

  - cidr: 172.26.0.0/16
    nextHopIP: 172.26.0.2
    policy: policySrc

  #- cidr: 172.29.0.0/16
  #  nextHopIP: 172.21.0.10
  #  policy: policyDst


[root@hci-ctrl-1 yealink]# cat 02.subnet.yaml
---
# 上海区 - L1 虚拟机网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc-yealink-shanghai-vm
spec:
  # 所属vpc
  vpc: vpc-yealink
  # 绑定到此子网的命名空间列表。如果要将命名空间绑定到此子网，请编辑命名空间名称并将其添加到此字段。
  # 【注 1】由于cdi组件临时生成的pod在vpc场景下无法使用dns，所以不要将子网绑定到namespace，
  #         这样cdi组件临时生成的pod就使用ovn-default网络，从而可以使用dns了。
  #         但这样的话就要求所有pod全部需要指定子网。
  # 【注 2】不能将多个subnet绑定到同一个namespace。
  #namespaces:
  #- vpc-yealink
  protocol: IPv4
  # 子网的CIDR
  cidrBlock: 172.17.0.0/16
  # 不想被分配的IP地址或地址段。如果未设置，则网关地址会被自动加入excludeIPs列表
  excludeIps:
  - 172.17.0.1..172.17.191.255     # 【注 3】其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址 
---
# 上海区 - L2 POD网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc-yealink-shanghai-pod
  labels:
    app.kubernetes.io/managed-by: ip-address-operator
    topology.kubernetes.io/region: shanghai
    topology.kubernetes.io/zone: "01"
spec:
  # 所属vpc
  vpc: vpc-yealink
  # 绑定到此子网的命名空间列表。如果要将命名空间绑定到此子网，请编辑命名空间名称并将其添加到此字段。
  # 【注 1】由于cdi组件临时生成的pod在vpc场景下无法使用dns，所以不要将子网绑定到namespace，
  #         这样cdi组件临时生成的pod就使用ovn-default网络，从而可以使用dns了。
  #         但这样的话就要求所有pod全部需要指定子网。
  # 【注 2】不能将多个subnet绑定到同一个namespace。
  #namespaces:
  #- vpc-yealink
  protocol: IPv4
  # 子网的CIDR
  cidrBlock: 172.18.0.0/16
  # 不想被分配的IP地址或地址段。如果未设置，则网关地址会被自动加入excludeIPs列表
  excludeIps:
  - 172.18.0.1..172.18.191.255     # 【注 3】其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址 

---

# 欧洲区 - L1 虚拟机网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc-yealink-europe-vm
spec:
  # 所属vpc
  vpc: vpc-yealink
  # 绑定到此子网的命名空间列表。如果要将命名空间绑定到此子网，请编辑命名空间名称并将其添加到此字段。
  # 【注 1】由于cdi组件临时生成的pod在vpc场景下无法使用dns，所以不要将子网绑定到namespace，
  #         这样cdi组件临时生成的pod就使用ovn-default网络，从而可以使用dns了。
  #         但这样的话就要求所有pod全部需要指定子网。
  # 【注 2】不能将多个subnet绑定到同一个namespace。
  #namespaces:
  #- vpc-yealink
  protocol: IPv4
  # 子网的CIDR
  cidrBlock: 172.19.0.0/16
  # 不想被分配的IP地址或地址段。如果未设置，则网关地址会被自动加入excludeIPs列表
  excludeIps:
  - 172.19.0.1..172.19.191.255     # 【注 3】其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址 
---
# 欧洲区 - L2 POD网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc-yealink-europe-pod
  labels:
    app.kubernetes.io/managed-by: ip-address-operator
    topology.kubernetes.io/region: europe
    topology.kubernetes.io/zone: "01"
spec:
  # 所属vpc
  vpc: vpc-yealink
  # 绑定到此子网的命名空间列表。如果要将命名空间绑定到此子网，请编辑命名空间名称并将其添加到此字段。
  # 【注 1】由于cdi组件临时生成的pod在vpc场景下无法使用dns，所以不要将子网绑定到namespace，
  #         这样cdi组件临时生成的pod就使用ovn-default网络，从而可以使用dns了。
  #         但这样的话就要求所有pod全部需要指定子网。
  # 【注 2】不能将多个subnet绑定到同一个namespace。
  #namespaces:
  #- vpc-yealink
  protocol: IPv4
  # 子网的CIDR
  cidrBlock: 172.20.0.0/16
  # 不想被分配的IP地址或地址段。如果未设置，则网关地址会被自动加入excludeIPs列表
  excludeIps:
  - 172.20.0.1..172.20.191.255     # 【注 3】其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址 

---

# 深圳区 - L1 虚拟机网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc-yealink-shenzhen-vm
spec:
  # 所属vpc
  vpc: vpc-yealink
  # 绑定到此子网的命名空间列表。如果要将命名空间绑定到此子网，请编辑命名空间名称并将其添加到此字段。
  # 【注 1】由于cdi组件临时生成的pod在vpc场景下无法使用dns，所以不要将子网绑定到namespace，
  #         这样cdi组件临时生成的pod就使用ovn-default网络，从而可以使用dns了。
  #         但这样的话就要求所有pod全部需要指定子网。
  # 【注 2】不能将多个subnet绑定到同一个namespace。
  #namespaces:
  #- vpc-yealink
  protocol: IPv4
  # 子网的CIDR
  cidrBlock: 172.21.0.0/16
  # 不想被分配的IP地址或地址段。如果未设置，则网关地址会被自动加入excludeIPs列表
  excludeIps:
  - 172.21.0.1..172.21.191.255     # 【注 3】其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址 
---
# 深圳区 - L2 POD网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc-yealink-shenzhen-pod
  labels:
    app.kubernetes.io/managed-by: ip-address-operator
    topology.kubernetes.io/region: shenzhen
    topology.kubernetes.io/zone: "01"
spec:
  # 所属vpc
  vpc: vpc-yealink
  # 绑定到此子网的命名空间列表。如果要将命名空间绑定到此子网，请编辑命名空间名称并将其添加到此字段。
  # 【注 1】由于cdi组件临时生成的pod在vpc场景下无法使用dns，所以不要将子网绑定到namespace，
  #         这样cdi组件临时生成的pod就使用ovn-default网络，从而可以使用dns了。
  #         但这样的话就要求所有pod全部需要指定子网。
  # 【注 2】不能将多个subnet绑定到同一个namespace。
  #namespaces:
  #- vpc-yealink
  protocol: IPv4
  # 子网的CIDR
  cidrBlock: 172.22.0.0/16
  # 不想被分配的IP地址或地址段。如果未设置，则网关地址会被自动加入excludeIPs列表
  excludeIps:
  - 172.22.0.1..172.22.191.255     # 【注 3】其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址 

---

# 香港区 - L1 虚拟机网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc-yealink-hongkong-vm
spec:
  # 所属vpc
  vpc: vpc-yealink
  # 绑定到此子网的命名空间列表。如果要将命名空间绑定到此子网，请编辑命名空间名称并将其添加到此字段。
  # 【注 1】由于cdi组件临时生成的pod在vpc场景下无法使用dns，所以不要将子网绑定到namespace，
  #         这样cdi组件临时生成的pod就使用ovn-default网络，从而可以使用dns了。
  #         但这样的话就要求所有pod全部需要指定子网。
  # 【注 2】不能将多个subnet绑定到同一个namespace。
  #namespaces:
  #- vpc-yealink
  protocol: IPv4
  # 子网的CIDR
  cidrBlock: 172.23.0.0/16
  # 不想被分配的IP地址或地址段。如果未设置，则网关地址会被自动加入excludeIPs列表
  excludeIps:
  - 172.23.0.1..172.23.191.255     # 【注 3】其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址 
---
# 香港区 - L2 POD网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc-yealink-hongkong-pod
  labels:
    app.kubernetes.io/managed-by: ip-address-operator
    topology.kubernetes.io/region: hongkong
    topology.kubernetes.io/zone: "01"
spec:
  # 所属vpc
  vpc: vpc-yealink
  # 绑定到此子网的命名空间列表。如果要将命名空间绑定到此子网，请编辑命名空间名称并将其添加到此字段。
  # 【注 1】由于cdi组件临时生成的pod在vpc场景下无法使用dns，所以不要将子网绑定到namespace，
  #         这样cdi组件临时生成的pod就使用ovn-default网络，从而可以使用dns了。
  #         但这样的话就要求所有pod全部需要指定子网。
  # 【注 2】不能将多个subnet绑定到同一个namespace。
  #namespaces:
  #- vpc-yealink
  protocol: IPv4
  # 子网的CIDR
  cidrBlock: 172.24.0.0/16
  # 不想被分配的IP地址或地址段。如果未设置，则网关地址会被自动加入excludeIPs列表
  excludeIps:
  - 172.24.0.1..172.24.191.255     # 【注 3】其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址 
---




```
