### ISSUE TITLE
 iptables-eip 和  iptables-snat-rule 无法删除

### ISSUE THREAD

**Issue by flyfish002** [kubeovn/kube-ovn#1847]
1. 删除问题，删除一个无用的 iptables-eip 发现卡住很长时间

root@master:~#`kubectl delete  iptables-eip   ns1-vpc1-sub181-eips1`
iptableseip.kubeovn.io "ns1-vpc1-sub181-eips1" deleted

 查看 kube-ovn 日志  原因为  ns1-vpc1-sub181-natgw (vpc-nat-gateway 已经删除)，删除  iptables-eip  会先查找是否已经删除之前相关联的 ns1-vpc1-sub181-natgw (vpc-nat-gateway )
进行此操作前已经执行` kubectl  delete   vpc-nat-gateway    ns1-vpc1-sub181-natgw`  (对不用的 vpc-nat-gateway 进行删除)

root@master:~#`kubectl  logs  kube-ovn-controller-54885554d8-xpvtk   -n  kube-system `
I0824 07:43:23.238773       7 pod.go:391] take 16 ms to handle update pod ns4/nginx-ns4-vpc4-sub181-c1
E0824 07:50:35.488225       7 vpc_nat_gw_eip.go:360] failed to clean eip 'ns1-vpc1-sub181-eips1' in pod, pod 'ns1-vpc1-sub181-natgw' not exist
E0824 07:50:35.488307       7 vpc_nat_gw_eip.go:178] error syncing 'ns1-vpc1-sub181-eips1': pod 'ns1-vpc1-sub181-natgw' not exist, requeuing
E0824 07:50:37.493865       7 vpc_nat_gw_eip.go:360] failed to clean eip 'ns1-vpc1-sub181-eips1' in pod, pod 'ns1-vpc1-sub181-natgw' not exist
E0824 07:50:37.493936       7 vpc_nat_gw_eip.go:178] error syncing 'ns1-vpc1-sub181-eips1': pod 'ns1-vpc1-sub181-natgw' not exist, requeuing

2. 删除问题，删除一个无用的 iptables-snat-rule  发现卡住很长时间 
root@master:~#`kubectl delete   iptables-snat-rule  ns1-vpc1-sub181-snat1  `
iptablessnatrule.kubeovn.io "ns1-vpc1-sub181-snat1" deleted

查看 kube-ovn 日志  原因为  ns1-vpc1-sub181-natgw(vpc-nat-gateway 已经删除)，删除 iptables-snat-rule  会先查找是否已经删除之前相关联的 ns1-vpc1-sub181-natgw (vpc-nat-gateway )
root@master:~#`kubectl  logs  kube-ovn-controller-54885554d8-xpvtk   -n  kube-system `
E0824 07:58:25.550054       7 vpc_nat_gw_nat.go:470] error syncing 'ns1-vpc1-sub181-snat1': pod 'ns1-vpc1-sub181-natgw' not exist, requeuing
E0824 07:58:27.561088       7 vpc_nat_gw_nat.go:1571] failed to get nat gw pod, pod 'ns1-vpc1-sub181-natgw' not exist
E0824 07:58:27.561107       7 vpc_nat_gw_nat.go:949] failed to delete snat, pod 'ns1-vpc1-sub181-natgw' not exist
E0824 07:58:27.561132       7 vpc_nat_gw_nat.go:470] error syncing 'ns1-vpc1-sub181-snat1': pod 'ns1-vpc1-sub181-natgw' not exist, requeuing

**Comment by bobz965** [comment]
这个应该是删除顺序的问题，感觉应该 先删除eip 和 snat crd，再清理nat-gw pod比较好。
因为使用这个eip和nat，默认是要求先创建nat gw ，再创建eip nat这些crd的，删除的话，应该是创建逻辑的逆操作。
这样操作的话可以规避该问题。

当然， 代码也可以再完善一点，允许先清理nat-gw，再删除crd，后续我看下

**Comment by bobz965** [comment]
same as #1888， fixed

**Comment by JBNRZ** [comment]
v1.14.1 有类似的这个问题，必须要先删除eip才能删除subnet

```
apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: test-vpc-1
spec:
  namespaces:
  - ns1
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: net1
spec:
  vpc: test-vpc-1
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  namespaces:
    - ns1
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ns1
  name: pod-1-1
  annotations:
    ovn.kubernetes.io/logical_switch: "net1"
    ovn.kubernetes.io/ip_address: "10.0.1.10"
spec:
  containers:
    - name: test-1-1
      image: nicolaka/netshoot:v0.13
      command: ["sleep", "infinity"]
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 10.233.0.0/16
  gateway: 10.233.233.233  # IP address of the physical gateway
  excludeIps:
  - 10.233.0.1..10.233.233.255
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens192",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-vpc-nat-config
  namespace: kube-system
data:
  image: 'docker.io/kubeovn/vpc-nat-gateway:v1.14.1' 
  nodeSelector: |
    kubernetes.io/hostname: k8s-node3-virtual-machine
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-vpc-nat-gw-config
  namespace: kube-system
data:
  enable-vpc-nat-gw: 'true'
---
apiVersion: kubeovn.io/v1
kind: VpcNatGateway
metadata:
  name: gw1
spec:
  vpc: test-vpc-1
  subnet: net1
  lanIp: 10.0.1.254
  selector:
    - "kubernetes.io/hostname: k8s-node3-virtual-machine"
    - "kubernetes.io/os: linux"
  externalSubnets:
    - ovn-vpc-external-network
---
apiVersion: kubeovn.io/v1
kind: IptablesEIP
metadata:
  name: eip-random
spec:
  natGwDp: gw1
---
apiVersion: kubeovn.io/v1
kind: IptablesEIP
metadata:
  name: eipd01
spec:
  natGwDp: gw1
---
kind: IptablesDnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: dnat01
spec:
  eip: eipd01
  externalPort: '8888'
  internalIp: 10.0.1.10
  internalPort: '80'
  protocol: tcp
```

kube-ovn-controller 日志

```
failed to get ovn-vpc-nat-config, configmap "ovn-vpc-nat-config" not found
```
