### ISSUE TITLE
ovn-dpdk网络分配的ip未生效

### ISSUE THREAD

**Issue by htz2507** [kubeovn/kube-ovn#1890]
## Expected Behavior
pod中应该有两个ip，默认网络ip和ovn-dpdk网络ip
## Actual Behavior
pod中只有默认网络分配的ip, 没有ovn-dpdk网络分配的ip

## Steps to Reproduce the Problem

1. 按照教程配置好了dpdk,  https://kubeovn.github.io/docs/v1.10.x/en/advance/dpdk/
2. pod设置为ovn-dpdk的网络
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-deployment
  labels:
    app: vm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod
  template:
    metadata:
      labels:
        app: pod
      annotations:
        k8s.v1.cni.cncf.io/networks: default/ovn-dpdk
        ovn-dpdk.default.ovn.kubernetes.io/ip_address: 10.128.7.9
        ovn-dpdk.default.ovn.kubernetes.io/mac_address: 00:00:00:0A:30:89
    spec:
      nodeSelector:
        ovn.kubernetes.io/ovs_dp_type: userspace
      securityContext:
        runAsUser: 0
      volumes:
        - name: vhostuser-sockets
          emptyDir: {}
        - name: hugepage
          emptyDir:
            medium: HugePages-2Mi
        - name: libvirt-runtime
          emptyDir: {}
      containers:
        - name: vm
          image: support.myhci.com:5000/nginx:alpine
          securityContext:
            capabilities:
              add:
                - NET_BIND_SERVICE
                - SYS_NICE
                - NET_RAW
                - NET_ADMIN
            privileged: false
            runAsUser: 0
          resources:
            limits:
              cpu: '2'
              devices.kubevirt.io/kvm: '1'
              memory: '8784969729'
              hugepages-2Mi: 2Gi
            requests:
              cpu: 666m
              devices.kubevirt.io/kvm: '1'
              ephemeral-storage: 50M
              memory: '4490002433'
          volumeMounts:
            - name: vhostuser-sockets
              mountPath: /var/run/vm
            - mountPath: /dev/hugepages
              name: hugepage
            - name: libvirt-runtime
              mountPath: /var/run/libvirt
```
3. 登陆到pod中，查看pod的ip, 无10.128.7.9这个ip
```
[root@support ~]# oc exec -it pod-deployment-7b55df6d97-sq2ts -- sh
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
242: eth0@if243: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1400 qdisc noqueue state UP 
    link/ether 00:00:00:41:eb:c2 brd ff:ff:ff:ff:ff:ff
    inet 10.128.1.133/16 brd 10.128.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe41:ebc2/64 scope link 
       valid_lft forever preferred_lft forever

```

## Additional Info

- pod中无法ping通ip 10.128.7.9
```
[root@support ~]# oc exec -it pod-deployment-7b55df6d97-sq2ts -- sh
/ # ping 10.128.7.9
PING 10.128.7.9 (10.128.7.9): 56 data bytes

```

- ovn中已经有ip 10.128.7.9
```
[root@support ~]# oc exec -it ovn-central-587bfdc6c7-j6hhk -n kube-system -- bash
root@master1:/kube-ovn# ovn-nbctl show | grep 10.128.7.9
        addresses: ["00:00:00:0A:30:89 10.128.7.9"]
```

- ovs中有分配的端口
```
    Bridge br-int
        fail_mode: secure
        datapath_type: netdev
        Port br-int
            Interface br-int
                type: internal
        Port ovn-80d453-0
            Interface ovn-80d453-0
                type: geneve
                options: {csum="true", key=flow, remote_ip="172.20.200.124"}
        Port "98c29d31_net1_h"
            Interface "98c29d31_net1_h"
                type: dpdkvhostuserclient
                options: {vhost-server-path="/var/run/openvswitch/vhost_sockets/74b7d0e6-c938-45a3-8a2e-24e2fcb60fcb/vhostuser-sockets/sock"}
        Port a76fc8b7a187_h
            Interface a76fc8b7a187_h
        Port "20103b73e19f_h"
            Interface "20103b73e19f_h"
```
- ovs端口中对应的sock文件不存在
```
[root@worker2 core]# ll /var/run/openvswitch/vhost_sockets/74b7d0e6-c938-45a3-8a2e-24e2fcb60fcb/vhostuser-sockets/sock
ls: cannot access '/var/run/openvswitch/vhost_sockets/74b7d0e6-c938-45a3-8a2e-24e2fcb60fcb/vhostuser-sockets/sock': No such file or directory
```

- Kubernetes version:
```
  Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v0.21.0-beta.1", GitCommit:"52a2fd9", GitTreeState:"clean", BuildDate:"2022-02-08T01:26:19Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.1-1839+b93fd35dd03051-dirty", GitCommit:"b93fd35dd030519c24dd02f8bc2a7f873d2928cd", GitTreeState:"dirty", BuildDate:"2022-02-11T06:14:59Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (0.21) and server (1.22) exceeds the supported minor version skew of +/-1
```

- kube-ovn version:

```
  kube-ovn-v1.10.1
  kube-ovn-v1.10.5-dpdk
  ```

- operation-system/kernel version:

```
Fedora CoreOS 34
5.14.14-200.fc34.x86_64
  ```
