### ISSUE TITLE
External IP for Service Just Like Pod Has

### ISSUE THREAD

**Issue by ikandars** [kubeovn/kube-ovn#1916]
### Feature request

It would be nice if there is a way to assign external IP for service just like in pod level.

### Use case

Maybe something like this:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-svc
  annotations:
    ovn.kubernetes.io/eip: 103.1.8.20
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
   app: api
```
