### ISSUE TITLE
NetworkPolicy failed after updating labels of namespace or pod

### ISSUE THREAD

**Issue by lut777** [kubeovn/kube-ovn#1920]
# Expected Behavior
NetworkPolicy  should also work to a updated namespace or pod

# Actual Behavior
The updated namespace or pod is not bound by networkpolicy

# Steps to Reproduce the Problem

For namespace: 
1. create a networkpolicy like this:
```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-client-a-via-ns-selector
  namespace: x
spec:
  policyTypes:
    - Ingress
  podSelector:
    matchLabels:
      pod: a
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              ns2: updated
```

Check the tcp connection between pod a in ns x and pod b in ns y. It should work.

2.  Update namespace y with adding a new label: 
     ns2: updated

3.  Check the tcp connection between pod a in ns x and pod b in ns y. It should not work but it works.  

For pods:

networkpolicy:
```yaml
metadata:
  creationTimestamp: null
  name: allow-client-a-via-pod-selector
  namespace: x
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          pod: b
          pod2: updated
  podSelector:
    matchLabels:
      pod: a
  policyTypes:
  - Ingress
```

Almost the same procedure, but change the labels of pod with "pod2: updated"

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```
