### ISSUE TITLE
statefulset中pod的preStop勾子失去网络的问题

### ISSUE THREAD

**Issue by hugo345816** [kubeovn/kube-ovn#1953]
# Expected Behavior
在statefulset中的pod定义了preStop勾子，里面有网络操作的脚本，例如：
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-prestop
  labels:
    app: test-prestop
spec:
  serviceName: test-prestop
  replicas: 4
  selector:
    matchLabels:
      app: test-prestop
  template:
    metadata:
      name: test-prestop
      labels:
        app: test-prestop
    spec:
      containers:
      - name: busybox
        image: cr.yealink.top/system/busybox:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -ec
              - |
                echo "preStop:" > /data/log.txt
                ping -W 1 -c 5 10.5.32.1 2>&1 > /data/log.txt
        volumeMounts:
        - name: datadir
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          # upstream recommended max is 700M
          storage: 1Gi
```
当用kubectl delete pod test-prestop-3执行删除pod时，勺子中的ping操作是正常的，网络正常。
当用kubectcl scale sts test-prestop --replicas=3执行缩容，从而也会触发pod test-prestop-3删除，preStop勾子也会执行，但此时ping操作失败，网络是不通的。
（其它CNI没有这个问题）

# Actual Behavior
在对statefulset缩容时，被删除的Pod触发的preStop勾子中要保持网络可用。
# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version:
  
  ```
1.10.6
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
NAME="CentOS Stream"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Stream 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_SUPPORT_PRODUCT_VERSION="CentOS Stream"

5.4.210-1.el8.elrepo.x86_64
  ```

怀疑是由于kubeovn对statefulset作了特殊处理，在缩容时未等pod删除就先删除了网络。
