### ISSUE TITLE
Incorrect IP statistics in subnet status after subnet expansion

### ISSUE THREAD

**Issue by zhangzujian** [kubeovn/kube-ovn#1975]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

1. Create a subnet with CIDR 10.21.0.0/30;
2. Create a deployment with 2 replication;
3. A pod within the deployment is running and the other is stuck on NoAvailableAddress;
4. Change the subnet CIDR to 10.21.0.0/29;
5. Both the Pods are running;
6. There is a chance that the IP statistics in the subnet status are incorrect.

```yaml
  v4availableIPs: 4  # should be 3
  v4usingIPs: 1      # should be 2
  v6availableIPs: 0
  v6usingIPs: 0
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```
