### ISSUE TITLE
VPC Peering function bug?

### ISSUE THREAD

**Issue by hugo345816** [kubeovn/kube-ovn#1981]
# Expected Behavior
通过vpc-peering实现VPC互通

# Actual Behavior
部分能通，部分不能通

# Steps to Reproduce the Problem
新建两个VPC网络，每个网络中各有两个子网，每个子网都有独立的VPC网关。
参考例子：https://kubeovn.github.io/docs/v1.10.x/en/advance/vpc-peering/ 实现两个VPC互通。
VPC与子网的定义如下。
```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: qa
  annotations:
    yealink.com/description: QA环境
spec:
  namespaces:
  - qa
  vpcPeerings:
    - remoteVpc: dev
      localConnectIP: 169.254.0.1/30
  staticRoutes:
  # 欧洲VM
  - cidr: 10.115.32.0/19
    nextHopIP: 10.115.32.2
    policy: policySrc

  # 欧洲POD
  - cidr: 10.116.64.0/18
    nextHopIP: 10.116.64.2
    policy: policySrc

  # ==以下是通往另一个VPC的==

  # 上海VM
  - cidr: 10.115.0.0/19
    nextHopIP: 169.254.0.2
    policy: policyDst

  # 上海POD
  - cidr: 10.116.0.0/18
    nextHopIP: 169.254.0.2
    policy: policyDst
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: qa
  annotations:
    yealink.com/description: QA环境
spec:
  namespaces:
  - qa
  vpcPeerings:
    - remoteVpc: dev
      localConnectIP: 169.254.0.1/30
  staticRoutes:
  # 欧洲VM
  - cidr: 10.115.32.0/19
    nextHopIP: 10.115.32.2
    policy: policySrc

  # 欧洲POD
  - cidr: 10.116.64.0/18
    nextHopIP: 10.116.64.2
    policy: policySrc

  # ==以下是通往另一个VPC的==

  # 上海VM
  - cidr: 10.115.0.0/19
    nextHopIP: 169.254.0.2
    policy: policyDst

  # 上海POD
  - cidr: 10.116.0.0/18
    nextHopIP: 169.254.0.2
    policy: policyDst
---
# 欧洲区 - L1 虚拟机网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: qa-europe-vm
  annotations:
    yealink.com/description: QA环境-欧洲区-虚拟机子网
    ovn.kubernetes.io/multicast: "true"
  labels:
    topology.kubernetes.io/region: qa
    topology.kubernetes.io/zone: europe
spec:
  vpc: qa
  protocol: IPv4
  cidrBlock: 10.115.32.0/19       # 10.115.32.1 ~ 10.115.63.255
  excludeIps:
  - 10.115.32.1..10.115.39.255    # 其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址 
  # 10.115.40.0..10.115.47.255    # 可动态分配给一级POD/VM的IP
  - 10.115.48.0..10.115.63.255    # 保留作为L2 Service LoadBalancer EIP
---
# 欧洲区 - L2 POD网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: qa-europe-pod
  annotations:
    yealink.com/description: QA环境-欧洲区-容器子网
  labels:
    topology.kubernetes.io/region: qa
    topology.kubernetes.io/zone: europe
spec:
  vpc: qa
  protocol: IPv4
  cidrBlock: 10.116.64.0/18         # 10.116.64.1 ~ 10.116.127.255
  excludeIps:
  - 10.116.64.1..10.116.79.255      # 其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址 
  # 10.116.80.0..10.116.127.255     # 可动态分配给一级POD/VM或二级IPVLAN POD使用

---
# 上海区 - L1 虚拟机网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: dev-shanghai-vm
  annotations:
    yealink.com/description: 开发环境-上海区-虚拟机子网
    ovn.kubernetes.io/multicast: "true"
  labels:
    topology.kubernetes.io/region: dev
    topology.kubernetes.io/zone: shanghai
spec:
  vpc: dev
  protocol: IPv4
  cidrBlock: 10.115.0.0/19        # 10.115.0.1 ~ 10.115.31.255
  excludeIps:
  - 10.115.0.1..10.115.7.255      # 其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址
  # 10.115.8.0..10.115.15.255     # 可动态分配给一级POD/VM的IP
  - 10.115.16.0..10.115.31.255    # 保留作为L2 Service LoadBalancer EIP
---
# 上海区 - L2 POD网络
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: dev-shanghai-pod
  annotations:
    yealink.com/description: 开发环境-上海区-容器子网
  labels:
    topology.kubernetes.io/region: dev
    topology.kubernetes.io/zone: shanghai
spec:
  vpc: dev
  protocol: IPv4
  cidrBlock: 10.116.0.0/18        # 10.116.0.1 ~ 10.116.63.255
  excludeIps:
  - 10.116.0.1..10.116.15.255      # 其中'1'为默认网关地址，'2'为VPC网关地址，其它的保留作为静态分配的地址
  # 10.116.16.0..10.116.63.255     # 可动态分配给一级POD/VM或二级IPVLAN POD使用

---

# 显示指定使用【qa-europe-vm】子网
apiVersion: v1
kind: Pod
metadata:
  namespace: qa
  name: europe-vm
  annotations:
    # 指定使用【qa-europe-vm】子网
    ovn.kubernetes.io/logical_switch: qa-europe-vm
spec:
  containers:
  - name: busybox
    image: cr.yealink.top/system/busybox:latest

---

# 指定使用【qa-europe-pod】子网
apiVersion: v1
kind: Pod
metadata:
  namespace: qa
  name: europe-pod
  annotations:
    # 指定使用【qa-europe-pod】子网
    ovn.kubernetes.io/logical_switch: qa-europe-pod
spec:
  containers:
  - name: busybox
    image: cr.yealink.top/system/busybox:latest
---
# 显示指定使用【dev-shanghai-vm】子网
apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: shanghai-vm
  annotations:
    # 指定使用【dev-shanghai-vm】子网
    ovn.kubernetes.io/logical_switch: dev-shanghai-vm
spec:
  containers:
  - name: busybox
    image: cr.yealink.top/system/busybox:latest

---

# 指定使用【dev-shanghai-pod】子网
apiVersion: v1
kind: Pod
metadata:
  namespace: dev
  name: shanghai-pod
  annotations:
    # 指定使用【dev-shanghai-pod】子网
    ovn.kubernetes.io/logical_switch: dev-shanghai-pod
spec:
  containers:
  - name: busybox
    image: cr.yealink.top/system/busybox:latest
```
在每个子网都创建一个pod，然后做互ping测试，结果如下：
europe-vm -> shanghai-vm        (kubectl -n qa exec -it europe-vm -- ping -w1 -c1 10.115.8.0)
europe-vm -> shanghai-pod       (kubectl -n qa exec -it europe-vm -- ping -w1 -c1 10.116.16.0)
europe-pod x shanghai-vm        (kubectl -n qa exec -it europe-pod -- ping -w1 -c1 10.115.8.0)
europe-pod -> shanghai-pod      (kubectl -n qa exec -it europe-pod -- ping -w1 -c1 0.116.16.0)

shanghai-vm -> europe-vm        (kubectl -n dev exec -it shanghai-vm -- ping -w1 -c1 10.115.40.0)
shanghai-vm x europe-pod        (kubectl -n dev exec -it shanghai-vm -- ping -w1 -c1 10.116.80.0)
shanghai-pod x europe-vm        (kubectl -n dev exec -it shanghai-pod -- ping -w1 -c1 10.115.40.0)
shanghai-pod -> europe-pod      (kubectl -n dev exec -it shanghai-pod -- ping -w1 -c1 10.116.80.0)

说明：
europe-vm、  shanghai-vm、europe-pod、 shanghai-pod为4个pod，分别在不同的subnet中。
 -> 表示能ping通
 x 表示无法ping通
（）内表示测试命令

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:24:41Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version:
  
  ```
1.10.0
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
"CentOS Stream 8"
5.4.205-1.el8.elrepo.x86_64
  ```

补充：如果暂时不考虑VPC网络出口流量问题，即在vpc定义中去掉两条policySrc的静态路由，由没此问题。但这样的话VPC网络就无法与外部通讯了。
