### ISSUE TITLE
Can I put kube-ovn into other namespace instead of kube-system?

### ISSUE THREAD

**Issue by NoahLovesLife** [kubeovn/kube-ovn#1997]
pinger crashed when I use other namespace instead of kube-system!
![coredns](https://user-images.githubusercontent.com/84314029/198561563-84b10aa2-ba02-4c29-95b0-661bf810c4a8.png)

**Comment by zhangzujian** [comment]
Please try to add the following parameter to the daemonset:

```txt
--ds-namespace=kube-ovn-ns
```

**Comment by NoahLovesLife** [comment]
I've already modified the namespace, but still crashed.
![image](https://user-images.githubusercontent.com/84314029/199154994-90f402a4-be90-4b0b-9ff4-7ebe3efb0df9.png)
![image](https://user-images.githubusercontent.com/84314029/199154798-aa08cce4-1946-4e62-baa6-a129db7c9fe2.png)
![image](https://user-images.githubusercontent.com/84314029/199154911-e8d52166-814a-41e5-a573-9c82f7a8b718.png)
Did I do it right?

**Comment by NoahLovesLife** [comment]
I guess pinger and coredns need to be in the same namespace.
Never mind.

**Comment by NoahLovesLife** [comment]
OK, I just find the right place to add `--ds-namespace=kube-ovn-ns`. 
And problem solved! 🤣🤣
```
containers:
  - name: pinger
    image: "kubeovn/kube-ovn:v1.10.6"
    command:
    - /kube-ovn/kube-ovn-pinger
    args:
    - --external-address=114.114.114.114
    - --external-dns=alauda.cn
    - --logtostderr=false
    - --alsologtostderr=true
    - --log_file=/var/log/kube-ovn/kube-ovn-pinger.log
    - --log_file_max_size=0
    - --ds-namespace=kube-ovn-ns
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0
      privileged: false
```
