### ISSUE TITLE
Hybrid-dpdk with vxlan tunnel mode，The OVS node does not create a VXLAN tunnel to the OVS-DPDK node

### ISSUE THREAD

**Issue by lynn901** [kubeovn/kube-ovn#2037]
# Expected Behavior
In the ovs node, ovs-vsctl show the tunnel to the ovs-dpdk node 
![image](https://user-images.githubusercontent.com/11764870/201566843-cbef18d6-dc26-42cb-8316-8a50d07c5268.png)

# Actual Behavior
 ovs does not have  the tunnel port to the ovs-dpdk node 
# Steps to Reproduce the Problem

1. intall ovs with hybird-dpdk
2. ovs-vsctl show in ovs node

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
clientVersion:
  buildDate: "2021-10-19T08:30:59Z"
  compiler: gc
  gitCommit: 83c85a6e50757c6bbb81c6ceaac60234c1161817
  gitTreeState: clean
  gitVersion: v1.21.5-eki.0
  goVersion: go1.16.8
  major: "1"
  minor: 21+
  platform: linux/amd64
serverVersion:
  buildDate: "2021-10-19T08:28:00Z"
  compiler: gc
  gitCommit: 83c85a6e50757c6bbb81c6ceaac60234c1161817
  gitTreeState: clean
  gitVersion: v1.21.5-eki.0
  goVersion: go1.16.8
  major: "1"
  minor: 21+
  platform: linux/amd64

  ```

- kube-ovn version:
  
  ```
  v1.10.6
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  BigCloud Enterprise Linux For Euler release 21.10 (LTS-SP2)
 4.19.90-2107.6.0.0100.oe1.bclinux.x86_64
  ```
