### ISSUE TITLE
VPC子网通过NAT Gateway访问内外网 ，Connection refused 

### ISSUE THREAD

**Issue by WaterAndBread** [kubeovn/kube-ovn#2097]
1. 环境说明 ：  k8s 1.22.9   主网卡地址段：  192.168.211.*   可以正常访问外网  ； 网卡名br211 ; 测试namespace:  sukai263
实验配置如下：
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "br211",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }' 

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-nat-gw-config
  namespace: kube-system
data:
  image: 'dockerhub.kubekey.local/vpc-nat-gateway:v1.10.7'
  enable-vpc-nat-gw: 'true'
  nic: br211

---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: mail263
spec:
  namespaces:
  - sukai263
  staticRoutes:
    - cidr: 0.0.0.0/0
      nextHopIP: 10.0.1.1
      policy: policyDst
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: vmservers
spec:
  vpc: mail263
  cidrBlock: 10.0.1.0/24
  gateway: 10.0.1.1
  protocol: IPv4
  namespaces:
    - sukai263
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 192.168.211.0/24
  gateway: 192.168.211.222
  excludeIps:
  - 192.168.211.1..192.168.211.100
----
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: natgw
spec:
  vpc: mail263
  subnet: vmservers
  lanIp: 10.0.1.1
  selector:
    - "kubernetes.io/os: linux"

---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: eips01
spec:
  natGwDp: natgw 
  v4ip: 192.168.211.169   # specify ip in macvlan public subnet

---
kind: IptablesSnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: snat01
spec:
  eip: eips01                      # eip name
  internalCIDR: 10.0.1.0/24     # vpc subnet cidr
---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: eipd01
spec:
  natGwDp: natgw
  v4ip: 192.168.211.170
---
kind: IptablesDnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: dnat01
spec:
  eip: eipd01               # eip name
  externalPort: '8888'
  internalIp: 10.0.1.2
  internalPort: '80'
  protocol: tcp
---
apiVersion: v1
kind: Pod
metadata:
  name: vpc-nginx-1
  namespace: sukai263
  annotations:
    ovn.kubernetes.io/ip_address: 10.0.1.2
spec:
  containers:
  - name: vpc-nginx
    image: dockerhub.kubekey.local/nginx:latest

问题截图：
网关 iptables 截图
![image](https://user-images.githubusercontent.com/27998792/204774231-2c2b9b6c-95c9-46f1-b36d-785b3746341c.png)
 网关内部网络截图
![image](https://user-images.githubusercontent.com/27998792/204774406-7b56b6e5-c6c0-4174-a105-afa41a64648e.png)

访问connection refused 报错截图
![image](https://user-images.githubusercontent.com/27998792/204774758-3788111e-9f67-49ea-aaca-f542b38b94e2.png)

在网关上抓包截图
<img width="956" alt="337b333c2344c56a3e6d00895d66bfb" src="https://user-images.githubusercontent.com/27998792/204775634-aed2fe14-56f1-4b23-b992-72925b1f0d6b.png">

本实验参考：https://zhuanlan.zhihu.com/p/524433989  根据实验结果，应当可以正常通过gateway 进行内外网访问。

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`: 1.22.9

- kube-ovn version:
  
  ```
  1.10.7
  ```

- operation-system/kernel version:
  
 /etc/os-release`: CentOS Linux 7 (Core)
uname -r`:   5.6.15-1.el7.elrepo.x86_64

**Comment by bobz965** [comment]
lanIp 不能和vpc 子网网关ip一致，子网网关默认都是.1,

**Comment by WaterAndBread** [comment]
> lanIp 不能和vpc 子网网关ip一致，子网网关默认都是.1,

![image](https://user-images.githubusercontent.com/27998792/204811925-c4587eb5-e6ee-4577-b5c4-44a3b2f762bc.png)
 修改了lanip 还是不行

**Comment by QtSYnT** [comment]
I'm seeing the exact same issue with v1.11.0, RHEL 8.6 4.18.0-372.9.1.el8.x86_64.

Looks like the nat prerouting rule simply isn't being reached as the counter never increases. Traffic makes it into the nat gateway pod and dies.


```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 10.67.0.0/16
  gateway: 10.67.0.1 
  excludeIps:
  - 10.67.200.0..10.67.200.255
  - 10.67.150.150
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "br0",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-nat-gw-config
  namespace: kube-system
data:
  image: 'kubeovn/vpc-nat-gateway:v1.11.0' 
  enable-vpc-nat-gw: 'true'
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-1
spec:
  namespaces:
  - kube-system
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net1
spec:
  vpc: test-vpc-1
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  namespaces:
    - kube-system
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw1
spec:
  vpc: test-vpc-1
  subnet: net1
  lanIp: 10.0.1.254
  selector:
    - "kubernetes.io/os: linux"
---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: eipf01
spec:
  natGwDp: gw1
---
kind: IptablesFIPRule
apiVersion: kubeovn.io/v1
metadata:
  name: fip01
spec:
  eip: eipf01
  internalIp: 10.0.1.5
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: net1
    ovn.kubernetes.io/ip_address: 10.0.1.5
  name: vpc1-pod
spec:
  containers:
    - name: vpc1-pod
      image: nginx:latest
```
