### ISSUE TITLE
vm删除后12分钟内创建同名vm，node到vm网络不通。

### ISSUE THREAD

**Issue by syang1997** [kubeovn/kube-ovn#2162]
# Expected Behavior
vm删除后12分钟内创建同名vm，node到vm网络不通。vm使用容器网络，子网选择ovn-default。
# Actual Behavior

# Steps to Reproduce the Problem
```yaml
piVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  name: vm
  namespace: default
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: pvcdisk-1
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            model: virtio
            name: eth0
        machine:
          type: q35
        resources:
          requests:
            cpu: "1"
            memory: 2Gi
      networks:
      - name: eth0
        pod: {}
      volumes:
      - dataVolume:
          name: restore
        name: pvcdisk-1
      - cloudInitConfigDrive:
          userData: |
            #cloud-config
            ssh_pwauth: true
            disable_root: false
            groups:
              - admingroup: [root,sys]
            users:
              - name: root
                gecos: Foo B. Bar
                sudo: ALL=(ALL) NOPASSWD:ALL
                groups: root
                expiredate: '2032-09-01'
                lock_passwd: false
                plain_text_passwd: 123456
        name: cloudinitdisk
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.7", GitCommit:"42c05a547468804b2053ecf60a3bd15560362fc2", GitTreeState:"clean", BuildDate:"2022-05-24T12:30:55Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}


  ```

- kube-ovn version:
  
  ```
v1.11.0
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
CentOS Stream 8 5.4.223-1.el8.elrepo.x86_64
  ```
