### ISSUE TITLE
kube-ovn-controller reports error: named port http has already be defined with portID 8083

### ISSUE THREAD

**Issue by zhangzujian** [kubeovn/kube-ovn#2326]
# Expected Behavior

# Actual Behavior

# Steps to Reproduce the Problem

Create two pods with the same port name:

```yaml
    ports:
    - containerPort: 9080
      name: http
      protocol: TCP
```

```yaml
    ports:
    - containerPort: 8083
      name: http
      protocol: TCP
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- kube-ovn version:
  
  ```
  (paste your output here)
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```
