### ISSUE TITLE
v1.11.1 deploy vpc-dns fail

### ISSUE THREAD

**Issue by lizsGH** [kubeovn/kube-ovn#2412]
> I try the vpc-dns according to the official tutorial [VPC DNS](https://kubeovn.github.io/docs/v1.11.x/advance/vpc-dns/), but the status of pod `vpc-dns-external-dns-6d58db7555-hmlmq` is `Pending`

# Steps to Reproduce the Problem
**uname -a**
``` bash
Linux lizs-pc 4.15.0-204-generic #215-Ubuntu SMP Fri Jan 20 18:24:59 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
**kube-ovn version**
```bash
-------------------------------
Kube-OVN Version:     v1.11.1
Default Network Mode: geneve
Default Subnet CIDR:  10.16.0.0/16
Join Subnet CIDR:     100.64.0.0/16
Enable SVC LB:        true
Enable Networkpolicy: true
Enable EIP and SNAT:  true
Enable Mirror:        false
-------------------------------
```
**kubectl get node**
```bash
NAME          STATUS   ROLES                  AGE    VERSION
kube-master   Ready    control-plane,master   112m   v1.23.16
```
**kubectl get vpc**
``` bash
NAME          ENABLEEXTERNAL   STANDBY   SUBNETS                         NAMESPACES
external      false            true      ["external-gw","external-01"]   ["external"]
ovn-cluster   false            true      ["join","ovn-default"]
```
**kubectl get subnet**
> After apply `vpc-dns.yaml`
``` bash
NAME                       PROVIDER                               VPC           PROTOCOL   CIDR              PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS                         U2OINTERCONNECTIONIP
external-01                ovn                                    external      IPv4       10.0.1.0/24       false     true    false     distributed   1        252           0        0             ["10.0.1.1"]                       
external-gw                ovn                                    external      IPv4       10.254.254.0/24   false     true    false     distributed   3        250           0        0             ["10.254.254.1"]                   
join                       ovn                                    ovn-cluster   IPv4       100.64.0.0/16     false     false   false     distributed   1        65532         0        0             ["100.64.0.1"]                     
ovn-default                ovn-nad.default.ovn                    ovn-cluster   IPv4       10.16.0.0/16      false     true    true      distributed   11       65522         0        0             ["10.16.0.1"]                      
ovn-vpc-external-network   ovn-vpc-external-network.kube-system   ovn-cluster   IPv4       192.168.22.0/24   false     true    false     distributed   3        151           0        0             ["192.168.22.1..192.168.22.100"]   
```

**vpc-dns.yaml**
> I fully copy the configuration of the tutorial [VPC DNS](https://kubeovn.github.io/docs/v1.11.x/advance/vpc-dns/)
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:vpc-dns
rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    - services
    - pods
    - namespaces
    verbs:
    - list
    - watch
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs:
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: vpc-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:vpc-dns
subjects:
- kind: ServiceAccount
  name: vpc-dns
  namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vpc-dns
  namespace: kube-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vpc-dns-corefile
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        prometheus :9153
        forward . /etc/resolv.conf {
          prefer_udp
        }
        cache 30
        loop
        reload
        loadbalance
    }
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-nad
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "ovn-nad.default.ovn"
    }'
# cniVersion: get cniVersion from /etc/cni/net.d/00-multus.conf
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-default
spec:
  cidrBlock: 10.16.0.0/16
  default: true
  disableGatewayCheck: false
  disableInterConnection: false
  enableDHCP: false
  enableIPv6RA: false
  excludeIps:
  - 10.16.0.1
  gateway: 10.16.0.1
  gatewayType: distributed
  logicalGateway: false
  natOutgoing: true
  private: false
  protocol: IPv4
  # provider: ovn
  provider: ovn-nad.default.ovn
  vpc: ovn-cluster
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vpc-dns-config
  namespace: kube-system
data:
  coredns-vip: 10.96.0.3
  enable-vpc-dns: "true"
  nad-name: ovn-nad
  nad-provider: ovn-nad.default.ovn
```
**kubectl apply -f vpc-dns.yaml**
```bash
clusterrole.rbac.authorization.k8s.io/system:vpc-dns created
clusterrolebinding.rbac.authorization.k8s.io/vpc-dns created
serviceaccount/vpc-dns created
configmap/vpc-dns-corefile created
networkattachmentdefinition.k8s.cni.cncf.io/ovn-nad created
Warning: resource subnets/ovn-default is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
subnet.kubeovn.io/ovn-default configured
configmap/vpc-dns-config created
```
**dns-external-gw.yaml**
```yaml
kind: VpcDns
apiVersion: kubeovn.io/v1
metadata:
  name: external-dns
spec:
  vpc: external
  subnet: external-gw
```

**kubectl apply -f dns-external-gw.yaml && kubectl get all --all-namespaces**
```bash
kube-system   pod/vpc-dns-external-dns-6d58db7555-hmlmq   0/1     Pending   0          23m
kube-system   pod/vpc-dns-external-dns-6d58db7555-lcmnk   1/1     Running   0          23m
kube-system   deployment.apps/vpc-dns-external-dns   1/2     2            1           23m
```
_**<font color="#dd0000">The pod `vpc-dns-external-dns-6d58db7555-hmlmq` is not running!</font>**_

**kubectl describe pod/vpc-dns-external-dns-6d58db7555-hmlmq -n kube-system**
``` bash
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  2m45s (x51 over 53m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules.
```
**kubectl get pod/vpc-dns-external-dns-6d58db7555-hmlmq -n kube-system -o json**
``` bash
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "annotations": {
            "k8s.v1.cni.cncf.io/networks": "default/ovn-nad",
            "ovn-nad.default.ovn.kubernetes.io/allocated": "true",
            "ovn-nad.default.ovn.kubernetes.io/cidr": "10.16.0.0/16",
            "ovn-nad.default.ovn.kubernetes.io/gateway": "10.16.0.1",
            "ovn-nad.default.ovn.kubernetes.io/ip_address": "10.16.0.18",
            "ovn-nad.default.ovn.kubernetes.io/logical_router": "ovn-cluster",
            "ovn-nad.default.ovn.kubernetes.io/logical_switch": "ovn-default",
            "ovn-nad.default.ovn.kubernetes.io/mac_address": "00:00:00:9F:FB:A6",
            "ovn-nad.default.ovn.kubernetes.io/pod_nic_type": "veth-pair",
            "ovn.kubernetes.io/allocated": "true",
            "ovn.kubernetes.io/cidr": "10.254.254.0/24",
            "ovn.kubernetes.io/gateway": "10.254.254.1",
            "ovn.kubernetes.io/ip_address": "10.254.254.5",
            "ovn.kubernetes.io/logical_router": "external",
            "ovn.kubernetes.io/logical_switch": "external-gw",
            "ovn.kubernetes.io/mac_address": "00:00:00:89:5F:A4",
            "ovn.kubernetes.io/pod_nic_type": "veth-pair"
        },
        "creationTimestamp": "2023-03-01T19:18:25Z",
        "generateName": "vpc-dns-external-dns-6d58db7555-",
        "labels": {
            "k8s-app": "vpc-dns-external-dns",
            "pod-template-hash": "6d58db7555"
        },
        "name": "vpc-dns-external-dns-6d58db7555-hmlmq",
        "namespace": "kube-system",
        "ownerReferences": [
            {
                "apiVersion": "apps/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "ReplicaSet",
                "name": "vpc-dns-external-dns-6d58db7555",
                "uid": "8984e9ed-a4c7-4699-834c-882f9b41b7f7"
            }
        ],
        "resourceVersion": "5676",
        "uid": "8220d80e-5e7f-4541-b287-4c8da1a6651e"
    },
    "spec": {
        "affinity": {
            "podAntiAffinity": {
                "requiredDuringSchedulingIgnoredDuringExecution": [
                    {
                        "labelSelector": {
                            "matchExpressions": [
                                {
                                    "key": "k8s-app",
                                    "operator": "In",
                                    "values": [
                                        "vpc-dns-external-dns"
                                    ]
                                }
                            ]
                        },
                        "topologyKey": "kubernetes.io/hostname"
                    }
                ]
            }
        },
        "containers": [
            {
                "args": [
                    "-conf",
                    "/etc/coredns/Corefile"
                ],
                "image": "registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.8.6",
                "imagePullPolicy": "IfNotPresent",
                "name": "coredns",
                "ports": [
                    {
                        "containerPort": 53,
                        "name": "dns",
                        "protocol": "UDP"
                    },
                    {
                        "containerPort": 53,
                        "name": "dns-tcp",
                        "protocol": "TCP"
                    },
                    {
                        "containerPort": 9153,
                        "name": "metrics",
                        "protocol": "TCP"
                    }
                ],
                "resources": {
                    "limits": {
                        "memory": "170Mi"
                    },
                    "requests": {
                        "cpu": "100m",
                        "memory": "70Mi"
                    }
                },
                "securityContext": {
                    "allowPrivilegeEscalation": false,
                    "capabilities": {
                        "add": [
                            "NET_BIND_SERVICE"
                        ],
                        "drop": [
                            "all"
                        ]
                    },
                    "readOnlyRootFilesystem": true
                },
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/etc/coredns",
                        "name": "config-volume",
                        "readOnly": true
                    },
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-f8srv",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "Default",
        "enableServiceLinks": true,
        "initContainers": [
            {
                "command": [
                    "sh",
                    "-c",
                    "ip route add ${KUBERNETES_SERVICE_HOST} via 10.16.0.1 dev net1;ip route add 114.114.114.114 via 10.16.0.1 dev net1;ip route add 8.8.8.8 via 10.16.0.1 dev net1;"
                ],
                "image": "kubeovn/vpc-nat-gateway:v1.11.0",
                "imagePullPolicy": "IfNotPresent",
                "name": "init-route",
                "resources": {},
                "securityContext": {
                    "allowPrivilegeEscalation": true,
                    "privileged": true
                },
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "kube-api-access-f8srv",
                        "readOnly": true
                    }
                ]
            }
        ],
        "nodeSelector": {
            "kubernetes.io/os": "linux"
        },
        "preemptionPolicy": "PreemptLowerPriority",
        "priority": 2000000000,
        "priorityClassName": "system-cluster-critical",
        "restartPolicy": "Always",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "vpc-dns",
        "serviceAccountName": "vpc-dns",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "key": "CriticalAddonsOnly",
                "operator": "Exists"
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "configMap": {
                    "defaultMode": 420,
                    "items": [
                        {
                            "key": "Corefile",
                            "path": "Corefile"
                        }
                    ],
                    "name": "vpc-dns-corefile"
                },
                "name": "config-volume"
            },
            {
                "name": "kube-api-access-f8srv",
                "projected": {
                    "defaultMode": 420,
                    "sources": [
                        {
                            "serviceAccountToken": {
                                "expirationSeconds": 3607,
                                "path": "token"
                            }
                        },
                        {
                            "configMap": {
                                "items": [
                                    {
                                        "key": "ca.crt",
                                        "path": "ca.crt"
                                    }
                                ],
                                "name": "kube-root-ca.crt"
                            }
                        },
                        {
                            "downwardAPI": {
                                "items": [
                                    {
                                        "fieldRef": {
                                            "apiVersion": "v1",
                                            "fieldPath": "metadata.namespace"
                                        },
                                        "path": "namespace"
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2023-03-01T19:18:25Z",
                "message": "0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules.",
                "reason": "Unschedulable",
                "status": "False",
                "type": "PodScheduled"
            }
        ],
        "phase": "Pending",
        "qosClass": "Burstable"
    }
}
```
**kubectl logs -f pod/kube-ovn-controller-ccf4b8855-ts7b5 -n kube-system**
``` bash
I0302 03:18:25.379125       7 switch_lb_rule.go:48] enqueue add SwitchLBRule vpc-dns-external-dns
I0302 03:18:25.403695       7 pod.go:288] handle add pod kube-system/vpc-dns-external-dns-6d58db7555-lcmnk
I0302 03:18:25.425824       7 ipam.go:51] allocate v4 10.16.0.17 v6  mac 00:00:00:FC:C4:FB for kube-system/vpc-dns-external-dns-6d58db7555-lcmnk from subnet ovn-default
I0302 03:18:25.435101       7 endpoint.go:94] update endpoint kube-system/slr-vpc-dns-external-dns
I0302 03:18:25.449279       7 service.go:269] update svc kube-system/slr-vpc-dns-external-dns
I0302 03:18:25.450847       7 pod.go:288] handle add pod kube-system/vpc-dns-external-dns-6d58db7555-hmlmq
I0302 03:18:25.463898       7 ipam.go:51] allocate v4 10.16.0.18 v6  mac 00:00:00:9F:FB:A6 for kube-system/vpc-dns-external-dns-6d58db7555-hmlmq from subnet ovn-default
I0302 03:18:25.468623       7 ipam.go:51] allocate v4 10.254.254.4 v6  mac 00:00:00:B9:0E:BB for kube-system/vpc-dns-external-dns-6d58db7555-lcmnk from subnet external-gw
I0302 03:18:25.494045       7 service.go:340] add vip 10.96.0.3:53 to tcp lb cluster-tcp-session-loadbalancer
I0302 03:18:25.506210       7 ipam.go:51] allocate v4 10.254.254.5 v6  mac 00:00:00:89:5F:A4 for kube-system/vpc-dns-external-dns-6d58db7555-hmlmq from subnet external-gw
I0302 03:18:25.520389       7 service.go:367] exist udp vips are map[10.96.0.10:53:10.16.0.5:53,10.16.0.6:53]
I0302 03:18:25.520665       7 endpoint.go:94] update endpoint kube-system/slr-vpc-dns-external-dns
I0302 03:18:25.532565       7 service.go:374] add vip 10.96.0.3:53 to udp lb cluster-udp-session-loadbalancer
I0302 03:18:25.542432       7 pod.go:294] take 138 ms to handle add pod kube-system/vpc-dns-external-dns-6d58db7555-lcmnk
I0302 03:18:25.549762       7 pod.go:358] handle update pod kube-system/vpc-dns-external-dns-6d58db7555-lcmnk
I0302 03:18:25.550680       7 pod.go:775] update pod kube-system/vpc-dns-external-dns-6d58db7555-lcmnk
I0302 03:18:25.561252       7 endpoint.go:94] update endpoint kube-system/slr-vpc-dns-external-dns
I0302 03:18:25.574792       7 pod.go:294] take 123 ms to handle add pod kube-system/vpc-dns-external-dns-6d58db7555-hmlmq
I0302 03:18:25.608535       7 pod.go:365] take 58 ms to handle update pod kube-system/vpc-dns-external-dns-6d58db7555-lcmnk
I0302 03:18:27.740334       7 endpoint.go:94] update endpoint kube-system/slr-vpc-dns-external-dns
I0302 03:18:27.959357       7 pod.go:323] handle delete pod kube-system/vpc-dns-external-dns-6d58db7555-zsvzq
I0302 03:18:27.962019       7 node.go:699] delete cr ip 'vpc-dns-external-dns-6d58db7555-zsvzq.kube-system.ovn-nad.default.ovn' for pod kube-system/vpc-dns-external-dns-6d58db7555-zsvzq
I0302 03:18:27.964133       7 node.go:699] delete cr ip 'vpc-dns-external-dns-6d58db7555-zsvzq.kube-system' for pod kube-system/vpc-dns-external-dns-6d58db7555-zsvzq
I0302 03:18:27.965825       7 pod.go:330] take 6 ms to handle delete pod kube-system/vpc-dns-external-dns-6d58db7555-zsvzq
I0302 03:18:28.738369       7 endpoint.go:94] update endpoint kube-system/slr-vpc-dns-external-dns
I0302 03:18:28.751202       7 service.go:269] update svc kube-system/slr-vpc-dns-external-dns
I0302 03:18:28.789727       7 service.go:340] add vip 10.96.0.3:53 to tcp lb vpc-external-tcp-sess-load
I0302 03:18:28.789857       7 endpoint.go:94] update endpoint kube-system/slr-vpc-dns-external-dns
I0302 03:18:28.795688       7 service.go:367] exist udp vips are map[10.96.0.3:53:10.254.254.4:53]
I0302 03:18:34.065533       7 pod.go:323] handle delete pod kube-system/vpc-dns-external-dns-6d58db7555-zsvzq
I0302 03:18:34.104911       7 node.go:699] delete cr ip 'vpc-dns-external-dns-6d58db7555-zsvzq.kube-system.ovn-nad.default.ovn' for pod kube-system/vpc-dns-external-dns-6d58db7555-zsvzq
I0302 03:18:34.107998       7 node.go:699] delete cr ip 'vpc-dns-external-dns-6d58db7555-zsvzq.kube-system' for pod kube-system/vpc-dns-external-dns-6d58db7555-zsvzq
I0302 03:18:34.110164       7 pod.go:330] take 44 ms to handle delete pod kube-system/vpc-dns-external-dns-6d58db7555-zsvzq

```
**kubectl get vpc-dns**
```bash
NAME           ACTIVE   VPC        SUBNET
external-dns   true     external   external-gw
```
**kubectl get slr**
```bash
NAME                   VIP         PORT(S)                  SERVICE                                AGE
vpc-dns-external-dns   10.96.0.3   53/UDP,53/TCP,9153/TCP   kube-system/slr-vpc-dns-external-dns   69m
```
