### ISSUE TITLE
创建SwitchLBRule资源对象，VIP访问不通

### ISSUE THREAD

**Issue by 66545shiwo** [kubeovn/kube-ovn#2635]
# Expected Behavior
希望使用SwitchLBRule对象的VIP负载均衡访问后端Pod（例如：Deployment）

# Actual Behavior
SwitchLBRule创建成功后，子网内部ping不通VIP，代理的pod端口也不通

# Steps to Reproduce the Problem
0. 创建VPC
```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-1
spec:
  namespaces:
    - ovn1
  staticRoutes:
    - cidr: 0.0.0.0/0
      nextHopIP: 10.0.1.254 #nat gateway ip
      policy: policyDst

```

1.创建net1子网
```
[root@k8s1 ovntest]# kubectl get subnet
NAME                       PROVIDER                               VPC           PROTOCOL   CIDR             PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS                                      U2OINTERCONNECTIONIP
join                       ovn                                    ovn-cluster   IPv4       100.64.0.0/16    false     false   false     distributed   3        65530         0        0             ["100.64.0.1"]                                  
net1                       ovn                                    test-vpc-1    IPv4       10.0.1.0/24      false     false   false     distributed   4        249           0        0             ["10.0.1.1"]                                    
net2                       ovn                                    test-vpc-2    IPv4       10.0.1.0/24      false     false   false     distributed   2        251           0        0             ["10.0.1.1"]                                    
ovn-default                ovn                                    ovn-cluster   IPv4       192.168.0.0/20   false     true    true      distributed   168      3925          0        0             ["192.168.0.1"]                                 
ovn-vpc-external-network   ovn-vpc-external-network.kube-system   ovn-cluster   IPv4       172.16.72.0/24   false     false   false     distributed   1        242           0        0             ["172.16.72.1..172.16.72.10","172.16.72.254"]   

```
2.在net1子网创建nginx deployment
```
[root@k8s1 ovntest]# cat nginx-vpc1.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-vpc1
  namespace: ovn1
  labels:
    app: nginx-vpc1
  annotations:
    ovn.kubernetes.io/logical_switch: net1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-vpc1
  template:
    metadata:
      labels:
        app: nginx-vpc1
      annotations:
        ovn.kubernetes.io/logical_switch: net1
    spec:
      containers:
      - name: backend
        image: hadoop01:28081/library/nginx:alpine

[root@k8s1 ovntest]# kubectl get po -n ovn1 -owide 
NAME                         READY   STATUS    RESTARTS   AGE     IP         NODE             NOMINATED NODE   READINESS GATES
nginx-vpc1-f678bc47f-rgjxt   1/1     Running   0          4h52m   10.0.1.3   k8s3.dev.local   <none>           <none>
nginx-vpc1-f678bc47f-xrnqq   1/1     Running   0          4h52m   10.0.1.2   k8s1.dev.local   <none>           <none>

```
3. 在net1子网中创建VIP资源对象
```
[root@k8s1 ovntest]# cat vip.yaml 
apiVersion: kubeovn.io/v1
kind: Vip
metadata:
  name: vip-nginx-vpc1
spec:
  subnet: net1

[root@k8s1 ovntest]# kubectl get vip 
NAME             V4IP       PV4IP   MAC                 PMAC   V6IP   PV6IP   SUBNET   READY
vip-nginx-vpc1   10.0.1.4           00:00:00:58:A0:4E                         net1     true

```
5. 根据VIP创建SwitchLBRule资源对象
```
[root@k8s1 ovntest]# cat switchlbrule.yaml 
apiVersion: kubeovn.io/v1
kind: SwitchLBRule
metadata:
  name:  cjh-slr-nginx
spec:
  vip: 10.0.1.4
  sessionAffinity: ClientIP
  namespace: ovn1
  selector:
    - app:nginx-vpc1
  ports:
  - name: nginx
    port: 8888
    targetPort: 80
    protocol: TCP

[root@k8s1 ovntest]# kubectl get slr
NAME            VIP        PORT(S)    SERVICE                  AGE
cjh-slr-nginx   10.0.1.4   8888/TCP   ovn1/slr-cjh-slr-nginx   46m

```
7. 查看lb rule
```
[root@k8s1 ovntest]# kubectl ko nbctl lb-list | grep 10.0.1.4
49c36c6f-5338-4083-a8ae-46c4e21efb3f    vpc-test-vpc-1-t    tcp        10.0.1.4:8888         10.0.1.2:80,10.0.1.3:80
```
8. 测试在net1子网中的nginx pod里访问vip，ping不通，代理端口同样不通
```
[root@k8s1 ovntest]# kubectl exec -it -n ovn1 nginx-vpc1-f678bc47f-rgjxt sh 
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
219: eth0@if220: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1400 qdisc noqueue state UP 
    link/ether 00:00:00:38:f7:1e brd ff:ff:ff:ff:ff:ff
    inet 10.0.1.3/24 brd 10.0.1.255 scope global eth0
       valid_lft forever preferred_lft forever
/ # curl 10.0.1.3
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
/ # curl 10.0.1.2
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
html { color-scheme: light dark; }
body { width: 35em; margin: 0 auto;
font-family: Tahoma, Verdana, Arial, sans-serif; }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
/ # curl 10.0.1.4:8888
curl: (7) Failed to connect to 10.0.1.4 port 8888 after 3107 ms: Host is unreachable
/ # ping  10.0.1.4 
PING 10.0.1.4 (10.0.1.4): 56 data bytes
^C
--- 10.0.1.4 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss

```
 

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
v1.20.12
  ```

- kube-ovn version:
  
  ```
 1.11.3
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  4.19.12-1.el7.elrepo.x86_64
  ```
