### ISSUE TITLE
Is there a way to set the pod IP of VPC NAT gateway?

### ISSUE THREAD

**Issue by lizsGH** [kubeovn/kube-ovn#2691]
### Feature request

I create a VPC and the VPC NAT gateway. I want to set the IP (net1) of VPC NAT gateway pod.

**kubectl get vpc**
```bash
NAME          ENABLEEXTERNAL   STANDBY   SUBNETS                         NAMESPACES
external      false            true      ["external-01","external-gw"]   ["external"]
```
**kubectl get vpc-nat-gw**
```bash
NAME          VPC        SUBNET        LANIP
external-gw   external   external-gw   10.254.254.254
```
**kubectl get pod -A**
```bash
NAMESPACE     NAME                                    READY   STATUS    RESTARTS       AGE
kube-system   vpc-nat-gw-external-gw-0                1/1     Running   2 (2d6h ago)   5d2h
```
**kubectl get ips**
```bash
NAME                                                                        V4IP             V6IP   MAC                 NODE          SUBNET
vpc-nat-gw-external-gw-0.kube-system                                        10.254.254.254          00:00:00:B1:AF:89   kube-master   external-gw
vpc-nat-gw-external-gw-0.kube-system.ovn-vpc-external-network.kube-system   192.168.22.101          00:00:00:08:FA:8C   kube-master   ovn-vpc-external-network
```
**nat-gw.yaml**
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-nat-gw-config
  namespace: kube-system
data:
  image: 'kubeovn/vpc-nat-gateway:v1.11.3' 
  enable-vpc-nat-gw: 'true'
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: external-gw
spec:
  vpc: external
  subnet: external-gw
  lanIp: 10.254.254.254
  selector:
    - "kubernetes.io/hostname: kube-master"
    - "kubernetes.io/os: linux"
```
I didn't find a way to set the IP of VPC NAT pod in `ConfigMap` and `VpcNatGateway`. Is there a way to set the pod IP of VPC NAT gateway.

### Use case

I have a special VPC, and there are some vm in the VPC. Now I want the physical machines(e.g. 192.168.22.100) that out of VPC to access the vm via their IP(e.g. 10.0.1.1) directly. So I add static routing rules to the router.

- source ip/netmask: 10.0.0.0/8 (the subnet VLAN of the VPC)
- gateway: 192.168.22.101  (vpc-nat-gw-external-gw-0.kube-system.ovn-vpc-external-network.kube-system)

Now, I can access the the vm in the VPC via their IP.

The only trouble now is that the pod IP of VPC NAT gateway will change when I recreate it. In this way, I have to modify the gateway of the static route.
