### ISSUE TITLE
自定义vpc无法通过vpc网关上网

### ISSUE THREAD

**Issue by Learntotolearn** [kubeovn/kube-ovn#2710]
# Expected Behavior
```
自定义vpc的pod通过vpc网关可以访问互联网。
```
# Actual Behavior
>1、自定义vpc的pod中可以ping通vpc网关pod中的IP （10.0.1.254、192.168.100.31）,但ping不通外网
![image](https://user-images.githubusercontent.com/85656971/234217642-819dcebf-c2aa-4244-abac-704009b807d5.png)
![image](https://user-images.githubusercontent.com/85656971/234218621-9d65b37a-1f43-41c7-848c-73b71a2634eb.png)

>2、vpc网关pod中无法ping通192.168.100.1(该IP为可以宿主机网络的网关)
![image](https://user-images.githubusercontent.com/85656971/234218386-4544cffc-7a3c-4c15-a5dd-23fb2578fc54.png)

# Steps to Reproduce the Problem

1.创建自定义vpc和vpc网段
```
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-1
spec:
  namespaces:
  - ns1
  staticRoutes:
   - cidr: 0.0.0.0/0
     nextHopIP: 10.0.1.254
     policy: policyDst
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-2
spec:
  namespaces:
  - ns2
 ---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net1
spec:
  vpc: test-vpc-1
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  gateway: 10.0.1.254
  namespaces:
    - ns1
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net2
spec:
  vpc: test-vpc-2
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  namespaces:
    - ns2
```
2.创建外部网络
```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 192.168.100.0/24
  gateway: 192.168.100.1  # IP address of the physical gateway
  excludeIps:
  - 192.168.100.1..192.168.100.29
  - 192.168.100.32..192.168.100.254   #排除的ip范围
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens192",  #宿主机网卡
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }'

```
3.开启网关功能和创建vpc网关
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-nat-gw-config
  namespace: kube-system
data:
  image: 'kubeovn/vpc-nat-gateway:v1.11.1' 
  enable-vpc-nat-gw: 'true'
  nic: ens192
---
apiVersion: kubeovn.io/v1
metadata:
  name: gw1
spec:
  vpc: test-vpc-1
  subnet: net1
  lanIp: 10.0.1.254
  selector:
    - "kubernetes.io/os: linux"
```
4.配置snat
```
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: eips01
  namespace: ns1
spec:
  natGwDp: gw1
  v4ip: 192.168.100.31
---
kind: IptablesSnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: snat01
  namespace: ns1
spec:
  eip: eips01
  internalCIDR: 10.0.1.0/24
```
5.创建pod
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: net1
  namespace: ns1
  name: vpc1-pod
spec:
  containers:
    - name: vpc1-pod
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: net2
    #  namespace: ns2
  name: vpc2-pod
spec:
  containers:
    - name: vpc2-pod
      image: nginx:alpine
```

# Additional Info

- Kubernetes version:

```
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.26.0
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
```

- kube-ovn version:
  
```
v1.11.3
```

- operation-system/kernel version:
 
```
Ubuntu 20.04.1 LTS
5.4.0-147-generic
```

- 实验环境
>VMware ESXI 虚拟机创建的k8s集群   
>虚拟机上网网段为：192.168.100.0/24
