### ISSUE TITLE
使用 VF 进行网络卸载加速的 Pod 未成功

### ISSUE THREAD

**Issue by Longchuanzheng** [kubeovn/kube-ovn#2727]
# Expected Behavior
根据文档 https://kubeovn.github.io/docs/v1.10.x/advance/offload-mellanox/#vf-pod 创建Pod 后，通过在 Pod 运行节点的 ovs-ovn 容器中运行下面的命令观察卸载
```
ovs-appctl dpctl/dump-flows -m type=offloaded
```
有相关内容
![image](https://user-images.githubusercontent.com/49519342/234776324-3d4d3865-0edc-4357-a439-9ed7930b3377.png)

# Actual Behavior
通过如下 yaml 创建Pod 后
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    v1.multus-cni.io/default-network: default/default
spec:
  containers:
  - name: nginx
    image: registry.eki/zhuanlan/nginx:alpine
    resources:
      requests:
        mellanox.com/cx5_sriov_switchdev: '1'
      limits:
        mellanox.com/cx5_sriov_switchdev: '1'
```
Pod running，但是ovs 中未体现，但是Pod使用的确实是VF
![image](https://user-images.githubusercontent.com/49519342/234776962-4ac3310c-3dfa-4597-bb57-9b7f699cd2ce.png)

###  验证Pod使用的是VF
根据 pod 的 容器 Container ID 找到 Pid，进入该容器的 namespace，cha查看相应网卡信息
![image](https://user-images.githubusercontent.com/49519342/234778450-4bb5312a-043a-4b77-85ac-f3a512ce4f03.png)
pci号是属于某个VF的
![image](https://user-images.githubusercontent.com/49519342/234779547-d1c43162-1634-4d38-a520-360881043521.png)
### 其他环境信息
![image](https://user-images.githubusercontent.com/49519342/234779832-5c6d9b31-9d95-41e0-abca-a5885f445b7d.png)
![image](https://user-images.githubusercontent.com/49519342/234780007-32cc40e4-d414-4ce2-a7c6-f5fc42c2a677.png)

# Steps to Reproduce the Problem

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

```
 v1.21.5
```

- kube-ovn version:
  
```
1.11.1
```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
```
centos 7
3.10.0-957.el7.x86_64
```
