### ISSUE TITLE
Allow other_config: vlan-passthru="true" to handle vlan traffic from pods. 

### ISSUE THREAD

**Issue by fizzers123** [kubeovn/kube-ovn#2737]
### Feature request

We want to run routers in Kubernetes as part of our bachelor thesis. To allow routers to communicate over different VLANs, the `other_config: vlan-passthru="true"` must be set on the subnet (virtual_switch). It would be very helpful if this option could be set from the yaml manifest of the subnet directly. 

### Use case

As a router, I want to send dot1q encapsulated VLAN traffic through Kube-OVN.

### Example
This setting can be manually enabled using the command below. 

`kubectl ko nbctl add logical_switch subnet1 other_config vlan-passthru=true`

After it has been applied to subnet1, it can be seen under other_config. when listing the configuration.

```
# kubectl ko nbctl list logical_switch subnet1
_uuid               : 51f7f761-5f45-439b-8d35-8ef56925cb84
acls                : []
copp                : []
dns_records         : []
external_ids        : {vendor=kube-ovn}
forwarding_groups   : []
load_balancer       : [b5a5a90a-75ca-449d-84b8-36266e28fa0e, c02fbfb1-3699-4753-b2d6-636227b9d1d2, ddafbdeb-c9be-462f-9f8c-34d234986349, f01d248b-3056-4770-a5b9-979fad28e420]
load_balancer_group : []
name                : subnet1
other_config        : {vlan-passthru="true"}
ports               : [1c6f2b86-d474-4092-abf8-44af5de1d10f, 37a1c304-a71e-46b2-9866-1187b7956452, c7a26797-4071-4f6b-9e4a-f804860e85be]
qos_rules           : []
```

Suggestion for manifest:

```
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: subnet1
spec:
  vpc: lab1-vpc
  provider: net1.default.ovn
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  other_config:
    vlan-passthru: true
```
