### ISSUE TITLE
 VpcNatGateway in version "v1" cannot be handled as a VpcNatGateway

### ISSUE THREAD

**Issue by willzhang** [kubeovn/kube-ovn#2740]
# Expected Behavior
create VpcNatGateway success
# Actual Behavior
create VpcNatGateway failed
# Steps to Reproduce the Problem

https://kubeovn.github.io/docs/v1.11.x/guide/vpc/#vpc_4
```
root@ubuntu:~/vpc# cat VpcNatGateway.yaml 
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw1
spec:
  vpc: test-vpc-1
  subnet: net1
  lanIp: 10.0.1.254
  selector:
    - "kubernetes.io/hostname: ubuntu"
    - "kubernetes.io/os: linux"
  staticRoutes:
    - cidr: 0.0.0.0/0
      nextHopIP: 10.0.1.254
      policy: policyDst
```

```
root@ubuntu:~/vpc# kubectl apply -f VpcNatGateway.yaml 
Error from server (BadRequest): error when creating "VpcNatGateway.yaml": VpcNatGateway in version "v1" cannot be handled as a VpcNatGateway: strict decoding error: unknown field "spec.staticRoutes"
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
v1.25.8
  ```

- kube-ovn version:
  
  ```
v1.11.1
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
ubuntu 22.04
  ```
