### ISSUE TITLE
Custom VPC cannot access service cluster ip

### ISSUE THREAD

**Issue by willzhang** [kubeovn/kube-ovn#2787]
# Expected Behavior

Custom VPC can access service cluster ip

# Actual Behavior

Custom VPC can ping service  cluster ip but can not access service cluster ip.

# Steps to Reproduce the Problem

1. create nginx pod with 3 replicas and service in Custom VPC
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ns1
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: registry.cn-shenzhen.aliyuncs.com/cnregistry/nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ns1
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
```

2. get  pods and service

```
root@node34:~/vpc# kubectl -n ns1 get pods -o wide
NAME                                READY   STATUS    RESTARTS   AGE     IP          NODE     NOMINATED NODE   READINESS GATES
nginx-deployment-5ff77d69bd-44qqp   1/1     Running   0          3m38s   10.0.1.9    node34   <none>           <none>
nginx-deployment-5ff77d69bd-b9swz   1/1     Running   0          3m38s   10.0.1.10   node34   <none>           <none>
nginx-deployment-5ff77d69bd-t7tqz   1/1     Running   0          3m38s   10.0.1.8    node34   <none>           <none>
vpc1-pod                            1/1     Running   0          49m     10.0.1.1    node34   <none>           <none>
root@node34:~/vpc# kubectl -n ns1 get svc
NAME            TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)   AGE
nginx-service   ClusterIP   10.96.0.175   <none>        80/TCP    3m42s
root@node34:~/vpc# 
```

3. ping cluster-ip from k8s node success
```
root@node34:~/vpc# ping 10.96.0.175 -c 4
PING 10.96.0.175 (10.96.0.175) 56(84) bytes of data.
64 bytes from 10.96.0.175: icmp_seq=1 ttl=64 time=0.075 ms
64 bytes from 10.96.0.175: icmp_seq=2 ttl=64 time=0.070 ms
64 bytes from 10.96.0.175: icmp_seq=3 ttl=64 time=0.048 ms
64 bytes from 10.96.0.175: icmp_seq=4 ttl=64 time=0.039 ms

--- 10.96.0.175 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3077ms
rtt min/avg/max/mdev = 0.039/0.058/0.075/0.014 ms
```
4. curl cluster-ip failed
```
root@node34:~/vpc# curl 10.96.0.175


^C
root@node34:~/vpc# ^C

```

is it mean cluster-ip、serivice-name、node-port and loadbalancer defaults are not available in custom vpc, if not use vpc-dns ?

 

# Additional Info

- Kubernetes version: v1.25.6

- kube-ovn version: v1.11.3
  
- operation-system/kernel version: ubuntu 22.04
