### ISSUE TITLE
u2oInterconnection breaks communication between pods when using hostport 

### ISSUE THREAD

**Issue by patriziobassi** [kubeovn/kube-ovn#2807]
# Expected Behavior

We have ngnix ingress controller cluster-wide deployed as container using hostPorts (and so using the workers' control plane IP address)

```
    ports:
    - containerPort: 80
      hostPort: 80
      name: http
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      name: https
      protocol: TCP

```
those workers should reach underlay network in order to expose HTTP/HTTPs services using Service object and a HTTP backend similar to this:

```
# cat 01-pod.yml
kind: Pod
apiVersion: v1
metadata:
  name: apple-app
  labels:
    app: apple
  annotations:
    ovn.kubernetes.io/logical_switch: subnet1-vpc

spec:
  containers:
    - name: apple-app
      image: hashicorp/hashicorp/http-echo
      args:
        - "-text=apple"

---

kind: Service
apiVersion: v1
metadata:
  name: apple-service
spec:
  selector:
    app: apple
  ports:
    - port: 5678 # Default port for image

```

We are using a subnet definition for underlay network like this:

```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet1-vpc
spec:
  cidrBlock: 10.0.0.0/24
  gateway: 10.0.0.1
  vlan: provvlan1
  protocol: IPv4
  excludeIps:
  - 10.0.0.1
  - 10.0.0.2..10.0.0.15
  - 10.0.0.32..10.0.0.255
  private: false
  gatewayType: distributed
  natOutgoing: false
  disableGatewayCheck: true
  u2oInterconnection: true

```

# Actual Behavior

We see nginx ingress to expose the service but when a client tries to connect it times out because the backend is unreachable, while we should get the traffic to the backend pod.

Changing 
` u2oInterconnection: false` solves this internal communication issue but of course breaks the underlay pod to Services communication

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-15T02:14:53Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.1", GitCommit:"4c9411232e10168d7b050c49a1b59f6df9d7ea4b", GitTreeState:"clean", BuildDate:"2023-04-15T02:05:42Z", GoVersion:"go1.20.3", Compiler:"gc", Platform:"linux/amd64"}
  ```

- kube-ovn version: 1.11.5

- operation-system/kernel version: "Ubuntu 22.04.2 LTS"

**Comment by patriziobassi** [comment]
Hi,
i can add more info: the problem is not specific to hostports of course but the reachablility of the underlay pod network from the control plane network.

Infact we first spot the problem when we had nginx deployed with hostport, so the load balancer could not reach the backend endpoints.

Today we tested metalLB in order to expose Services to external (non-k8s) clients: because of the routing the requests from the clients will go to the default gw and then from the control plane network should got to the pod network but they don't.
if we disable the u2o interconnection flag this works and pods can receive the forwarded traffic.

This is a show stopper for non http applications which need an external reachable ip.

we'll be happy to test a fix or a workaround
Thank you

**Comment by changluyi** [comment]
I can't reproduce your bug, in my kind env, you can provide more detailed information like below

env: 
1. kube-ovn: v1.11.5
2. kernel 3.10.0-1160.83.1.el7.x86_64

steps:
1. create kind cluster
```
make kind-init && make kind-install-underlay
```

2. install metallb
```
kubectl create namespace metallb-system
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.12.1/manifests/metallb.yaml
```

3. config external ippool
```configmap.yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.18.0.100-172.18.0.104

```
4. deployment and service
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - name: http
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  #loadBalancerIP: 172.18.0.100
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
```

5. enable ovn-default u2oInterconection

result:
 # kubectl get svc
NAME         TYPE           CLUSTER-IP      EXTERNAL-IP    PORT(S)        AGE
kubernetes   ClusterIP      10.96.0.1       <none>         443/TCP        51m
nginx        LoadBalancer   10.101.21.162   172.18.0.100   80:32601/TCP   67s

I can access 172.18.0.100: 80 successfully from external
