### ISSUE TITLE
创建port和targetPort不一样的loadbalacner service时，外部访问不了服务

### ISSUE THREAD

**Issue by qsliao** [kubeovn/kube-ovn#2835]
# Expected Behavior
```
从集群外访问http://<lb ip>:8080成功
```
# Actual Behavior
```
从集群外访问http://<lb ip>:8080失败，原因是lb svc pod里面配置iptables nat规则错误，如下图所示，nat后的端口号应该是8080，而不是80端口
```
![image](https://github.com/kubeovn/kube-ovn/assets/28948877/92759154-b756-4af2-8898-e5484e0bec7c)

![image](https://github.com/kubeovn/kube-ovn/assets/28948877/df9f273b-9f65-4777-8dc3-308710f96416)

# Steps to Reproduce the Problem
```
1. 创建一个loadbalacner service，指定port:为8080，targetPort为80
2.  创建nginx后端
3. 从集群外访问http://<lb ip>:8080
```
# Additional Info

# Kubernetes version: 
  ```
1.27.1
  ```

# kube-ovn version:
  ```
1.11.x
  ```

# operation-system/kernel version: 

```
Ubuntu 18.04.5 LTS"
```  

# Output of `uname -r`:
  ```
4.15.0-112-generic
  ```

svc yaml:
  ```
apiVersion: v1
kind: Service
metadata:
  annotations:
    lb-svc-attachment.kube-system.kubernetes.io/logical_switch: attach-subnet  #可选
    ovn.kubernetes.io/attachmentprovider: lb-svc-attachment.kube-system           #必须
  labels:
    app: dynamic
  name: test-service
  namespace: default
spec:
  loadBalancerIP: 192.168.61.239  #可选，不为空时，最终将该参数赋值给service external-ip字段。不指定的情况下，该参数为随机分配值
  ports:
    - name: test
      protocol: TCP
      port: 8080
      targetPort: 80
  selector:
    app: dynamic
  sessionAffinity: None
  type: LoadBalancer
  ```
