### ISSUE TITLE
Access via External IP Blocked when NetworkPolicy Applied 

### ISSUE THREAD

**Issue by ikandars** [kubeovn/kube-ovn#3078]
I have a pod that has an eip. I'm able to access the pod form public internet. Then I apply a networkPolicy object to the namespace where the pod belongs to. And then I'm not able to access the pod. Heres my networkPolicy manifest:

```yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-allowed
  namespace: my-namespace
spec:
  podSelector: {}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network-access: allowed
```

Adding label network-access: allowed  in namespace kube-system  didn't help.
Any suggestion?

**Comment by oilbeater** [comment]
> And then I'm not able to access the pod. 

In which direction you cannot access the pod, from the outside of the cluster or from the pod in other namespaces?

**Comment by ikandars** [comment]
from the outside

**Comment by oilbeater** [comment]
You need add the src ips to the networkpolicy like this:
```bash
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
```

**Comment by ikandars** [comment]
in this case, I need to make sure all pods in `my-namespace` should only use `172.17.1.0/24` subnet right?

**Comment by ikandars** [comment]
Testing with this rule:

```yaml
  ingress:
    - from:
        - ipBlock:
            cidr: 172.17.0.0/16
            except:
              - 172.17.1.0/24
```

But still not expected.

My expected result: block from other namespace expect certain namespace by it label. And allow from all from external IP
What actual result at the moment base on that rule: both other namespace and external IP inbound blocked

My current setup:

Version: v1.11.8
Installation method:  Helm

**Comment by ikandars** [comment]
I managed to solve this issue by integrating with Cilium. I followed this docs https://kubeovn.github.io/docs/v1.11.x/en/advance/with-cilium/ but instead of using helm chart version `1.11.6` I use latest version of Cilium Helm chart:

```bash
helm install cilium cilium/cilium --version 1.14.0 \
    --namespace kube-system \
    --set cni.chainingMode=generic-veth \
    --set cni.customConf=true \
    --set cni.configMap=cni-configuration \
    --set tunnel=disabled \
    --set enableIPv4Masquerade=false \
    --set enableIdentityMark=false
```

and to achieve the policy, I apply this rules:

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "isolate-ns"
  namespace: my-namespace
spec:
  endpointSelector:
    matchLabels:
      {}
  ingress:
  - fromEndpoints:
    - matchLabels:
        k8s:io.kubernetes.pod.namespace: allowed-ns
  - fromEntities:
      - world
      - host
      - remote-node
```
