### ISSUE TITLE
使用原生ovn-eip，ovnfip，snat，无法ping通外网

### ISSUE THREAD

**Issue by zhoulw** [kubeovn/kube-ovn#3082]
环境：

三台机器，每台机器上都是两张网卡：enp3s0f0，enp3s0f1，enp3s0f0 vlan id是12，enp3s0f1 vlan id是31.

我拿enp3s0f1这张网卡作为公网的网卡，然后根据OVN EIP FIP SNAT 文档的配置去做实验。发现ping不通ovn-eip，ovn-fip。

provider-network：
```
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: external31
spec:
  defaultInterface: enp3s0f1
---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan31
spec:
  id: 31
  provider: external31
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: external31
spec:
  protocol: IPv4
  cidrBlock: 10.120.31.0/24
  gateway: 10.120.31.254
  vlan: vlan31
  excludeIps:
  - 10.120.31.1..10.120.31.10
  - 10.120.31.101..10.120.31.254
```

默认VPC：
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  external-gw-nodes: "hci-ctl-1,hci-compute-1,hci-compute-2"
  type: "centralized" 
  external-gw-nic: "enp3s0f1"
  external-gw-addr: "10.120.31.254/24"
```

自定义VPC：
```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc1-subnet1
spec:
  cidrBlock: 10.111.111.0/24
  default: false
  disableGatewayCheck: false
  disableInterConnection: true
  enableEcmp: true
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: vpc1
  namespaces:
  - vpc1
  ```

router:
```
outer 1157ad9e-7115-494c-960f-d5b17c50af3d (vpc1)
    port vpc1-external31
        mac: "00:00:00:CE:1D:D5"
        networks: ["10.120.31.12/24"]
        gateway chassis: [5da25fe4-2edf-4471-a498-7975e4c123a0 73778e46-23b6-4523-9d45-129994bb21a1 37ed0714-91a0-456e-bbd6-a42010d36f37]
    port vpc1-vpc1-subnet1
        mac: "00:00:00:5B:3B:E0"
        networks: ["10.111.111.1/24"]
    nat dd7e810c-89b3-4b1c-98d2-fe63434f57be
        external ip: "10.120.31.13"
        logical ip: "10.111.111.2"
        type: "dnat_and_snat"
```

为pod分配ofip，但是ping 不通oeip：
```
[root@hci-ctl-1 ovn-eip]# kubectl get ofip
NAME         VPC    V4EIP          V4IP           READY   IPTYPE   IPNAME
eip-static   vpc1   10.120.31.13   10.111.111.2   true             test-ovn-eip-fip-pod.vpc1
[root@hci-ctl-1 ovn-eip]# get ofip eip-static^C
[root@hci-ctl-1 ovn-eip]# kubectl get ofip eip-static
NAME         VPC    V4EIP          V4IP           READY   IPTYPE   IPNAME
eip-static   vpc1   10.120.31.13   10.111.111.2   true             test-ovn-eip-fip-pod.vpc1

[root@hci-ctl-1 ovn-eip]# ping 10.120.31.13
PING 10.120.31.13 (10.120.31.13) 56(84) bytes of data.
From 10.120.31.101 icmp_seq=1 Destination Host Unreachable
```

主机路由：

```
[root@hci-ctl-1 ovn-eip]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.120.12.254   0.0.0.0         UG    100    0        0 enp3s0f0
0.0.0.0         10.120.31.254   0.0.0.0         UG    101    0        0 br-external31
10.16.0.0       100.64.0.1      255.255.0.0     UG    0      0        0 ovn0
10.66.0.0       100.64.0.1      255.255.0.0     UG    0      0        0 ovn0
10.120.12.0     0.0.0.0         255.255.255.0   U     100    0        0 enp3s0f0
10.120.31.0     0.0.0.0         255.255.255.0   U     101    0        0 br-external31
100.64.0.0      0.0.0.0         255.255.0.0     U     0      0        0 ovn0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      100.64.0.1      255.255.0.0     UG    0      0        0 ovn0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
```

网桥：
```
Bridge "br-external31"
        Port "enp3s0f1"
            Interface "enp3s0f1"
        Port "br-external31"
            Interface "br-external31"
                type: internal
        Port "patch-localnet.external31-to-br-int"
            Interface "patch-localnet.external31-to-br-int"
                type: patch
                options: {peer="patch-br-int-to-localnet.external31"}
    ovs_version: "3.1.3"
    
```
对应配置：

```
[root@hci-ctl-1 ~]# kubectl get po -n kube-system kube-ovn-controller-544dd44b97-w9r2t -oyaml|grep external
    - --external-gateway-vlanid=31
    - --external-gateway-switch=external31
    
    
    root@hci-ctl-1 ~]# kubectl get po -n kube-system kube-ovn-cni-8qh8n -oyaml|grep external
    - --external-gateway-switch=external31
```

### 出现的问题：
按照以上的配置，无法使用ovn-eip，ovn-fip，snat等功能。

目前的解决的方法是 将provider network管理的公网subnet， vlanid 分别设置为”external“， ”0“，如以下配置：
```
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: external
spec:
  defaultInterface: enp3s0f1
---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: underlay
spec:
  id: 0
  provider: external
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: external
spec:
  protocol: IPv4
  cidrBlock: 10.120.31.0/24
  gateway: 10.120.31.254
  vlan: underlay
  excludeIps:
  - 10.120.31.1..10.120.31.10
  - 10.120.31.101..10.120.31.254
 ```

并且不设置kube-ovn-controller以及kube-ovn-cni中对应的”external-gateway-vlanid=“   ”- --external-gateway-switch=“ 等启动项，

可以发现 ovn-eip&&ovn-fip是可以使用的，但是无法使用 vip，snat， dnat等功能，如下：

```
[root@hci-ctl-1 test-snat]# ping 10.120.31.13
PING 10.120.31.13 (10.120.31.13) 56(84) bytes of data.
64 bytes from 10.120.31.13: icmp_seq=1 ttl=63 time=5.60 ms
64 bytes from 10.120.31.13: icmp_seq=2 ttl=63 time=3.26 ms
64 bytes from 10.120.31.13: icmp_seq=3 ttl=63 time=0.366 ms


```

容器内抓包：
```

[root@hci-compute-1 .kube]# nsenter -t 22448 -n tcpdump -i eth0 -nvee icmp
tcpdump: listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
11:52:35.400758 00:00:00:77:b2:09 > 00:00:00:b7:32:06, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 63, id 38513, offset 0, flags [DF], proto ICMP (1), length 84)
10.120.31.101 > 10.111.112.2: ICMP echo request, id 46050, seq 1, length 64
11:52:35.400799 00:00:00:b7:32:06 > 00:00:00:77:b2:09, ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 41395, offset 0, flags [none], proto ICMP (1), length 84)
10.111.112.2 > 10.120.31.101: ICMP echo reply, id 46050, seq 1, length 64

```

```
[root@hci-ctl-1 ovn-eip]# kubectl ko nbctl show vpc1
router e4f7f4e1-6c59-43d0-989d-ea3423b23b1e (vpc1)
    port vpc1-vpc1-subnet1
        mac: "00:00:00:77:B2:09"
        networks: ["10.111.112.1/24"]
    port vpc1-external
        mac: "00:00:00:80:5F:F0"
        networks: ["10.120.31.12/24"]
        gateway chassis: [73778e46-23b6-4523-9d45-129994bb21a1 5da25fe4-2edf-4471-a498-7975e4c123a0 37ed0714-91a0-456e-bbd6-a42010d36f37]
    nat b52ba774-51bb-46d5-b030-440f1472d7de
        external ip: "10.120.31.14"
        logical ip: "10.111.112.3"
        type: "dnat_and_snat"
    nat c4e14f46-93d4-4097-b617-364efb430edd
        external ip: "10.120.31.13"
        logical ip: "10.111.112.2"
        type: "dnat_and_snat"
   nat d43cf941-f52a-4876-8fd7-31ad15ec72a7
        external ip: "10.120.31.16"
        logical ip: "10.111.112.0/24"
        type: "snat"
```
