### ISSUE TITLE
v1.11.8 seems to be not working with kubevirt vms

### ISSUE THREAD

**Issue by zlangi** [kubeovn/kube-ovn#3087]
Hello kube-ovn team. We have found a problem in the kube-ovn version 1.11.8. When one tries to create a pod it works well, but when one creates a vm provided by kubevirt, it doesn't work. The problem is not there with the latest dev branch. (1.12.x)

# Expected Behavior
The expected behaviour is to have the vm on kubevirt connected to the kube-ovn.

# Actual Behavior
The actual behaviour is this:
```
Warning  FailedCreatePodSandBox  28m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "ea7d199627fa9ef9834e0e733c3af864c94b8bac2292aa76099be7fa2425d8fd": plugin type="multus" name="multus-cni-network" failed (add): [default/virt-launcher-vm-cirros-m7ffn:kube-ovn]: error adding container to network "kube-ovn": RPC failed; Post "http://dummy/api/v1/add": EOF
```
# Steps to Reproduce the Problem

1. install a kubernetes cluster with kind, 4 nodes. 3 worker 1 master
2. install multus
3. change the default multus network name to kindnet
4. install kube-ovn
```
curl -O https://raw.githubusercontent.com/kubeovn/kube-ovn/release-1.11/dist/images/install.sh
export CNI_CONFIG_PRIORITY=20
export ENABLE_KEEP_VM_IP=true
bash install.sh
```
5. create a network
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: kube-ovn
  namespace: default
spec:
  config: |
    {
        "name":"kube-ovn",
        "cniVersion":"0.3.1",
        "plugins":[
            {
                "type":"kube-ovn",
                "server_socket":"/run/openvswitch/kube-ovn-daemon.sock"
            },
            {
                "type":"portmap",
                "capabilities":{
                    "portMappings":true
                }
            }
        ]
    }
```
6. install kubevirt
```
export RELEASE=$(curl https://storage.googleapis.com/kubevirt-prow/release/kubevirt/kubevirt/stable.txt)
kubectl apply -f "https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml"
kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml
```
7. create a vm
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-cirros
  name: vm-cirros
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-cirros
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: overcloud_network
            bridge: {}
        resources:
          requests:
            memory: 128Mi
      networks:
      - name: overcloud_network
        multus:
          networkName: default/kube-ovn
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo:v1.0.0
        name: containerdisk
      - cloudInitNoCloud:
          userData: |
            #!/bin/sh

            echo 'printed from cloud-init userdata'
        name: cloudinitdisk
```
The problem will appear immediately.

# Additional Info
Here is the output of a kube-ovn pod when the problem happens:
https://pastebin.com/TZytBgWn
- Kubernetes version:
v1.27.3
  **Output of kubectl version:**

  ```
  Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-15T00:36:28Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.27) exceeds the supported minor version skew of +/-1

  ```

- kube-ovn version:
  
```
v1.11.8
```

- operation-system/kernel version:
  
```
ubuntu 20.04
 ```
