### ISSUE TITLE
OVN SNAT 失效

### ISSUE THREAD

**Issue by zcq98** [kubeovn/kube-ovn#3165]
# Expected Behavior

绑定snat规则后，内部subnet下的pod能ping通external subnet的网关

# Actual Behavior

配置snat后没有实现源地址转换，导致无法ping通外部网络

# Steps to Reproduce the Problem

1.创建VPC

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: vpc1

---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: vpc1
spec:
  namespaces:
  - vpc1
  enableExternal: true
```

2.创建external subnet

> ens224为通过vmware创建的主机网络的网卡，网段为192.168.94.0/24，网关位于宿主机上为192.168.94.1

```yaml
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: external
spec:
  defaultInterface: ens224

---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan0
spec:
  id: 0
  provider: external

---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: external
spec:
  protocol: IPv4
  cidrBlock: 192.168.94.0/24
  gateway: 192.168.94.1
  vlan: vlan0
  excludeIps:
  - 192.168.94.2..192.168.94.127
```

3.创建subnet

> subnet网段为192.168.0.0/24

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc1-subnet1
spec:
  cidrBlock: 192.100.0.0/24
  default: false
  disableGatewayCheck: false
  disableInterConnection: true
  enableEcmp: true
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: vpc1
  namespaces:
  - vpc1
```

4.创建eip，snat和busybox

> snat绑定pod的方式，绑定vpc-1-busybox02

```yaml
apiVersion: kubeovn.io/v1
kind: OvnEip
metadata:
  name: snat-for-pod-vpc-ip
spec:
  externalSubnet: external
  type: nat

---
apiVersion: kubeovn.io/v1
kind: OvnSnatRule
metadata:
  name: snat01
spec:
  ovnEip: snat-for-pod-vpc-ip
  ipName: vpc-1-busybox02.vpc1
 
---
apiVersion: v1
kind: Pod
metadata:
  name: vpc-1-busybox02
  namespace: vpc1
spec:
  containers:
    - name: busybox-container
      image: busybox
      command: ["sleep", "3600"]
```

5.问题描述

```shell
$ kubectl get oeip
NAME                     V4IP             V6IP    MAC                 TYPE   NAT    READY
eip-static               192.168.94.129   <nil>   00:00:00:9E:76:EF   nat    fip    true
ovn-cluster-external     192.168.94.130           00:00:00:AD:E9:00   lrp           true
snat-for-pod-vpc-ip      192.168.94.131   <nil>   00:00:00:D3:61:6F   nat    snat   true
snat-for-subnet-in-vpc   192.168.94.132   <nil>   00:00:00:C9:7F:2B   nat    snat   true
vpc1-external            192.168.94.128   <nil>   00:00:00:03:2C:D5   lrp           true

$ kubectl get osnat
NAME                     VPC    V4EIP            V4IP             READY
snat01                   vpc1   192.168.94.131   192.100.0.3      true
```

**vpc-1-busybox02的ip为192.100.0.3，当vpc-1-busybox02 尝试 ping 192.168.94.1时，仅能抓取到**

**192.100.0.3 -> 192.168.94.1的数据包而没有192.168.94.131 -> 192.168.94.1的数据包，导致无法ping通。**

**fip规则下，则可以ping通**

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```shell
  v1.25.3
  ```

- kube-ovn version:
  
  ```
  v1.13.0
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  
  ```
  CentOS Stream 8 4.18.0-500.el8.x86_64
  ```
