### ISSUE TITLE
enabling u2ointerconnection breaks underlay networking

### ISSUE THREAD

**Issue by patriziobassi** [kubeovn/kube-ovn#3246]
# Expected Behavior

i would like to
a) create a custom vpc and associate a subnet, with underlay configuration
b) allow that underlay network to reach overlay network services in the ovn-default network and ovn-cluster default vpc such as coredns
c) allow underlay L2 connectivity (..of course)

# Actual Behavior

when u2o is enabled, ovn-default pods cannot be reached but even the L2 connectivity is gone.
disabling that flag allows at least the L2 traffic to flow (as the the used gateway is not the logical one)

# Steps to Reproduce the Problem

1) create provider network
```
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: provnet1
spec:
  defaultInterface: ens9

```
2) create vlan and vpc
```
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: provvlan1
spec:
  id: 0
  provider: provnet1

---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-1
spec:
  namespaces:
  - ns1

```

3) create underlay subnet
```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet1-vpc
spec:
  cidrBlock: 10.0.10.0/24
  gateway: 10.0.10.1
  vlan: provvlan1
  vpc: test-vpc-1
  protocol: IPv4
#  default: true
  namespaces:
   - ns1
  excludeIps:
  - 10.0.10.1
  - 10.0.10.2..10.0.10.15
  - 10.0.10.32..10.0.10.255
  private: false
  gatewayType: distributed
  natOutgoing: false
  disableGatewayCheck: true
  u2oInterconnection: true

```
# Additional Info

- Kubernetes version:

  ```
  1.28.2
  ```

- kube-ovn version:
  
  ```
  1.12.0
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  (paste your output here)
  ```
