### ISSUE TITLE
VPC update is always enqueued leading to huge number of updates when creating subnet

### ISSUE THREAD

**Issue by sirkrypt0** [kubeovn/kube-ovn#3301]
# Expected Behavior

When creating a subnet the VPC shouldn't be updated a large amount of times.

# Actual Behavior

Creating a subnet after a VPC already has two subnets leads to a huge amount of updates.

I assume that this has to do with the following line:

https://github.com/kubeovn/kube-ovn/blob/60ef1ad1f31d2974cb9462670b0ad26b1015be6f/pkg/controller/vpc.go#L47

Before #3107 this was (note the missing `!` in the line above):

https://github.com/kubeovn/kube-ovn/blob/68dc1c38023e4967e9644c89e72e63c605df8591/pkg/controller/vpc.go#L56

I'm unsure why the `!` should be removed here, as that leads to the `c.addOrUpdateVpcQueue.Add(key)` basically being called every time, which leads to a huge amount of (unnecessary) updates.

# Steps to Reproduce the Problem

1. Create a VPC

  ```yaml
  kind: Vpc
  apiVersion: kubeovn.io/v1
  metadata:
    name: test-vpc
  ```

2. Create a subnet and bind it to the VPC. Check the `kube-ovn-controller` logs. Shortly after you created the subnet the logs calm down again.

  ```yaml
  apiVersion: kubeovn.io/v1
  kind: Subnet
  metadata:
    name: subnet-138
  spec:
    cidrBlock: 10.129.138.0/24,fd50:52:129:138::0/64
    default: false
    disableGatewayCheck: true
    vpc: test-vpc
  ```

3. Create a second subnet and bind it to the VPC. Check the `kube-ovn-controller` logs. Shortly after you created the subnet the logs calm down again.

  ```yaml
  apiVersion: kubeovn.io/v1
  kind: Subnet
  metadata:
    name: subnet-139
  spec:
    cidrBlock: 10.129.139.0/24,fd50:52:129:139::0/64
    default: false
    disableGatewayCheck: true
    vpc: test-vpc
  ```

4. Create a third subnet and bind it to the VPC.

  ```yaml
  apiVersion: kubeovn.io/v1
  kind: Subnet
  metadata:
    name: subnet-140
  spec:
    cidrBlock: 10.129.140.0/24,fd50:52:129:140::0/64
    default: false
    disableGatewayCheck: true
    vpc: test-vpc
  ```

5. Now watch the log output of the `kube-ovn-controller`. Notice that it takes ~3 minutes (on my machines) until the logs stop.

Check the [kubeovn-bug-report.log](https://github.com/kubeovn/kube-ovn/files/12910539/kubeovn-bug-report.log) I attached.
I annotated where I started to create the subnets.
You should note that adding `subnet-140` leads to an absurd amount of log lines.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.28.2
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.28.2
  ```

- kube-ovn version:
  
  ```
  v1.12.1
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  Debian GNU/Linux 12 (bookworm)
  6.1.0-13-amd64
  ```
