### ISSUE TITLE
After shutting down a node, pods on other nodes cannot access the keepalived VIP.

### ISSUE THREAD

**Issue by Ghosgt** [kubeovn/kube-ovn#3304]
# Expected Behavior

After shutting down a node, pods on other nodes can access the keepalived VIP.

# Actual Behavior

I have three master nodes, the IP addresses are: 100.200.4.101, 100.200.4.102, 100.200.4.103. There is also a VIP created using keepalived: 100.200.4.111.

But when 100.200.4.102 is shut down, the pod on 100.200.4.103 cannot access VIP 100.200.4.111, but can access 100.200.4.101, and vice versa.

100.103.0.0/16 is the cidr of my ovn-default, 100.104.0.0/16 is the cidr of the join, and there is a route of 100.103.0.0/16 via 100.104.0.1 dev ovn0 on each node. 

I found that manually deleting this route from 100.200.4.102 will affect the pod on 103's access to VIP.

Another thing is that if you shut down the 100.200.4.101 node, the remaining 102 and 103 are normal, and you can access VIP without being affected; shutting down any node 102 or 103 will only affect the other party, and the pods on 101 will not be affected.

I don’t know where the problem is that affects 102 and 103. Can you provide some ideas?

# Steps to Reproduce the Problem

1.
1.
1.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  v1.25.4
  ```

- kube-ovn version:
  
  ```
  v1.11.8
  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  "Ubuntu 22.04.3 LTS"

  5.15.0-78-generic
  ```

**Comment by oilbeater** [comment]
Did you set the gatewayType to centralized and gatewayNodes to 100.200.4.102

**Comment by Ghosgt** [comment]
> Did you set the gatewayType to centralized and gatewayNodes to 100.200.4.102

The subnet is `ovn-default`, and the gatewayType is distributed.

```yaml
spec:
  cidrBlock: 100.103.0.0/16
  default: true
  excludeIps:
  - 100.103.0.1
  gateway: 100.103.0.1
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: true
  private: false
  protocol: IPv4
  provider: ovn
  vpc: ovn-cluster
```
