### ISSUE TITLE
Kubevirt VM 无法使用 Mellanox 网卡 Offload 功能

### ISSUE THREAD

**Issue by a180285** [kubeovn/kube-ovn#3564]
# Bug Report

## Expected Behavior

我看使用到 offload 网卡的 pod 的 k8s.v1.cni.cncf.io/network-status 为  "default/default",
```yaml
  annotations:
    default.default.ovn.kubernetes.io/allocated: 'true'
    default.default.ovn.kubernetes.io/cidr: 10.5.192.0/18
    default.default.ovn.kubernetes.io/gateway: 10.5.196.1
    default.default.ovn.kubernetes.io/ip_address: 10.5.192.127
    default.default.ovn.kubernetes.io/logical_router: ovn-cluster
    default.default.ovn.kubernetes.io/logical_switch: ovn-default
    default.default.ovn.kubernetes.io/mac_address: 00:00:00:E3:20:0B
    default.default.ovn.kubernetes.io/pod_nic_type: veth-pair
    default.default.ovn.kubernetes.io/routed: 'true'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "default/default",
          "interface": "eth0",
          "ips": [
              "10.5.192.127"
          ],
          "mac": "00:00:00:E3:20:0B",
          "default": true,
          "dns": {},
          "gateway": [
              "10.5.196.1"
          ]
      }]
    prometheus.io/port: '78'
    prometheus.io/scrape: 'true'
    v1.multus-cni.io/default-network: default/default
```

## Actual Behavior

但是 kubevirt 创建的 VM 的 pod 的 k8s.v1.cni.cncf.io/network-status: 为 "multus-cni-network"
```yaml
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "multus-cni-network",
          "interface": "eth0",
          "ips": [
              "10.5.192.6"
          ],
          "mac": "00:00:00:66:E7:80",
          "default": true,
          "dns": {},
          "gateway": [
              "10.5.196.1"
          ]
      }]
    ovn.kubernetes.io/allocated: 'true'
    ovn.kubernetes.io/cidr: 10.5.192.0/18
    ovn.kubernetes.io/gateway: 10.5.196.1
    ovn.kubernetes.io/ip_address: 10.5.192.6
    ovn.kubernetes.io/logical_router: ovn-cluster
    ovn.kubernetes.io/logical_switch: ovn-default
    ovn.kubernetes.io/mac_address: 00:00:00:66:E7:80
    ovn.kubernetes.io/pod_nic_type: veth-pair
    ovn.kubernetes.io/routed: 'true'
    ovn.kubernetes.io/virtualmachine: my-vm
```

## Steps to Reproduce the Problem

1. 参考这个文档配置 offload: https://kubeovn.github.io/docs/v1.12.x/advance/offload-mellanox/
2. 添加   annotations:  `v1.multus-cni.io/default-network: default/default` 后尝试创建 vm

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`: **

```bash
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-14T09:56:58Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.11", GitCommit:"3cd242c51317aed8858119529ccab22079f523b1", GitTreeState:"clean", BuildDate:"2023-11-15T16:50:12Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"linux/amd64"}
```

- kube-ovn version:
  
```bash
1.12.0
```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:** 
  **Output of `uname -r`:** 

```bash
"Ubuntu 22.04.2 LTS"
  5.15.0-71-generic
```

Here is my vm yaml

```yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: my-vm
spec:
  preference: ...
  runStrategy: Always
  template:
    metadata:
      annotations: # 这两个 annotation 在 pod 中都没有，很奇怪
        a/b: c
        v1.multus-cni.io/default-network: default/default
    spec:
      domain:
        cpu:
          cores: 2
          model: host-model
        devices:
          disks:
            - name: system-disk
          inputs:
            - name: tablet
              type: tablet
          interfaces:
            - bridge: {}
              name: default
        machine:
          type: q35
        resources:
          limits:
            cpu: '2'
            mellanox.com/cx5_sriov_switchdev: '1'
            memory: 4Gi
          requests:
            mellanox.com/cx5_sriov_switchdev: '1'
      networks:
        - name: default
          pod: {}
      volumes:
        - name: system-disk
          persistentVolumeClaim:
            claimName: my-pvc
```
