### ISSUE TITLE
使用kube-ovn创建underlay网络后，再在k8s节点上使用kvm创建vm，网络桥接在br-provider1上面，出现vm与当前宿主机网络不通

### ISSUE THREAD

**Issue by tghfly** [kubeovn/kube-ovn#3573]
# Bug Report
使用kube-ovn创建underlay网络后，再在k8s节点上使用kvm创建vm，网络桥接在br-provider1上面，出现vm与当前宿主机网络不通，但vm可以与其他k8s宿主机通信。
## Expected Behavior
使用kube-ovn创建underlay网络后，再在k8s节点上使用kvm创建vm，网络桥接在br-provider1上面，vm与当前宿主机网络能通
## Actual Behavior
使用kube-ovn创建underlay网络后，再在k8s节点上使用kvm创建vm，网络桥接在br-provider1上面，出现vm与当前宿主机网络不通，但vm可以与其他k8s宿主机通信。

## Steps to Reproduce the Problem
1.使用kube-ovn 创建underlay网络
```yaml
---
kind: ProviderNetwork
metadata:
  name: provider1
spec:
  defaultInterface: eth0
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: provider
spec:
  protocol: IPv4
  cidrBlock: 192.168.171.0/24
  gateway: 192.168.171.1
  vlan: provider1-vlan0
  enableDHCP:  true
  dhcpV4Options: lease_time=86400,router=192.168.171.1
  excludeIps:
  - 192.168.171.0..192.168.171.10
---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: provider1-vlan0
spec:
  id: 0
  provider: provider1
```
2. 在k8s节点上安装kvm，并使用virt-manager创建vm，在选择网络时，使用桥接，选择br-provider1
3.  在vm中配置好ip 192.168.171.112/24后，在vm上ping当前vm所在的k8s宿主机出现网络不通，并且互ping及telnet相关端口均不通。

## Additional Info

- Kubernetes version: 1.27.4

  **Output of `kubectl version`:** 

  ```bash
  (paste your output here)

  ```

- kube-ovn version: 1.11.8
  
  ```bash
  (paste your output here)

  ```

- operation-system/kernel version: 5.4.251-1.el8.elrepo.x86_64
