### ISSUE TITLE
Better name for CNI_CONF_FILE variable

### ISSUE THREAD

**Issue by aminmr** [kubeovn/kube-ovn#3701]
# Bug Report

## Expected Behavior
When I configured the helm chart values for the `cni.conf` section, I thought that the CNI_CONF_FILE variable is the file name that will be created on each node in the `/etc/cni/net.d` path. So by changing the CNI_CONFIG_PRIORITY to 10, I also changed this variable file name to `/kube-ovn/10-kube-ovn.conflist`
```
cni_conf:
  CHECK_GATEWAY: true
  LOGICAL_GATEWAY: false
  CNI_CONFIG_PRIORITY: "10"
  CNI_CONF_DIR: "/etc/cni/net.d"
  CNI_BIN_DIR: "/opt/cni/bin"
  CNI_CONF_FILE: "/kube-ovn/10-kube-ovn.conflist"
```

## Actual Behavior
This variable is a sample file directory for CNI_CONF content and the name of the file is generated based on the `CNI_CONFIG_PRIORITY` variable

## Suggestion
I suggest that it's better to rename this variable value to something like `10-kube-ovn.conflist.sample` or also rename the variable to something else. I am aware that this change forces me to change the filename in the Dockerfile and other parts of the project.
If you agree, I am volunteering to open a PR for these changes.
```
cni_conf:
  CHECK_GATEWAY: true
  LOGICAL_GATEWAY: false
  CNI_CONFIG_PRIORITY: "10"
  CNI_CONF_DIR: "/etc/cni/net.d"
  CNI_BIN_DIR: "/opt/cni/bin"
  CNI_CONF_FILE: "/kube-ovn/kube-ovn.conflist.sample"
```
