### ISSUE TITLE
 kubevirt vm通过spec.template.metadata.annotations固定ip,修改ip后重启vm,vmi一直处于scheduling

### ISSUE THREAD

**Issue by mtpdx** [kubeovn/kube-ovn#3741]
# Bug Report
kubevirt通过以下方式创建固定ip的虚拟机:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  name: vm-pnvf7c6q
  namespace: default
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        net-d89vgy72.virt-system.ovn.kubernetes.io/ip_address: 10.20.3.2
        net-d89vgy72.virt-system.ovn.kubernetes.io/mac_address: 00:00:00:73:A4:FD
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: disk-6bywls2r
          interfaces:
            - bridge: {}
              macAddress: 00:00:00:73:A4:FD
              name: eth0
        machine:
          type: q35
        resources:
          limits:
            cpu: '1'
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
      evictionStrategy: LiveMigrate
      hostname: fvghfcv
      networks:
        - multus:
            default: true
            networkName: virt-system/net-d89vgy72
          name: eth0
      volumes:
        - cloudInitNoCloud:
            networkDataBase64: >-
              dmVyc2lvbjogMgpldGhlcm5ldHM6CiAgZXRoMDoKICAgIGRoY3A0OiB0cnVlCiAgICBtYXRjaDoKICAgICAgbWFjYWRkcmVzczogMDA6MDA6MDA6NzM6QTQ6RkQKICAgIG5hbWVzZXJ2ZXJzOgogICAgICBhZGRyZXNzZXM6CiAgICAgIC0gMTE0LjExNC4xMTQuMTE0Cg==
            userDataBase64: >-
              CiNjbG91ZC1jb25maWcKdXBkYXRlczoKICBuZXR3b3JrOgogICAgd2hlbjogWyAnYm9vdCcgXQp0aW1lem9uZTogQXNpYS9TaGFuZ2hhaQpwYWNrYWdlczoKICAtIGNsb3VkLWluaXQKcGFja2FnZV91cGRhdGU6IHRydWUKc3NoX3B3YXV0aDogdHJ1ZQpkaXNhYmxlX3Jvb3Q6IGZhbHNlCmNocGFzc3dkOiB7ICJsaXN0IjogInJvb3Q6MTIzNDU2IixleHBpcmU6IEZhbHNlIH0KcnVuY21kOgogIC0gc2VkIC1pICIvUGVybWl0Um9vdExvZ2luL3MvXi4qJC9QZXJtaXRSb290TG9naW4geWVzL2ciIC9ldGMvc3NoL3NzaGRfY29uZmlnCiAgLSBzeXN0ZW1jdGwgcmVzdGFydCBzc2hkLnNlcnZpY2UK
          name: cloudinitdisk
        - name: disk-6bywls2r
          persistentVolumeClaim:
            claimName: sys-6bywls2r
    
```
vmi running后,修改vm中ip地址为10.20.3.3:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  name: vm-pnvf7c6q
  namespace: default
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        net-d89vgy72.virt-system.ovn.kubernetes.io/ip_address: 10.20.3.3
        net-d89vgy72.virt-system.ovn.kubernetes.io/mac_address: 00:00:00:73:A4:FD

...    
     
```
然后重启vm

## Expected Behavior
vmi running并且ip为修改后的地址

## Actual Behavior
vmi一直处于scheduling状态;
与vmi对应的pod处于pending,并且出现以下events:
```
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "917264c0f81ca786db8d2c6c72097ee81598f42066bcbdace3a1d82ccb9c2727": plugin type="multus-shim" name="multus-cni-network" failed (add): CmdAdd (shim): CNI request failed with status 400: '&{ContainerID:917264c0f81ca786db8d2c6c72097ee81598f42066bcbdace3a1d82ccb9c2727 Netns:/var/run/netns/cni-d2d96743-af14-9f8a-fde5-64aa210e1bb9 IfName:eth0 Args:K8S_POD_UID=d525d2f3-ec9e-43d2-a3db-6f8234592275;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=virt-launcher-vm-pnvf7c6q-4pcg9;K8S_POD_INFRA_CONTAINER_ID=917264c0f81ca786db8d2c6c72097ee81598f42066bcbdace3a1d82ccb9c2727 Path: StdinData:[123 34 99 97 112 97 98 105 108 105 116 105 101 115 34 58 123 34 112 111 114 116 77 97 112 112 105 110 103 115 34 58 116 114 117 101 125 44 34 99 104 114 111 111 116 68 105 114 34 58 34 47 104 111 115 116 114 111 111 116 34 44 34 99 108 117 115 116 101 114 78 101 116 119 111 114 107 34 58 34 47 104 111 115 116 47 101 116 99 47 99 110 105 47 110 101 116 46 100 47 48 49 45 107 117 98 101 45 111 118 110 46 99 111 110 102 108 105 115 116 34 44 34 99 110 105 67 111 110 102 105 103 68 105 114 34 58 34 47 104 111 115 116 47 101 116 99 47 99 110 105 47 110 101 116 46 100 34 44 34 99 110 105 86 101 114 115 105 111 110 34 58 34 48 46 51 46 49 34 44 34 108 111 103 76 101 118 101 108 34 58 34 118 101 114 98 111 115 101 34 44 34 108 111 103 84 111 83 116 100 101 114 114 34 58 116 114 117 101 44 34 109 117 108 116 117 115 65 117 116 111 99 111 110 102 105 103 68 105 114 34 58 34 47 104 111 115 116 47 101 116 99 47 99 110 105 47 110 101 116 46 100 34 44 34 109 117 108 116 117 115 67 111 110 102 105 103 70 105 108 101 34 58 34 97 117 116 111 34 44 34 110 97 109 101 34 58 34 109 117 108 116 117 115 45 99 110 105 45 110 101 116 119 111 114 107 34 44 34 115 111 99 107 101 116 68 105 114 34 58 34 47 104 111 115 116 47 114 117 110 47 109 117 108 116 117 115 47 34 44 34 116 121 112 101 34 58 34 109 117 108 116 117 115 45 115 104 105 109 34 125]} ContainerID:"917264c0f81ca786db8d2c6c72097ee81598f42066bcbdace3a1d82ccb9c2727" Netns:"/var/run/netns/cni-d2d96743-af14-9f8a-fde5-64aa210e1bb9" IfName:"eth0" Args:"K8S_POD_UID=d525d2f3-ec9e-43d2-a3db-6f8234592275;IgnoreUnknown=1;K8S_POD_NAMESPACE=default;K8S_POD_NAME=virt-launcher-vm-pnvf7c6q-4pcg9;K8S_POD_INFRA_CONTAINER_ID=917264c0f81ca786db8d2c6c72097ee81598f42066bcbdace3a1d82ccb9c2727" Path:"" ERRORED: error configuring pod [default/virt-launcher-vm-pnvf7c6q-4pcg9] networking: [default/virt-launcher-vm-pnvf7c6q-4pcg9/d525d2f3-ec9e-43d2-a3db-6f8234592275:net-d89vgy72]: error adding container to network "net-d89vgy72": RPC failed; request ip return 500 configure nic failed no packets received from gateway [10.20.3.1](http://10.20.3.1/) '
```

## Additional Info

- Kubernetes version:
```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:16Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.13", GitCommit:"592eca05be27f7d927d0b25cbb4241d75a9574bf", GitTreeState:"clean", BuildDate:"2022-10-12T10:50:48Z", GoVersion:"go1.17.13", Compiler:"gc", Platform:"linux/amd64"}

```

- kube-ovn version:
```bash
 1.12.4

  ```

- kubevirt version:
```bash
 1.0.0

  ```

- operation-system/kernel version:
```bash
$ awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"Ubuntu 20.04.6 LTS"
$ uname -r
5.15.0-92-generic

  ```
