### ISSUE TITLE
Overlay模式下 LoadBalancer 类型Service 无法获取到请求源IP

### ISSUE THREAD

**Issue by Mrtao1028** [kubeovn/kube-ovn#3788]
# Bug Report
Overlay模式下 LoadBalancer 类型Service 无法获取到请求源IP

## Expected Behavior
从集群外发起对LB IP的请求，实际应答Pod能够获取到集群外发起请求的 源IP 

## Actual Behavior
从集群外发起对LB IP的请求， 实际只能获取到 对应Service Pod的PodIP 
![impicture_20240304_135738](https://github.com/kubeovn/kube-ovn/assets/7741839/a81b4cc0-1fb8-4ec2-ba97-3fcd7f27372f)

![impicture_20240304_135803](https://github.com/kubeovn/kube-ovn/assets/7741839/250c7847-d195-41a0-825f-dab9605a8db5)

## Steps to Reproduce the Problem

1. kube-ovn 相关配置
```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: lb-svc-attachment
  namespace: kube-system
spec:
  config: '{ 
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge"
    }'
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: attach-subnet
spec:
  cidrBlock: 192.168.8.0/24
  default: false
  enableLb: true
  excludeIps:
  - 192.168.8.1..192.168.8.180
  - 192.168.8.192..192.168.8.254
  gateway: 192.168.8.1
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: lb-svc-attachment.kube-system
  vpc: ovn-cluster
```
2.  测试部署
  ```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - image: hub.docker.com/containous/whoami:latest
        imagePullPolicy: Always
        name: whoami
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
---
apiVersion: v1
kind: Service
metadata:
  name: whoami-lb
  namespace: default
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami
  type: LoadBalancer
 ```

## Additional Info

- Kubernetes version: 
  ```bash
     $ kubectl version
    Client Version: v1.28.2
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.28.0
    ```

- kube-ovn version:  1.12.5
  

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

  ```bash
  (paste your output here)
  Debian GNU/Linux 10 (buster)
 4.19.0-21-amd64
  ```
