### ISSUE TITLE
v1.12.8 默认VPC无法创建external-gw网关

### ISSUE THREAD

**Issue by imwuwei** [kubeovn/kube-ovn#3798]
# Bug Report

利用 OVN 中的 L3 Gateway 功能来实现 Pod 级别的 SNAT 和 EIP 功能时，无法创建ovn external交换机和ovs中的br-external网桥

## Expected Behavior

应该能在ovn中创建external交换机，ovs中创建br-external网桥，实现L3 Gateway 功能。

## Actual Behavior
kube-ovn-controller中存在错误日志，无法创建外部网关
![image](https://github.com/kubeovn/kube-ovn/assets/24752677/e188f2d8-4f0a-418d-a0d6-734484b5e4bc)

ovn北向数据库中没显示创建external交换机
![image](https://github.com/kubeovn/kube-ovn/assets/24752677/867831cf-aba3-4a08-915b-dd04934d67c3)

## Steps to Reproduce the Problem

1.  ConfigMap配置
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  type: "distributed"
  external-gw-nic: "eth1"
  external-gw-addr: "10.15.14.1/24"
  nic-ip: "10.15.14.254/24"
  nic-mac: "fa:51:f3:13:1a:aa"
```
3. 使用的kube-ovn安装脚本
```bash
https://raw.githubusercontent.com/kubeovn/kube-ovn/release-1.12/dist/images/install.sh
```

## Additional Info

- Kubernetes version:
```bash
$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.0
```

- kube-ovn version: 1.12.8

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

```bash
$ awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"Debian GNU/Linux 10 (buster)"
$ uname -r
5.19.0-21-amd64
```
