### ISSUE TITLE
The evicted pod did not enter the deletion queue on k8s 1.28.

### ISSUE THREAD

**Issue by xieyunyue** [kubeovn/kube-ovn#3810]
# Bug Report
在k8s1.28上，pod由于内存压力触发了驱逐，pod的网络资源没有被回收，没有进入删除队列中

## Expected Behavior
被驱除的pod资源也会被回收

## Actual Behavior
被驱除的pod资源没有被回收

## Steps to Reproduce the Problem

1.使用stress在节点上模拟内存压力:stress --vm 1 --vm-bytes 13G --vm-keep
2.等待deployment的pod被驱除
3.pod ip没有被回收

## 额外信息
在k8s 1.28上，pod被驱除后，出现了两种状态Completed和ContainerStatusUnknown

ContainerStatusUnknown状态的pod ip会进入deletequeue，由于下面的原因
```yaml
phase: Failed
  podIP: 10.16.0.50
  podIPs:
  - ip: 10.16.0.50
  qosClass: BestEffort
  reason: Evicted
```

满足下列方法的第三个条件
```golang
func isPodAlive(p *v1.Pod) bool {
	...
	if p.Status.Phase == v1.PodSucceeded && p.Spec.RestartPolicy != v1.RestartPolicyAlways {
		return false
	}

	if p.Status.Phase == v1.PodFailed && p.Spec.RestartPolicy == v1.RestartPolicyNever {
		return false
	}

	if p.Status.Phase == v1.PodFailed && p.Status.Reason == "Evicted" {
		return false
	}
	...
}
```
Completed的pod phase:是Succeeded，但是由于它是deployment的pod，restartpolicy默认是always，第一个条件不满足，所以没有加入到删除队列中。
我理解这里加上p.Spec.RestartPolicy != v1.RestartPolicyAlways的判断是对job产生的pod判断。但现在发现被驱除的pod也会处于这个状态。所以这里是否可以直接把p.Spec.RestartPolicy != v1.RestartPolicyAlways 去掉

**completed状态的pod yaml**
```yaml
apiVersion: v1
kind: Pod
....
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-03-07T03:17:50Z"
    message: 'The node was low on resource: memory. Threshold quantity: 2Gi, available:
      863276Ki. Container nginx was using 5980Ki, request is 0, has larger consumption
      of memory. '
    reason: TerminationByKubelet
    status: "True"
    type: DisruptionTarget
  - lastProbeTime: null
    lastTransitionTime: "2024-03-07T03:13:29Z"
    reason: PodCompleted
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-03-07T03:17:50Z"
    reason: PodCompleted
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-03-07T03:17:50Z"
    reason: PodCompleted
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-03-07T03:13:29Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://2afad7d8dd63c55034416a77bb2ea4ccfb620c6259ee2ae3233b2dbd0ea665f2
  ...
    state:
      terminated:
        containerID: containerd://2afad7d8dd63c55034416a77bb2ea4ccfb620c6259ee2ae3233b2dbd0ea665f2
        exitCode: 0
        finishedAt: "2024-03-07T03:17:49Z"
        reason: Completed
        startedAt: "2024-03-07T03:13:39Z"
  hostIP: 10.20.0.8
  phase: Succeeded
  podIP: 10.16.0.66
  podIPs:
  - ip: 10.16.0.66
  qosClass: BestEffort
  startTime: "2024-03-07T03:13:29Z"
```
