### ISSUE TITLE
ovn-fip绑定一个pod A后，解绑，再绑定pod B，无法通过ovn-eip访问pod B

### ISSUE THREAD

**Issue by geniusxiong** [kubeovn/kube-ovn#3815]
# Bug Report
kubeovn 1.13.0版本，ovn-fip绑定一个pod A后，解绑，再绑定pod B，无法通过ovn-eip访问pod B
## Expected Behavior
ovn-fip绑定一个pod A后，解绑，再绑定pod B，能够通过ovn-eip访问pod B

## Steps to Reproduce the Problem

1.  为 pod A 绑定一个ovn-fip
```
[root@master-0 ovn]# cat ovneip-vm.yaml
kind: OvnEip
apiVersion: kubeovn.io/v1
metadata:
  name: eip-vm-1
spec:
  externalSubnet: external204
  type: nat

[root@master-0 ovn]# cat ovnfip-vm.yaml
kind: OvnFip
apiVersion: kubeovn.io/v1
metadata:
  name: fip-vm-1
spec:
  ovnEip: eip-vm-1
  ipName: i-kbh7b0o6.vpc1-ns

[root@master-0 ovn]# kubectl get ofip
NAME       VPC    V4EIP           V4IP         READY   IPTYPE   IPNAME
fip-vm-1   vpc1   172.18.164.65   10.50.1.9   true             i-kbh7b0o6.vpc1-ns
```
此时eip是172.18.164.65，podA ip是10.50.1.9
外部是可以ping 通172.18.164.65

2. 解除绑定podA
``` 
[root@master-0 ovn]# kubectl delete -f ovnfip-vm.yaml 
ovnfip.kubeovn.io "fip-vm-1" deleted

[root@master-0 ovn]# kubectl get ofip
No resources found in default namespace.
```
3. 绑定podB
```
[root@master-0 ovn]# cat ovnfip-vm.yaml
kind: OvnFip
apiVersion: kubeovn.io/v1
metadata:
  name: fip-vm-1
spec:
  ovnEip: eip-vm-1
  ipName: **i-j3be6h11.vpc1-ns**

[root@master-0 ovn]# kubectl get ofip
NAME       VPC    V4EIP           V4IP        READY   IPTYPE   IPNAME
fip-vm-1   vpc1   172.18.164.65   10.50.1.11   true             i-j3be6h11.vpc1-ns
```
显示绑定podB(10.50.1.9)成功
4. 外部ping 172.18.164.65不通
网关节点抓包，只收到外部来的ping包，没有回包
```
22:13:30.726068 IP 172.18.120.173 > 172.18.164.65: ICMP echo request, id 11312, seq 8, length 108
```
podB内抓包，没有收到外部来的ping包

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

- kube-ovn version:
  
```
1.13.0
```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
 ```
NFS Server 4.0 (G193)
4.19.113-3.nfs.x86_64
```

这个现象好像不是必现，但是有90%的可能会出现，如果没有出现，可以尝试再解绑再绑定，现象会出现
