### ISSUE TITLE
Handle encapsulating vpc-gateway subnet VLANs

### ISSUE THREAD

**Issue by Smithx10** [kubeovn/kube-ovn#3828]
We were hoping to use VPC to isolate internal teams to their own ovleray VPC fabric and have them NAT to a group 
of routable networks on a variety of different VLANs. 

As Described [here](https://kube-ovn.readthedocs.io/zh-cn/latest/en/guide/vpc/#configuring-the-external-network) we currently need to plumb up Subinterfaces that have the appropriate VLAN tagged in order for macvlan to forward.   We'd like to be able to introduce / have a way for specifying an carrier grade interface such as a "bond" and have kube ovn handle tagging the vlan provided in the external nat subnet declaration.

Since we are allocated routable networks on their own VLAN typically in the size of a /24 it would be nice to be able to group kubeovn subnets into another type of network object called a "SubnetPool".  

A subnet pool would be a logical representation of many subnets that serve the same purpose.... in our case being externally routable subnets that can be used by all VPCs to NAT out.

I could be wrong in my interpretation so please correct me accordingly.

"If the physical network card corresponds to a switch interface in Trunk mode, a sub-interface needs to be created on the network card and provided to Macvlan for use."

``` yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 192.168.0.0/24
  gateway: 192.168.0.1  # IP address of the physical gateway
  excludeIps:
  - 192.168.0.1..192.168.0.10
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth1",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }'
```

**Comment by Smithx10** [comment]
While reading the docs more....

It appears that VPC gateways does allow for an array of NAT Subnets and for their connectivity to be constrained to certain nodes via  selector.... 

#### Create VPC Gateway and Set the Default Route[¶](https://kube-ovn.readthedocs.io/zh-cn/latest/en/guide/vpc/#create-vpc-gateway-and-set-the-default-route) 
``` yaml
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw1
spec:
  vpc: test-vpc-1
  subnet: net1
  lanIp: 10.0.1.254
  selector:
    - "kubernetes.io/hostname: kube-ovn-worker"
    - "kubernetes.io/os: linux"
  externalSubnets:
    - ovn-vpc-external-network
```
