### ISSUE TITLE
2 provider-network can't share same bond

### ISSUE THREAD

**Issue by Smithx10** [kubeovn/kube-ovn#3909]
While attempting to setup EIP  I created the following configuration.

Creating 2 provider on the bond resulted the 2nd one having mtu-15000 and not able to ping the gateway.    using br-external pods work as expected.   using br-external1998 did not.

``` yaml
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: external
spec:
  defaultInterface: external
---
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: "external1998"
spec:
  defaultInterface: external
---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: eip
spec:
  id: 1998
  provider: external1998
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: eip
spec:
  vlan: "eip"
  protocol: IPv4
  cidrBlock: 10.91.64.0/19
  gateway: 10.91.95.254
  gatewayType: distributed
  natOutgoing: false
```

This resulted with 
```
* 7: external
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: /etc/systemd/network/01-external.network
                         State: degraded (configured)
                  Online state: online
                          Type: bond
                          Kind: bond
                        Driver: bonding
              Hardware Address: 96:60:27:94:89:54
                           MTU: 9000 (min: 68, max: 65535)
                         QDisc: noqueue
                        Master: ovs-system
  IPv6 Address Generation Mode: eui64
                          Mode: 802.3ad
                        Miimon: 1s
                       Updelay: 2s
                     Downdelay: 8s
      Number of Queues (Tx/Rx): 16/16
              Auto negotiation: no
                         Speed: 50Gbps
                        Duplex: full
                       Address: fe80::9460:27ff:fe94:8954
             Activation Policy: up
           Required For Online: yes
             DHCP6 Client DUID: DUID-EN/Vendor:0000ab116c32ecf536209975


* 15: br-external
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: n/a
                         State: routable (unmanaged)
                  Online state: unknown
                          Type: ether
                          Kind: openvswitch
                        Driver: openvswitch
              Hardware Address: 96:60:27:94:89:54
                           MTU: 9000 (min: 68, max: 65535)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
      Number of Queues (Tx/Rx): 1/1
                       Address: 172.16.0.20
                                fe80::9460:27ff:fe94:8954

* 39: br-external1998
                     Link File: /usr/lib/systemd/network/99-default.link
                  Network File: n/a
                         State: degraded (unmanaged)
                  Online state: unknown
                          Type: ether
                          Kind: openvswitch
                        Driver: openvswitch
              Hardware Address: 96:60:27:94:89:54
                           MTU: 1500 (min: 68, max: 65535)
                         QDisc: noqueue
  IPv6 Address Generation Mode: eui64
      Number of Queues (Tx/Rx): 1/1
                       Address: fe80::9460:27ff:fe94:8954
```

**Comment by zhangzujian** [comment]
provider-networks cannot share the same nic.

**Comment by zhangzujian** [comment]
If you want to use different VLANs on the same nic, you can refer the provider-network in multiple vlans:

```yaml
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan1
spec:
  id: 1
  provider: external
---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan2
spec:
  id: 2
  provider: external
```
