### ISSUE TITLE
Can't create pod with join subnet

### ISSUE THREAD

**Issue by Longchuanzheng** [kubeovn/kube-ovn#3947]
# Bug Report
When create pod with :
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    attachnet.default.ovn.kubernetes.io/allow_live_migration: "true"
    attachnet.default.ovn.kubernetes.io/logical_switch: join
    attachnet.default.ovn.kubernetes.io/default_route: "true"
    k8s.v1.cni.cncf.io/networks: attachnet
  name: zal-busybox-0422
spec:
  containers:
    - image: registry.paas/zhuanlan/busybox:stable
      command:
        - sleep
        - "86400"
      name: busybox
```
Kube-ovn can't do cmdADD succeeded.
![image](https://github.com/kubeovn/kube-ovn/assets/49519342/be13c040-0c5a-4cc3-8198-4adc3f1ba493)
We can find error in ovn-controller
![image](https://github.com/kubeovn/kube-ovn/assets/49519342/3ef75bc1-c356-4c55-bafe-88fb0c2ff6d0)

## Expected Behavior
When we create pod with join subnet, kube-ovn should reject this request or should do 'cmdADD' succeeded.
## Actual Behavior
Kube-ovn do 'cmdADD' failed.
## Steps to Reproduce the Problem

1.create nad 
2.create pod with yaml above
3.

## Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```bash
  (paste your output here)

  ```

- kube-ovn version:
  
  ```bash
  1.12

  ```

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**

  ```bash
  (paste your output here)
  
  ```
