### ISSUE TITLE
Keepalived vip in kubevirt ping failed.

### ISSUE THREAD

**Issue by yehaifeng** [kubeovn/kube-ovn#3956]
### Kube-OVN Version

v1.11.15

### Kubernetes Version

v1.28.2

### Operation-system/Kernel Version

5.14.0-391.el9.x86_64

### Description

Startup keepalived in kubevirt and up a vip, but i cann't ping the vip outside cluster.
Anything i can do?

### Steps To Reproduce

1. Installing a vm using kubevirt with kube-ovn sdn
2. Starting keepalived and a vip
3. Ping this vip from other machine.

### Current Behavior

Ping vip failed.

### Expected Behavior

Ping vip success

**Comment by zhangzujian** [comment]
Please try to add the following annotation to the kubevirt vm/pod in your vm definition:

```yaml
ovn.kubernetes.io/layer2_forward: true
```

**Comment by yehaifeng** [comment]
I added this annotation but it is not working

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/default-container: compute
    kubevirt.io/allow-pod-bridge-network-live-migration: ""
    kubevirt.io/migrationTransportUnix: "true"
    kubevirt.io/vm-generation: "2"
    ovn.kubernetes.io/allocated: "true"
    ovn.kubernetes.io/cidr: 192.168.81.0/24
    ovn.kubernetes.io/ip_address: 192.168.81.4
    ovn.kubernetes.io/layer2_forward: "true"
    ovn.kubernetes.io/logical_switch: subnet81
    ovn.kubernetes.io/mac_address: 00:50:56:b7:6f:03
    ovn.kubernetes.io/pod_nic_type: veth-pair
    ovn.kubernetes.io/provider_network: trunk
    ovn.kubernetes.io/routed: "true"
    ovn.kubernetes.io/vlan_id: "81"
```
