### ISSUE TITLE
Is there an elegant way to create >=2 nic with the same subnet in kube-ovn?

### ISSUE THREAD

**Issue by zsxsoft** [kubeovn/kube-ovn#4045]
### Description

I hope that the resources of the same pod can be accessed from multiple IPs in the same subnet (i.e., the same process can be accessed at 10.8.8.2:80 / 10.8.8.3:80 / 10.8.8.4:80). I tried to use NAD to meet this requirement, and the yaml follows: same provider for different NADs.

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: net-8889
spec:
  cidrBlock: 10.8.9.0/24
  default: false
  gateway: 10.8.9.1
  natOutgoing: true
  private: false
  protocol: IPv4
  disableGatewayCheck: true
  provider: net-8889-1.vm.ovn
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net-8889-1
  namespace: vm
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "net-8889-1.vm.ovn"
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net-8889-2
  namespace: vm
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "net-8889-1.vm.ovn"
    }'
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: vm
  annotations:
    k8s.v1.cni.cncf.io/networks: vm/net-8889-1,vm/net-8889-2
    net-8889-2.vm.kubernetes.io/mac_address: 00:00:00:AA:AA:AA
spec:
  containers:
  - name: nginx
    image: nginx

```

Obviously, this has caused confusion.

```yaml
> kubectl describe -n vm pod nginx
Name:             nginx
Namespace:        vm
Priority:         0
Service Account:  default
Node:             keen-16/192.168.231.16
Start Time:       Fri, 17 May 2024 21:34:50 +0800
Labels:           <none>
Annotations:      k8s.v1.cni.cncf.io/network-status:
                    [{
                        "name": "kube-ovn",
                        "interface": "eth0",
                        "ips": [
                            "10.16.1.3"
                        ],
                        "mac": "00:00:00:F1:0E:61",
                        "default": true,
                        "dns": {},
                        "gateway": [
                            "10.16.0.1"
                        ]
                    },{
                        "name": "vm/net-8889-1",
                        "interface": "net1",
                        "ips": [
                            "10.8.9.4"
                        ],
                        "mac": "00:00:00:CA:66:21",
                        "dns": {}
                    },{
                        "name": "vm/net-8889-2",
                        "interface": "net2",
                        "ips": [
                            "10.8.9.4" # same ip here
                        ],
                        "mac": "00:00:00:CA:66:21",
                        "dns": {}
                    }]
                  k8s.v1.cni.cncf.io/networks: vm/net-8889-1,vm/net-8889-2
                  net-8889-1.vm.ovn.kubernetes.io/allocated: true
                  net-8889-1.vm.ovn.kubernetes.io/cidr: 10.8.9.0/24
                  net-8889-1.vm.ovn.kubernetes.io/gateway: 10.8.9.1
                  net-8889-1.vm.ovn.kubernetes.io/ip_address: 10.8.9.4
                  net-8889-1.vm.ovn.kubernetes.io/logical_router: ovn-cluster
                  net-8889-1.vm.ovn.kubernetes.io/logical_switch: net-8889
                  net-8889-1.vm.ovn.kubernetes.io/mac_address: 00:00:00:CA:66:21
                  net-8889-1.vm.ovn.kubernetes.io/pod_nic_type: veth-pair
                  net-8889-1.vm.ovn.kubernetes.io/routed: true
                  net-8889-2.vm.kubernetes.io/mac_address: 00:00:00:AA:AA:AA
                  net-8889-2.vm.ovn.kubernetes.io/allocated: true
                  net-8889-2.vm.ovn.kubernetes.io/cidr: 10.16.0.0/16
                  net-8889-2.vm.ovn.kubernetes.io/gateway: 10.16.0.1
                  net-8889-2.vm.ovn.kubernetes.io/ip_address: 10.16.1.2
                  net-8889-2.vm.ovn.kubernetes.io/logical_router: ovn-cluster
                  net-8889-2.vm.ovn.kubernetes.io/logical_switch: ovn-default # <- mistake here, it should be net-8889
                  net-8889-2.vm.ovn.kubernetes.io/mac_address: 00:00:00:D4:88:2F
                  net-8889-2.vm.ovn.kubernetes.io/pod_nic_type: veth-pair
                  net-8889-2.vm.ovn.kubernetes.io/routed: true
                  ovn.kubernetes.io/allocated: true
                  ovn.kubernetes.io/cidr: 10.16.0.0/16
                  ovn.kubernetes.io/gateway: 10.16.0.1
                  ovn.kubernetes.io/ip_address: 10.16.1.3
                  ovn.kubernetes.io/logical_router: ovn-cluster
                  ovn.kubernetes.io/logical_switch: ovn-default
                  ovn.kubernetes.io/mac_address: 00:00:00:F1:0E:61
                  ovn.kubernetes.io/pod_nic_type: veth-pair
                  ovn.kubernetes.io/routed: true
Status:           Running
```

I think this might be because the providers cannot be the same, so I made changes based on the behavior of the relevant code: https://github.com/kubeovn/kube-ovn/blob/a0c2a4344b8f211c502dc1e1c161d94bb778a51b/pkg/controller/pod.go#L1623-L1626

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: net-8889
spec:
  cidrBlock: 10.8.9.0/24
  default: false
  gateway: 10.8.9.1
  natOutgoing: true
  private: false
  protocol: IPv4
  disableGatewayCheck: true
  # <- deleted provider here
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net-8889-1
  namespace: vm
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "net-8889-1.vm.ovn"
    }'
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: net-8889-2
  namespace: vm
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "kube-ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "net-8889-2.vm.ovn"
    }'
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: vm
  annotations:
    k8s.v1.cni.cncf.io/networks: vm/net-8889-1,vm/net-8889-2
    net-8889-1.vm.ovn.kubernetes.io/logical_switch: net-8889 # <- set subnet manually
    net-8889-2.vm.kubernetes.io/mac_address: 00:00:00:AA:AA:AA
    net-8889-2.vm.ovn.kubernetes.io/logical_switch: net-8889
spec:
  containers:
  - name: nginx
    image: nginx

```

```bash
> kubectl describe -n vm pod nginx
                  net-8889-1.vm.ovn.kubernetes.io/allocated: true
                  net-8889-1.vm.ovn.kubernetes.io/cidr: 10.8.9.0/24
                  net-8889-1.vm.ovn.kubernetes.io/gateway: 10.8.9.1
                  net-8889-1.vm.ovn.kubernetes.io/ip_address: 10.8.9.2
                  net-8889-1.vm.ovn.kubernetes.io/logical_router: ovn-cluster
                  net-8889-1.vm.ovn.kubernetes.io/logical_switch: net-8889
                  net-8889-1.vm.ovn.kubernetes.io/mac_address: 00:00:00:86:AB:6F
                  net-8889-1.vm.ovn.kubernetes.io/pod_nic_type: veth-pair
                  net-8889-1.vm.ovn.kubernetes.io/routed: true
                  net-8889-2.vm.kubernetes.io/mac_address: 00:00:00:AA:AA:AA
                  net-8889-2.vm.ovn.kubernetes.io/allocated: true
                  net-8889-2.vm.ovn.kubernetes.io/cidr: 10.8.9.0/24
                  net-8889-2.vm.ovn.kubernetes.io/gateway: 10.8.9.1
                  net-8889-2.vm.ovn.kubernetes.io/ip_address: 10.8.9.3
                  net-8889-2.vm.ovn.kubernetes.io/logical_router: ovn-cluster
                  net-8889-2.vm.ovn.kubernetes.io/logical_switch: net-8889
                  net-8889-2.vm.ovn.kubernetes.io/mac_address: 00:00:00:9E:AB:0D
                  net-8889-2.vm.ovn.kubernetes.io/pod_nic_type: veth-pair
                  net-8889-2.vm.ovn.kubernetes.io/routed: true
root@nginx:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
108: eth0@if109: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default 
    link/ether 00:00:00:7f:00:70 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.16.1.4/16 brd 10.16.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe7f:70/64 scope link 
       valid_lft forever preferred_lft forever
110: net1@if111: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default 
    link/ether 00:00:00:86:ab:6f brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.8.9.2/24 brd 10.8.9.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe86:ab6f/64 scope link 
       valid_lft forever preferred_lft forever
112: net2@if113: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default 
    link/ether 00:00:00:9e:ab:0d brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.8.9.3/24 brd 10.8.9.255 scope global net2
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe9e:ab0d/64 scope link 
       valid_lft forever preferred_lft forever
```

It seems to be no problem, but it still needs to be tested carefully.
Is this approach correct? If correct, can a more elegant API be designed to accomplish this? If not, how should this requirement be met?

Version: docker.io/kubeovn/kube-ovn:v1.12.11
