### ISSUE TITLE
[BUG] The Pod inside the user defined VPC cannot access public network via VPC GW

### ISSUE THREAD

**Issue by jcshare** [kubeovn/kube-ovn#4117]
### Kube-OVN Version

v.1.12.12

### Kubernetes Version

v1.30.1

### Operation-system/Kernel Version

root@master:~/project/kube-ovn# awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"Ubuntu 20.04.6 LTS"
root@master:~/project/kube-ovn# uname -ar
Linux master 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
root@master:~/project/kube-ovn#

### Description

configure a private VPC and found out the VPC GW doesn't works. the POD inside the VPC cannot access the public network

topology is below:

![vpc-gw-topo](https://github.com/kubeovn/kube-ovn/assets/70791398/e40f984e-7ab9-4679-82d4-b662165dd38d)

### Steps To Reproduce

exactly followed by this guide: https://kubeovn.github.io/docs/v1.12.x/guide/vpc/  to create my private VPC

### Current Behavior

 the POD inside the VPC cannot access the public network

### Expected Behavior

 the POD inside the VPC can access the public network successfully

**Comment by jcshare** [comment]
sorry for one mistake in the Topo picture: the NIC name on woker1 is "enp0s3" rather then "eth0".
I have doubled checked my private VPC configuration and it looks good.

**Comment by bobz965** [comment]
please make sure your config is following  the vpc-nat-gw doc

![image](https://github.com/kubeovn/kube-ovn/assets/7981158/e4d3e222-4de6-43e3-8c29-adc520741125)

**Comment by jcshare** [comment]
> please make sure your config is following the vpc-nat-gw doc
> 
> ![image](https://private-user-images.githubusercontent.com/7981158/337141801-e4d3e222-4de6-43e3-8c29-adc520741125.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTk1OTYsIm5iZiI6MTcxNzY1OTI5NiwicGF0aCI6Ii83OTgxMTU4LzMzNzE0MTgwMS1lNGQzZTIyMi00ZGU2LTQzZTMtOGMyOS1hZGM1MjA3NDExMjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMDczNDU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGEzYjE0YTVmZTIxMTdjZmEwZmJhNGJhYzRiNWE2MDMwZmIxNDRiYmIwYjNiYzRmYWFhZjRjZTJlZDRmYmNmMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iEVyUXu-NcJxJQFuszRIC3z4OdIkBW1TVVn3WQLFVsY)

thanks a lot, actually I have tried the way you mentioned, but it not work. 
my problem is that the VPC gateway cannot talk to the public network. even though the inside pod's traffic can be forwarded to the VPC GW.
is there any mis-configuration for my VPC GW?

**Comment by jcshare** [comment]
here are some debug information on my setup:

1.  The VPC GW cannot talk to the public GW(192.168.1.1)
```
root@master:~# kubectl exec -it vpc-nat-gw-gw-vpc-1-0 -n kube-system -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: net1@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether f2:33:a5:7a:ef:b1 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.16/24 brd 192.168.1.255 scope global net1
       valid_lft forever preferred_lft forever
    inet 192.168.1.19/24 scope global secondary net1
       valid_lft forever preferred_lft forever
    inet6 fe80::f033:a5ff:fe7a:efb1/64 scope link
       valid_lft forever preferred_lft forever
60: eth0@if61: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default
    link/ether 00:00:00:ec:4d:ac brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.0.1.254/24 brd 10.0.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:feec:4dac/64 scope link
       valid_lft forever preferred_lft forever
root@master:~# kubectl exec -it vpc-nat-gw-gw-vpc-1-0 -n kube-system -- ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
^C
--- 192.168.1.1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2049ms

command terminated with exit code 1
root@master:~# 
```

2. information on the worker node where the VPC GW running
```
root@worker2:~# ping 192.168.1.1
PING 192.168.1.1 (192.168.1.1) 56(84) bytes of data.
64 bytes from 192.168.1.1: icmp_seq=1 ttl=255 time=0.424 ms
root@worker2:~# crictl  ps
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID              POD
f866665134e89       bb285e82b00f9       23 hours ago        Running             vpc-nat-gw          0                   64d84dbae2657       vpc-nat-gw-gw-vpc-1-0
root@worker2:~# ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:e5:33:81 brd ff:ff:ff:ff:ff:ff
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 08:00:27:32:bd:b3 brd ff:ff:ff:ff:ff:ff
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:42:83:5f:a0:11 brd ff:ff:ff:ff:ff:ff
5: ovs-system: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether fa:57:04:7e:86:e4 brd ff:ff:ff:ff:ff:ff
6: br-int: <BROADCAST,MULTICAST> mtu 1400 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether 96:88:79:ba:43:a9 brd ff:ff:ff:ff:ff:ff
7: mirror0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether aa:29:9d:e5:6d:fc brd ff:ff:ff:ff:ff:ff
8: ovn0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 00:00:00:f1:80:2f brd ff:ff:ff:ff:ff:ff
9: genev_sys_6081: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 65000 qdisc noqueue master ovs-system state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 76:e9:4b:dd:fb:cf brd ff:ff:ff:ff:ff:ff
13: dbb26acce78d_h@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master ovs-system state UP mode DEFAULT group default qlen 1000
    link/ether f6:d3:94:1c:31:2a brd ff:ff:ff:ff:ff:ff link-netns cni-90326f82-9592-a612-9730-342ffac62914
15: c5c62d41acfd_h@if14: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master ovs-system state UP mode DEFAULT group default qlen 1000
    link/ether c2:6f:52:cc:6d:e8 brd ff:ff:ff:ff:ff:ff link-netns cni-2906e2c4-bbad-9018-a8d8-e797664284b0
61: 64d84dbae265_h@if60: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master ovs-system state UP mode DEFAULT group default qlen 1000
    link/ether ee:90:69:9c:ba:e0 brd ff:ff:ff:ff:ff:ff link-netns cni-99bfcd11-f3bf-59d1-e07a-e57ee1520987
65: 7563a725593e_h@if64: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master ovs-system state UP mode DEFAULT group default qlen 1000
    link/ether 4e:3e:f6:20:8b:b7 brd ff:ff:ff:ff:ff:ff link-netns cni-58c9debd-9768-1727-1ea8-1094219a2fc1
67: 12aec427a148_h@if66: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master ovs-system state UP mode DEFAULT group default qlen 1000
    link/ether 5a:b0:20:d2:06:11 brd ff:ff:ff:ff:ff:ff link-netns cni-adba48ea-ca9c-d453-38fb-05d492a341aa
69: 565bb6565251_h@if68: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master ovs-system state UP mode DEFAULT group default qlen 1000
    link/ether da:92:5f:53:6d:b9 brd ff:ff:ff:ff:ff:ff link-netns cni-f33681be-ba65-d472-5155-29d88d7e70e0
71: 01c436290cd6_h@if70: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master ovs-system state UP mode DEFAULT group default qlen 1000
    link/ether 06:db:ab:a1:39:ad brd ff:ff:ff:ff:ff:ff link-netns cni-376b214b-282b-02e8-8a36-cec889068a51
root@worker2:~# 
root@worker2:~# ip r
default via 192.168.1.1 dev enp0s3 proto static
10.16.0.0/16 via 100.64.0.1 dev ovn0
100.64.0.0/16 dev ovn0 proto kernel scope link src 100.64.0.4
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
192.168.1.0/24 dev enp0s3 proto kernel scope link src 192.168.1.222
192.168.1.0/24 dev enp0s8 proto kernel scope link src 192.168.1.118
root@worker2:~#

```

**Comment by jcshare** [comment]
I figured out the root cause:
need to configure"allow" for the Promiscuous mode of  the NIC on Virtualbox VM.
you guys may need to add one more item to the official VPC-NAT-GW doc:

```
For macvlan mode, the nic will send packets directly through that node NIC, relying on the underlying network devices for L2/L3 level forwarding capabilities. You need to configure the corresponding gateway, Vlan and security policy in the underlying network device in advance.
....
For Virturebox VM environments, the "Promiscuous Mode"  should be set to allow.
....
```

thanks a lot guys, the Kube-ovn is a very cool tool.

**Comment by bobz965** [comment]
please tcpdump the snat trafic flow inside the  vpc-nat-gw-gw-vpc-1 pod

**Comment by jcshare** [comment]
thanks a lot for the reply Bobz965. I have figured out the root cause:  the Promisous mode of the Nic on VirtualBox VM cannot get enabled  by click related button on VirtualBOX VM GUI,  it need to enable it via ip command("ip link set enp0s3 promisc on"). 

I'm not sure you guys have tried the VirtualBox VM yet. if not, then I would suggest to add one description in the official doc you mentioned above

thanks

**Comment by bobz965** [comment]
hi @jcshare , could you please help us post a PR on the official doc? thanks!

**Comment by jcshare** [comment]
sure, thanks

**Comment by reski-rukmantiyo** [comment]
Hi Guys, I also develop using the same use case but i'm using KIND.
In KIND i have control plan and several worker-node. 
How to achieve the same thing?

**Comment by bobz965** [comment]
> Hi Guys, I also develop using the same use case but i'm using KIND. In KIND i have control plan and several worker-node. How to achieve the same thing?

I think kind env may not support this.

**Comment by zhangzujian** [comment]
> Hi Guys, I also develop using the same use case but i'm using KIND. In KIND i have control plan and several worker-node. How to achieve the same thing?

```shell
kind get nodes | while read node; do docker network connect bridge $node; done
```

Then you can use eth1 in vpc-nat-gateway.

**Comment by zhangzujian** [comment]
Run `docker network inspect bridge` to get the external subnet CIDR and gateway, and add the container ip addresses into the subnet exclude IPs.

**Comment by reski-rukmantiyo** [comment]
Hi @zhangzujian , thanks for this. 
So these are the steps
1. kind get nodes
```
ubuntu@devspace-vm:~/operator/$ kind get nodes
kind-control-plane
kind-worker
```
2. docker network inspect bridge
```
ubuntu@devspace-vm:~/operator/$ docker network inspect bridge
[
    {
        "Name": "bridge",
        "Id": "ce6aac7125e0a06f4a133101d13832223ee5427bcf4cee8b0f096baef7b63fbb",
        "Created": "2024-06-28T03:45:20.665647314Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16",
                    "Gateway": "172.17.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "7b526e28ed713a39b8f4c8175f99d66fc719ef8df5364ffba372c9ebc8645293": {
                "Name": "kind-control-plane",
                "EndpointID": "4740b93f0f6e9862a735b533801c121ec6bbd5b13f4b057959657e7adf9a083b",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            },
            "d8d6b095e62abf5df37b630a3032d4de5c664928280125613b1ed8cc487d3038": {
                "Name": "kind-worker",
                "EndpointID": "2fb285b0e4177ddeade7cda7d85daf9e6a58edf171d564c5e42af1fd0aa5ec5e",
                "MacAddress": "02:42:ac:11:00:03",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]
```
I've seen  subnet 172.17.0.0/16 with gateway 172.17.0.1

3. Apply into subnet

```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 172.17.0.0/16
  gateway: 172.17.0.1  # IP address of the physical gateway
  excludeIps:
  - 172.17.0.1..172.17.0.50
 ```

4. Try again

```
ubuntu@devspace-vm:~/operator$ k exec -it pod/vpc1-pod -n ns1 -- ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8): 56 data bytes
^C
--- 8.8.8.8 ping statistics ---
3 packets transmitted, 0 packets received, 100% packet loss
command terminated with exit code 1
```

---
Additional configuration
```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-1
spec:
  namespaces:
  - ns1
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net1
spec:
  vpc: test-vpc-1
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  namespaces:
    - ns1
  excludeIps:
  - 10.0.1.1
  gateway: 10.0.1.1
  gatewayType: distributed
  natOutgoing: false
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ns1
  name: vpc1-pod
  labels:
    app: vpc1-pod
spec:
  containers:
    - name: vpc1-pod
      image: docker.io/library/nginx:alpine
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }'
---
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-nat-config
  namespace: kube-system
data:
  image: docker.io/kubeovn/vpc-nat-gateway:v1.12.18
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-nat-gw-config
  namespace: kube-system
data:
  enable-vpc-nat-gw: 'true'
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw1
spec:
  vpc: test-vpc-1
  subnet: net1
  lanIp: 10.0.1.254
  selector:
    - "kubernetes.io/hostname: kind-worker"
    - "kubernetes.io/os: linux"
  externalSubnets:
    - ovn-vpc-external-network
  ---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: eip-random
spec:
  natGwDp: gw1
  externalSubnet: ovn-vpc-external-network
---
kind: IptablesSnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: snat01
spec:
  eip: eips01
  internalCIDR: 10.0.1.0/24
```
