### ISSUE TITLE
[BUG] EIP 和 SNAT 配置，因网卡写错，导致节点离线，网络无法恢复，修改ConfigMap不行，删除ConfigMap也不行

### ISSUE THREAD

**Issue by yeshl** [kubeovn/kube-ovn#4165]
### Kube-OVN Version

v1.12.16

### Kubernetes Version

kubenetes 1.30, 按照文档EIP 和 SNAT 配置，因网卡写错，导致节点离线，网络无法恢复，修改ConfigMap不行，删除ConfigMap也不行，请问怎么解决？
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
#  type: "centrailized"
  enable-external-gw: "false"
  external-gw-nodes: "node50"
  external-gw-nic: "bond0"  #应该写外网网卡eno4，错写成主网卡导致节点离线了
  external-gw-addr: "1.2.3.1/24"
  nic-ip: "1.2.3.40/24"
  nic-mac: "16:52:f3:13:6a:25"
```

### Operation-system/Kernel Version

"Debian GNU/Linux 12 (bookworm)"

### Description

节点离线，网络无法恢复

### Steps To Reproduce

kubectl ko nbctl show|grep 'router ' -A 10
router a3672bc3-0802-431f-9975-be7b6e08abd4 (ovn-cluster)
    port ovn-cluster-external
        mac: "16:52:f3:13:6a:25"
        networks: ["1.2.3.40/24"]
        gateway chassis: [f3404e61-7378-4ada-b1ed-40e9d2691e36]
    port ovn-cluster-join
        mac: "00:00:00:20:82:34"
        networks: ["100.64.0.1/16"]
    port ovn-cluster-ovn-default
        mac: "00:00:00:DA:71:D4"
        networks: ["10.16.0.1/16"]

### Current Behavior

node50    NotReady   <none>          49d   v1.30.0

### Expected Behavior

delete
