### ISSUE TITLE
[BUG] NatGateway ceases working after being restarted

### ISSUE THREAD

**Issue by SkalaNetworks** [kubeovn/kube-ovn#4193]
### Kube-OVN Version

v1.13.0 and v1.12.x

### Kubernetes Version

v1.28.3 on k0s
Kube-proxy in IPVS mode (iptables seemed to make kube-ovn not work correctly)

### Operation-system/Kernel Version

Debian GNU/Linux 12 (bookworm)
6.1.0-18-amd64

### Description

The NatGateway ceases to ingress any traffic after being restarted. Pods using the NatGateway lose external connectivity.

### Steps To Reproduce

1. Deploy the following YAML on the cluster with kube-ovn installed and multus installed
```yaml
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-2
spec:
  staticRoutes:
    - cidr: 0.0.0.0/0
      nextHopIP: 10.0.1.70
      policy: policyDst
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net2
spec:
  vpc: test-vpc-2
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw1
spec:
  vpc: test-vpc-2
  subnet: net2
  lanIp: 10.0.1.70
  selector:
    - "kubernetes.io/os: linux"
  externalSubnets:
    - ovn-vpc-external-network
---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: eip-static
spec:
  natGwDp: gw1
---
kind: IptablesSnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: snat01
spec:
  eip: eip-static
  internalCIDR: 10.0.1.0/24
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: net2
  namespace: ns2
  name: vpc1-pod
spec:
  containers:
    - name: vpc1-pod
      image: docker.io/library/nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: net2
  namespace: ns2
  name: vpc2-pod
spec:
  containers:
    - name: vpc2-pod
      image: docker.io/library/nginx:alpine
```

2. Ping 1.1.1.1 from the GW
![image](https://github.com/kubeovn/kube-ovn/assets/127797154/a022068b-d4d0-42a1-97ed-3797eb1b5a7b)

3. Ping 1.1.1.1 from one of the 2 pods
![image](https://github.com/kubeovn/kube-ovn/assets/127797154/cbb5f2b7-3a9e-44c1-9cae-7bb5640e19dc)

4. Observe (tcpdump) the traffic on the gateway while pinging
![image](https://github.com/kubeovn/kube-ovn/assets/127797154/6cea21af-cd1a-4b2c-a577-b0545ffc4283)

5. Delete the nat-gateway pod and wait for the STS to Terminate and then Restart the pod
Pinging continues to work while the pod is Terminating (as expected)

6. Observe the ping stop on the pod that was running it within the VPC

7. Observe the tcpdump on the gateway
![image](https://github.com/kubeovn/kube-ovn/assets/127797154/00f24357-a02a-400b-bfe1-35990fb5ff23)
No response is received
Pinging 1.1.1.1 from the gateway directly still works

8. SSH to the K8S node hosting the gateway pod and run a tcpdump
![image](https://github.com/kubeovn/kube-ovn/assets/127797154/1e0f1a04-f58c-4d7c-a2ff-6d891a72f31d)

9. Wait a variable amount of time (10 minutes? sometimes 1 hour?) and rerun the ping from one of the test pods
![image](https://github.com/kubeovn/kube-ovn/assets/127797154/8517433b-4250-4d12-8dc4-21138910d46f)

10. Look at the (normal) traffic on the node hosting the gateway
![image](https://github.com/kubeovn/kube-ovn/assets/127797154/4c5c4362-f42c-4dfc-ba0f-0135eb86d008)

### Current Behavior

The NatGateway ceases to work for random amounts of time (sometimes indefinitely) when restarted.
Deleting everything (subnet, vpc, pods, gateway...) doesn't always fix the problem.

My tests are done WITHOUT the gateway moving from one node to another on restart (it's pinned to a node)

### Expected Behavior

Restarting the pod leads to a connection downtime equal to the downtime of the pod.
