### ISSUE TITLE
外网网关配置，无法ping通EIP

### ISSUE THREAD

**Issue by yeshl** [kubeovn/kube-ovn#4207]
### Kube-OVN Version

1.12.16

### Kubernetes Version

1.30

### Operation-system/Kernel Version

debian12

### Description

外网网关配置，无法ping通EIP，步骤按文档配置：https://kubeovn.github.io/docs/stable/advance/ovn-eip-fip-snat/#31-ovn-snat-subnet-cidr

### Steps To Reproduce

```
#1. kube-ovn-controller 启动参数需要配置：
          - --external-gateway-vlanid=204
          - --external-gateway-switch=external204

# 2. kube-ovn-cni 启动参数需要配置:
          - --external-gateway-switch=external204 

root@master20:~# kubectl -n kube-system get deploy/kube-ovn-controller -oyaml|grep gateway 
        - --default-gateway=10.16.0.1
        - --default-gateway-check=true
        - --default-logical-gateway=false
        - --external-gateway-vlanid=204
        - --external-gateway-switch=external204
        
root@master20:~# kubectl -n kube-system get ds/kube-ovn-cni -oyaml|grep external
        - --external-gateway-switch=external204
        
# 准备 provider-network， vlan， subnet
# cat 01-provider-network.yaml
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: external204
spec:
  defaultInterface: vlan
---
# cat 02-vlan.yaml
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan204
spec:
  id: 204
  provider: external204
---
# cat 03-vlan-subnet.yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: external204
spec:
  protocol: IPv4
  cidrBlock: 10.5.204.0/24
  gateway: 10.5.204.254
  vlan: vlan204
  excludeIps:
    - 10.5.204.1..10.5.204.100
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  external-gw-nodes: "node51.host"
  type: "centralized"
  external-gw-nic: "eno4" # 用于接入 ovs 公网网桥的网卡
  external-gw-addr: "10.5.204.254/24" # underlay 物理网关的 ip
---
# cat 00-ns.yml
apiVersion: v1
kind: Namespace
metadata:
  name: vpc1
---
# cat 01-vpc-ecmp-enable-external-bfd.yml
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc1
spec:
  namespaces:
    - vpc1
  enableExternal: true
# vpc 启用 enableExternal 会自动创建 lrp 关联到上述指定的公网
---
# cat 02-subnet.yml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc1-subnet1
spec:
  cidrBlock: 192.168.0.0/24
  default: false
  disableGatewayCheck: false
  disableInterConnection: true
  enableEcmp: true
  gatewayNode: ""
  gatewayType: distributed
  #gatewayType: centralized
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: vpc1
  namespaces:
    - vpc1

apiVersion: v1
kind: Pod
metadata:
  name: vpc-1-busybox01
  namespace: vpc1
spec:
  containers:
    - name: snat-pod
      imagePullPolicy: IfNotPresent
      image: docker.io/library/busybox:1.36.1
      command: [ "/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait" ]

root@master20:~# kubectl get po -o wide -n vpc1 vpc-1-busybox01
NAME              READY   STATUS    RESTARTS   AGE   IP            NODE          NOMINATED NODE   READINESS GATES
vpc-1-busybox01   1/1     Running   0          10s   192.168.0.2   node30.host   <none>           <none>

root@master20:~# kubectl get ip vpc-1-busybox01.vpc1
NAME                   V4IP          V6IP   MAC                 NODE          SUBNET
vpc-1-busybox01.vpc1   192.168.0.2          66:0b:61:23:bd:08   node30.host   vpc1-subnet1

---
kind: OvnEip
apiVersion: kubeovn.io/v1
metadata:
  name: eip-static
spec:
  externalSubnet: external204
  type: nat
---
kind: OvnFip
apiVersion: kubeovn.io/v1
metadata:
  name: eip-static
spec:
  ovnEip: eip-static
  ipName: vpc-1-busybox01.vpc1

root@master20:~# kubectl  get ofip
NAME         VPC    V4EIP          V4IP          READY   IPTYPE   IPNAME
eip-static   vpc1   10.5.204.103   192.168.0.2   true             vpc-1-busybox01.vpc1
root@master20:~# ping 10.5.204.101
PING 10.5.204.101 (10.5.204.101) 56(84) bytes of data.
文档中这里可以ping通，我测试ping不通

root@master20:~# kubectl ko nbctl show vpc1
router 14c37150-b405-4d38-8264-f6f0f1de60ef (vpc1)
    port vpc1-external204
        mac: "3e:ca:57:0f:dd:56"
        networks: ["10.5.204.102/24"]
        gateway chassis: [cd1f1f72-69aa-4e92-85ef-d7b7b0e074e0]
    port vpc1-vpc1-subnet1
        mac: "de:e2:48:4c:2e:fa"
        networks: ["192.168.0.1/24"]
    nat 05089518-1a25-4693-bddb-dc8e494492a8
        external ip: "10.5.204.103"
        logical ip: "192.168.0.2"
        type: "dnat_and_snat"
root@master20:~# kubectl ko nbctl lr-route-list vpc1
IPv4 Routes
Route Table <main>:
                0.0.0.0/0              10.5.204.254 dst-ip
root@master20:~# kk s external204
switch 78d8b48f-244a-4022-bcdc-0d32134dd280 (external204)
    port external204-ovn-cluster
        type: router
        router-port: ovn-cluster-external204
    port localnet.external204
        type: localnet
        tag: 204
        addresses: ["unknown"]
    port external204-vpc1
        type: router
        router-port: vpc1-external204
root@master20:~# kk s ovn-cluster
router 58c4b73d-d310-480d-8b23-f838b864ebea (ovn-cluster)
    port ovn-cluster-ovn-default
        mac: "d2:be:5f:c4:28:f0"
        networks: ["10.16.0.1/16"]
    port ovn-cluster-join
        mac: "76:cb:3c:f6:92:aa"
        networks: ["100.64.0.1/16"]
    port ovn-cluster-external204
        mac: "fa:d9:13:cc:ff:d4"
        networks: ["10.5.204.101/24"]
        gateway chassis: [cd1f1f72-69aa-4e92-85ef-d7b7b0e074e0]
root@master20:~# kk s vpc1-subnet1
switch fda16ae0-93a5-4daf-9eff-8ea5f5a5f6f5 (vpc1-subnet1)
    port vpc-1-busybox01.vpc1
        addresses: ["66:0b:61:23:bd:08 192.168.0.2"]
    port vpc1-subnet1-vpc1
        type: router
        router-port: vpc1-vpc1-subnet1
```

### Current Behavior

外网网关配置，无法ping通EIP

### Expected Behavior

 ping  pod 的公网 ip 是能通
