### ISSUE TITLE
[BUG] Custom VPC-DNS not working at VM (kubevirt)

### ISSUE THREAD

**Issue by reski-rukmantiyo** [kubeovn/kube-ovn#4250]
### Kube-OVN Version

v1.12.12

### Kubernetes Version

Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.0

### Operation-system/Kernel Version

"Ubuntu 22.04.4 LTS"
5.15.0-113-generic

### Description

Right now, I can create isolated workload in Pod by using Subnet, VPC and Nat Gateway.
And thru [VPC-DNS](https://kubeovn.github.io/docs/stable/en/guide/vpc/#custom-vpc-dns), my pod can reach domain name.

But somehow in KubeVirt VM, there are two problems
- Route: somehow route cannot go to 10.0.1.254 automatically, i have to add somekind of route inside the vm thru cloud-init (solveable)
- DNS : somehow in the vm cannot reach vpc-dns. In my case cannot reach dns pod 

### Steps To Reproduce

1. Create Kubevirt VM using script in [Config VPC](https://kubeovn.github.io/docs/stable/en/guide/vpc/#custom-vpc-dns)
2. Cannot check for DNS 

### Current Behavior

Default DNS not working inside VM. 

```
ubuntu@devspace-vm:~/dekagpu-installation/$ k get svc -o wide -A|grep dns
kube-system   kube-dns                      ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   43h   k8s-app=kube-dns
kube-system   slr-vpc-dns-dns-net1-ns1      ClusterIP   None             <none>        53/UDP,53/TCP,9153/TCP   42h   k8s-app=vpc-dns-dns-net1-ns1
```

When I try to solve from existing VM

```
ubuntu@ubuntu:~$ resolvectl status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp1s0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.96.0.10
       DNS Servers: 10.96.0.10
        DNS Domain: cluster.local devspace.svc.cluster.local
                    ns1.svc.cluster.local svc.cluster.local
```

DNS already correct but somehow cannot reach DNS server

```
ubuntu@ubuntu:~$ ping 10.96.0.10
PING 10.96.0.10 (10.96.0.10) 56(84) bytes of data.
^C
--- 10.96.0.10 ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1018ms

ubuntu@ubuntu:~$ telnet 10.96.0.10 53
Trying 10.96.0.10...
telnet: Unable to connect to remote host: No route to host
ubuntu@ubuntu:~$ 
```

### Expected Behavior

DNS should be working, maybe I missed something

**Comment by zhangzujian** [comment]
There are two mistakes:

1. 10.96.0.10 is a service ip, you should never ping a service ip to check if the service is reachable;
2. You should use the vpc-dns vip defined in configmap vpc-dns-config, not 10.96.0.10.

**Comment by zhangzujian** [comment]
You should use another ip address, e.g. 10.96.0.3.

**Comment by reski-rukmantiyo** [comment]
my DNS at 10.96.0.10 ...my current ServiceIP for CoreDNS

```
ubuntu@ubuntu:~$ resolvectl status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp1s0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.96.0.10
       DNS Servers: 10.96.0.10
        DNS Domain: cluster.local devspace.svc.cluster.local
                    ns1.svc.cluster.local svc.cluster.local
```

If i change into 10.96.0.5,

```
##
# coredns-vip is the IP address of the CoreDNS service.
# IP can be changes
##

apiVersion: v1
kind: ConfigMap
metadata:
  name: vpc-dns-config
  namespace: kube-system
data:
  coredns-vip: 10.96.0.5
  enable-vpc-dns: "true"
  nad-name: ovn-nad
  nad-provider: ovn-nad.default.ovn
```

No response...
```
ubuntu@devspace-vm:~/dekagpu-installation/$ k exec -it pod/vpc1-pod -n ns1 -- ping www.google.com
ping: bad address 'www.google.com'
command terminated with exit code 1
```

**Comment by bobz965** [comment]
how about nc -u -zv 10.96.0.5 53 ？

**Comment by reski-rukmantiyo** [comment]
This is my result

```
ubuntu@devspace-vm:~/dekagpu-installation/$ k exec -it pod/vpc1-pod -n ns1 -- nc -u -zv 10.96.0.5 53
10.96.0.5 (10.96.0.5:53) open
ubuntu@devspace-vm:~/dekagpu-installation/$ k exec -it pod/vpc1-pod -n ns1 -- ping www.google.com
ping: bad address 'www.google.com'
command terminated with exit code 1
```

and my config

```
##
# coredns-vip is the IP address of the CoreDNS service.
# IP can be changes
##

apiVersion: v1
kind: ConfigMap
metadata:
  name: vpc-dns-config
  namespace: kube-system
data:
  coredns-vip: 10.96.0.5
  enable-vpc-dns: "true"
  nad-name: ovn-nad
  nad-provider: ovn-nad.default.ovn
```

**Comment by zhangzujian** [comment]
Please check whether the vpc dns works:

```shell
k exec -it pod/vpc1-pod -n ns1 -- nslookup kubernetes.default.svc.cluster.local. 10.96.0.5
```

If it works for vpc pods but does not work for the vpc vm, the problem may be related to kubevirt. Check your route in the vm:

```shell
ip route get 10.96.0.5
nc -v -z -w1 10.96.0.5 54
```

**Comment by reski-rukmantiyo** [comment]
Hi @zhangzujian 

This is my config
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: vpc-dns-config
  namespace: kube-system
data:
  coredns-vip: 10.96.0.5
  enable-vpc-dns: "true"
  nad-name: ovn-nad
  nad-provider: ovn-nad.default.ovn
```

Results

```
ubuntu@ubuntu:~$ ubuntu@devspace-vm:~/dekagpu-installation/$ k exec -it pod/vpc1-pod -n ns1 -- nslookup kubernetes.default.svc.cluster.local. 10.96.0.5
Server:         10.96.0.5
Address:        10.96.0.5:53

** server can't find kubernetes.default.svc.cluster.local.: REFUSED

** server can't find kubernetes.default.svc.cluster.local.: REFUSED

command terminated with exit code 1
```

in VM

```
ubuntu@ubuntu:~$ ip route get 10.96.0.5
RTNETLINK answers: Network is unreachable

ubuntu@ubuntu:~$ ip route get 10.96.0.10
10.96.0.10 dev enp1s0 src 10.0.1.19 uid 1000 
    cache 
```

and

```
ubuntu@ubuntu:~$ nc -v -z -w1 10.96.0.10 54
nc: connect to 10.96.0.10 port 54 (tcp) timed out: Operation now in progress

ubuntu@ubuntu:~$ nc -v -z -w1 10.96.0.5 54
nc: connect to 10.96.0.5 port 54 (tcp) failed: Network is unreachable
```

**Comment by zhangzujian** [comment]
> ubuntu@ubuntu:~$ ip route get 10.96.0.5
RTNETLINK answers: Network is unreachable

Check routes in the VM by:

```shell
ip addr show
ip route show
```

**Comment by zhangzujian** [comment]
> nc -v -z -w1 10.96.0.10 54

The port should be 53.

Did you change the dns vip in the vpc-dns-config? If so, please try to turn off the vpc dns and enable it again.

**Comment by zhangzujian** [comment]
Run the following command to check ovn status:

```shell
kubectl ko nbctl lr-route-list vpc1
kubectl ko nbctl ls-lb-list <vpc-subnet-name>
kubectl ko trace ns1/vpc1-pod 10.96.0.5 udp 53
```

**Comment by reski-rukmantiyo** [comment]
Hi @zhangzujian 

after i figure out, is that 
1. Kubevirt VM is not getting default route that has been change into 10.0.1.254

After I change/add default gateway
```
ubuntu@ubuntu:~$ ip route show
default via 10.0.1.254 dev enp1s0 
10.0.1.0/24 dev enp1s0 proto kernel scope link src 10.0.1.19 metric 100 
10.96.0.10 dev enp1s0 proto dhcp scope link src 10.0.1.19 metric 100 
```

3. Default of dns still goes to coredns pod, instead of vpc-dns

Default from dhcp4
```
ubuntu@ubuntu:~$ resolvectl status
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp1s0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 10.96.0.10
       DNS Servers: 10.96.0.10
        DNS Domain: cluster.local devspace.svc.cluster.local
                    ns1.svc.cluster.local svc.cluster.local
```

After changed 2 of these, DNS in kubevirt working well.
But the next question, is it possible to make it as default value (VIP of VPC-DNS) for dhcp4 ?

Thanks

**Comment by reski-rukmantiyo** [comment]
I try to create another namespace and recreate the same use case, but somehow, default dns resolve for pod still the same coredns ip (10.96.0.10), instead of vpc-dns ip (10.96.0.5)

Here's the script

```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc3
spec:
  namespaces:
  - ns3
  staticRoutes:
  - cidr: 0.0.0.0/0
    nextHopIP: 10.0.3.254
    policy: policyDst
  - cidr: 0.0.0.0/0
    nextHopIP: 10.0.3.254
    policy: policySrc
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: subnet3
spec:
  vpc: vpc3
  cidrBlock: 10.0.3.0/24
  protocol: IPv4
  namespaces:
    - ns3
  excludeIps:
  - 10.0.3.1
  gateway: 10.0.3.1
  gatewayType: distributed
  natOutgoing: false
  provider: ovn-nad.default.ovn
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw3
spec:
  vpc: vpc3
  subnet: subnet3
  lanIp: 10.0.3.254
  selector:
    - "kubernetes.io/hostname: kind-worker"
    - "kubernetes.io/os: linux"
  externalSubnets:
    - ovn-vpc-external-network
   ---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: eip-ns3-1
spec:
  natGwDp: gw3
---

kind: IptablesSnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: snat-ns3-01
spec:
  eip: eip-ns3-1
  internalCIDR: 10.0.3.0/24
---
kind: VpcDns
apiVersion: kubeovn.io/v1
metadata:
  name: dns-net3-ns3
spec:
  vpc: vpc3
  subnet: subnet3
```

Everything already ok, but somehow ping to domain still failed

```
ubuntu@devspace-vm:~/dekagpu-installation/samples/diff-gw-3$ k exec -it pod/vpc3-pod -n ns3 -- nslookup kubernetes.default.svc.cluster.local 10.96.0.5
Server:         10.96.0.5
Address:        10.96.0.5:53

Name:   kubernetes.default.svc.cluster.local
Address: 10.96.0.1


ubuntu@devspace-vm:~/dekagpu-installation/samples/diff-gw-3$ k exec -it pod/vpc3-pod -n ns3 -- cat /etc/resolv.conf 
search ns3.svc.cluster.local svc.cluster.local cluster.local devspace.svc.cluster.local
nameserver 10.96.0.10
options ndots:5

ubuntu@devspace-vm:~/dekagpu-installation/samples/diff-gw-3$ k exec -it pod/vpc3-pod -n ns3 -- nc -v -z -w1 10.96.0.5 53
10.96.0.5 (10.96.0.5:53) open
```
