### ISSUE TITLE
VPC Gateway loses connectivity as soon as an EIP gets attached to it

### ISSUE THREAD

**Issue by tgdfool2** [kubeovn/kube-ovn#4259]
### Kube-OVN Version

v1.12.18

### Kubernetes Version

Client Version: v1.28.10
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.10

### Operation-system/Kernel Version

Ubuntu 22.04.4 LTS
6.5.0-1023-azure

kubespray cluster deployed to an Azure VM.

### Description

Dear community,

We would like to add multi-tenancy capability to our kubespray Kubernetes cluster deployed to Azure using VPC Gateways. Deployment of the gateways seems to work as expected, until an EIP gets created and assigned to the Gateway. Starting from this point in time, the Gateway loses all its connectivity.

Could you please help us to find and fix the issue?

Thanks in advance for your support!

### Steps To Reproduce

1. Create the following resources:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: test-ovn
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-ovn-vpc
spec:
  namespaces:
  - test-ovn
  staticRoutes:
  - cidr: 0.0.0.0/0
    nextHopIP: 100.105.0.1
    policy: policyDst
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: test-ovn-internal-subnet
spec:
  vpc: test-ovn-vpc
  cidrBlock: 100.105.0.0/16
  protocol: IPv4
  namespaces:
    - test-ovn
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 10.1.0.0/24  # Azure subnet
  gateway: 10.1.0.1  # IP address of the Azure gateway in the subnet
  excludeIps:
  - 10.1.0.1..10.1.0.10
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "eth0",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }'
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-nat-config
  namespace: kube-system
data:
  image: docker.io/kubeovn/vpc-nat-gateway:v1.12.18
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-nat-gw-config
  namespace: kube-system
data:
  enable-vpc-nat-gw: 'true'
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: test-ovn-gw
spec:
  vpc: test-ovn-vpc
  subnet: test-ovn-internal-subnet
  lanIp: 100.105.0.1
  selector:
    - "kubernetes.io/os: linux"
  externalSubnets:
    - ovn-vpc-external-network
```

2. Gateway Pod gets created, with two interfaces, as expected:
```
vpc-nat-gw-test-ovn-gw-0:/kube-ovn# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host proto kernel_lo
       valid_lft forever preferred_lft forever
2: net1@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/ether 00:22:48:87:55:e8 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.1.0.12/24 brd 10.1.0.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::22:4800:187:55e8/64 scope link proto kernel_ll
       valid_lft forever preferred_lft forever
275: eth0@if276: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default
    link/ether 96:36:c5:38:1c:32 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 100.105.0.1/16 brd 100.105.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::9436:c5ff:fe38:1c32/64 scope link proto kernel_ll
       valid_lft forever preferred_lft forever
```

3. Gateway Pod can reach other VMs in the VNet:
```
vpc-nat-gw-test-ovn-gw-0:/kube-ovn# ping 10.1.0.4
PING 10.1.0.4 (10.1.0.4) 56(84) bytes of data.
64 bytes from 10.1.0.4: icmp_seq=1 ttl=64 time=1.17 ms
64 bytes from 10.1.0.4: icmp_seq=2 ttl=64 time=1.31 ms
From 10.1.0.6: icmp_seq=2 Redirect Host(New nexthop: 10.1.0.4)
From 10.1.0.6: icmp_seq=3 Redirect Host(New nexthop: 10.1.0.4)
64 bytes from 10.1.0.4: icmp_seq=3 ttl=64 time=1.07 ms
From 10.1.0.6: icmp_seq=4 Redirect Host(New nexthop: 10.1.0.4)
64 bytes from 10.1.0.4: icmp_seq=4 ttl=64 time=1.18 ms
From 10.1.0.6: icmp_seq=5 Redirect Host(New nexthop: 10.1.0.4)
64 bytes from 10.1.0.4: icmp_seq=5 ttl=64 time=1.19 ms
From 10.1.0.6: icmp_seq=6 Redirect Host(New nexthop: 10.1.0.4)
64 bytes from 10.1.0.4: icmp_seq=6 ttl=64 time=1.64 ms
64 bytes from 10.1.0.4: icmp_seq=7 ttl=64 time=1.78 ms
From 10.1.0.6: icmp_seq=8 Redirect Host(New nexthop: 10.1.0.4)
64 bytes from 10.1.0.4: icmp_seq=8 ttl=64 time=1.15 ms
64 bytes from 10.1.0.4: icmp_seq=9 ttl=64 time=1.41 ms
64 bytes from 10.1.0.4: icmp_seq=10 ttl=64 time=1.22 ms
From 10.1.0.6: icmp_seq=11 Redirect Host(New nexthop: 10.1.0.4)
64 bytes from 10.1.0.4: icmp_seq=11 ttl=64 time=1.11 ms
64 bytes from 10.1.0.4: icmp_seq=12 ttl=64 time=1.60 ms
64 bytes from 10.1.0.4: icmp_seq=13 ttl=64 time=1.13 ms
64 bytes from 10.1.0.4: icmp_seq=14 ttl=64 time=1.77 ms
64 bytes from 10.1.0.4: icmp_seq=15 ttl=64 time=1.59 ms
64 bytes from 10.1.0.4: icmp_seq=16 ttl=64 time=1.31 ms
```

4. Create an EIP and assign it to the the Gateway:
```
---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: test-ovn-outgoing-ip
spec:
  natGwDp: test-ovn-gw
  externalSubnet: ovn-vpc-external-network
```

4. As soon as the EIP gets created and assigned to the the Gateway, all the traffic gets dropped:
```
vpc-nat-gw-test-ovn-gw-0:/kube-ovn# ping 10.1.0.4
From 10.1.0.12 icmp_seq=4054 Destination Host Unreachable
From 10.1.0.12 icmp_seq=4054 Destination Host Unreachable
From 10.1.0.12 icmp_seq=4054 Destination Host Unreachable
```

### Current Behavior

As soon as an EIP gets created and assigned to the the Gateway, all the traffic gets dropped.

### Expected Behavior

EIP gets and assigned to the the Gateway. Traffic continues to flow as previously. EIP can be used to create SNAT rules.
