### ISSUE TITLE
Issue with SwitchLBRule and DNAT for connectivity from external to service within VPC

### ISSUE THREAD

**Issue by tgdfool2** [kubeovn/kube-ovn#4279]
### Kube-OVN Version

v1.12.18

### Kubernetes Version

Client Version: v1.28.10
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.10

### Operation-system/Kernel Version

Ubuntu 22.04.4 LTS
6.5.0-1023-azure

kubespray cluster deployed to an Azure VM.

### Description

Dear Community,

I am trying to create a DNAT rule to allow external connections to reach Pods created by a deployment within a VPC. According to the docs (and other older issues, e.g. https://github.com/kubeovn/kube-ovn/issues/3130 or https://github.com/kubeovn/kube-ovn/issues/2636), I created a `Vip`, a `SwitchLBRule`, an `EIP` as well as a `DnatRule`, but still did not manage to connect to the service from outside.

_(My base setup is the one described under https://github.com/kubeovn/kube-ovn/issues/4259#issue-2392733349)_

Some questions to help me troubleshooting this issue:
1. Is the `Vip` resource necessary or not? There is no mention of it under https://kubeovn.github.io/docs/stable/en/advance/vpc-internal-lb/, but only under https://kubeovn.github.io/docs/stable/en/advance/vip/
2. Am I supposed to use an IP from `the service-cluster-ip-range` as `Vip`, or can it also be an IP from the internal VPC range? I initially tried with the internal VPC range, but I was even not able to access the VIP from within the VPC, so I switched to an IP from the `service-cluster-ip-range`
3. Based off https://github.com/kubeovn/kube-ovn/issues/2636, I understand that I may be missing some routes, but I don't really know which ones
4. I am currently using `Iptables-*`-based resources, but I have also seen documentation about `Ovn-*`-based resources (https://kubeovn.github.io/docs/stable/en/advance/ovn-eip-fip-snat/#4-ovn-dnat), so not sure which ones to use

I would be happy to provide further details if needed.

Thanks in advance for your help!

### Steps To Reproduce

**Please note**:
* I'm running `kubespray` with `service-cluster-ip-range: "10.233.0.0/18"`
* My base setup is the one described under https://github.com/kubeovn/kube-ovn/issues/4259#issue-2392733349

**Steps**:
1. Create the following resources:
```
---
apiVersion: kubeovn.io/v1
kind: Vip
metadata:
  name: test-ovn-arp-proxy-vip-lb-http
spec:
  namespace: test-ovn
  subnet: test-ovn-internal-subnet
  v4ip: 10.233.0.237
  type: switch_lb_vip
---
apiVersion: kubeovn.io/v1
kind: SwitchLBRule
metadata:
  name: test-ovn-incoming-lb-http
spec:
  vip: 10.233.0.237
  sessionAffinity: ClientIP
  namespace: test-ovn
  selector:
    - app:nginx
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: test-ovn-incoming-ip-http
spec:
  natGwDp: test-ovn-gw
  v4ip: 10.1.0.200
  externalSubnet: ovn-vpc-external-network
---
kind: IptablesDnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: test-ovn-incoming-dnat-http
spec:
  eip: test-ovn-incoming-ip-http
  externalPort: '80'
  internalIp: 10.233.0.237
  internalPort: '80'
  protocol: tcp
```

2. Try to access the service from outside:
```
$ curl -v http://10.1.0.200
*   Trying 10.1.0.200:80...
* connect to 10.1.0.200 port 80 failed: Connection timed out
* Failed to connect to 10.1.0.200 port 80 after 134683 ms: Connection timed out
* Closing connection 0
curl: (28) Failed to connect to 10.1.0.200 port 80 after 134683 ms: Connection timed out
```

3. Access from a Pod within the VPC is working, through Service IP:
```
$ curl http://10.233.0.237
Welcome to nginx!
```

### Current Behavior

Access to VIP within a VPC through VPC Gateway / DNAT not working

### Expected Behavior

Access working :-)

**Comment by bobz965** [comment]
about this case:
how about using loadbalancer instead of `SwitchLBRule and DNAT`? 
 @hongzhen-ma @tgdfool2

**Comment by tgdfool2** [comment]
> about this case: how about using loadbalancer instead of `SwitchLBRule and DNAT`? @hongzhen-ma @tgdfool2

Any example of such a config?

**Comment by tgdfool2** [comment]
@bobz965: you mean this I assume? https://kube-ovn.readthedocs.io/zh-cn/latest/en/guide/loadbalancer-service/

The issue is that it only supports services in the default VPC. In our case, we would have several VPCs on our cluster, and all of them would have services that need to reachable.

So maybe you have an idea on how to make DNAT rules to work? You mentioned some missing routes, but how can I find which ones?

**Comment by bobz965** [comment]
> @bobz965: you mean this I assume? https://kube-ovn.readthedocs.io/zh-cn/latest/en/guide/loadbalancer-service/

yes.

@hongzhen-ma can this lb support  custom vpc?

**Comment by tgdfool2** [comment]
In the end, this would be the setup that we would like to achieve:
<img width="1249" alt="image" src="https://github.com/kubeovn/kube-ovn/assets/66017789/db1b7dbd-139b-4459-9fb5-30bd9cca0661">

Would be great if you could give us some hints on how to achieve this :-)

Thanks in advance for your support!

**Comment by tgdfool2** [comment]
Other question: is this expected that the NAT Gateway is not able to ping the Pods in the same VPC?

In my picture above, from the NAT Gateway:
* Ping works to 100.105.1.100 (its own IP)
* Ping doesn't work to 100.105.1.4 and 100.105.1.5 (IPs of other Pods in the VPC/Namespace)

Just wondering if this is by design or if something is wrong...

**Comment by tgdfool2** [comment]
Regarding the missing routes with the `SwitchLBRule` setup, I did some further investigation, but sill with no luck. Here is my current setup:
<img width="689" alt="image" src="https://github.com/user-attachments/assets/2b5d439d-d19e-4573-bd8e-3c301d39e3bd">

With this setup:
1. Access from all Pods, including VPC Gateway to Nginx Pod (100.105.0.2:80) is working
2. Access from Test Pod Alpine (100.105.0.3) to `SwitchLBRule` VIP (10.96.0.237) is working
3. Access from VPC Gateway to `SwitchLBRule` VIP (10.96.0.237) is **NOT** working

Remarks:
* Route table of the VPC Gateway:
  ```
  Kernel IP routing table
  Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
  0.0.0.0         172.18.0.1      0.0.0.0         UG    0      0        0 net1
  10.96.0.0       100.105.0.1     255.240.0.0     UG    0      0        0 eth0
  100.105.0.0     0.0.0.0         255.255.0.0     U     0      0        0 eth0
  172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 net1
  ```
* Currently no static route configured on the VPC

My assumption is, prior to configure the DNAT rule to allow external connections to the `SwitchLBRule` VIP, we need to ensure that the VPC Gateway can access the VIP. Is this correct? If so, then what I am missing to get this connection to work?

Thanks in advance for your support!

**Comment by bobz965** [comment]
you can try use lb svc， if have any bug. please post .

I think it could be used in custom vpc.

**Comment by bobz965** [comment]
Using switch lb rule with nat gw is much more complex than LB service.

**Comment by tgdfool2** [comment]
Thanks. Will give a try and let you know the outcome.

**Comment by tgdfool2** [comment]
@bobz965

The following `Service` has been deployed:
```
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    lb-svc-attachment.kube-system.kubernetes.io/logical_switch: ovn-vpc-external-network
    ovn.kubernetes.io/attachmentprovider: ovn-vpc-external-network.kube-system
  name: test-clearml-ttr-svc
  namespace: test-clearml
spec:
  loadBalancerIP: 10.1.0.200
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
```

Which resulted in the following error in the controller Pod:
```
W0712 12:56:28.091566       7 service.go:495] pod for lb svc test-ovn/test-ovn-ttr-svc is not running: pod of deployment test-ovn/lb-svc-test-ovn-ttr-svc not found
I0712 12:56:29.190111       7 service_lb.go:311] add eip rules for lb svc pod, [10.1.0.200/24,10.1.0.1]
E0712 12:56:32.295601       7 service_lb.go:271] failed to ExecuteCommandInContainer, errOutput: failed to exec command "arping -c 3 -s 10.1.0.200 10.1.0.1"
E0712 12:56:32.295834       7 service_lb.go:276] command terminated with exit code 1
E0712 12:56:32.295854       7 service_lb.go:313] failed to add eip for pod, err: command terminated with exit code 1
E0712 12:56:32.295868       7 service.go:529] failed to update pod attachment network for service test-ovn/test-ovn-ttr-svc: command terminated with exit code 1
E0712 12:56:32.295942       7 service.go:166] error syncing 'test-ovn/test-ovn-ttr-svc': command terminated with exit code 1, requeuing
```

Could this be related to the fact that this infrastructure is running in Azure, with `ipvlan` and not `macvlan`? Do you see a way to overcome this?
