### ISSUE TITLE
[BUG] MTU Setting at subnet level is not working

### ISSUE THREAD

**Issue by nics90** [kubeovn/kube-ovn#4303]
### Kube-OVN Version

v1.12.3

### Kubernetes Version

v1.24.17

### Operation-system/Kernel Version

awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"Ubuntu 22.04.2 LTS"

### Description

# uname -r
5.15.0-67-generic

### Steps To Reproduce

1. Check the MTU on the default interface of Kubernetes node :
```
eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu **8900** qdisc mq state UP group default qlen 1000
    link/ether 00:00:00:b4:af:16 brd ff:ff:ff:ff:ff:ff
    inet 10.67.89.2/24 metric 100 brd 10.67.89.255 scope global dynamic eth0
       valid_lft 86293150sec preferred_lft 86293150sec
    inet6 fe80::200:ff:feb4:af16/64 scope link
       valid_lft forever preferred_lft forever
```
Note: In my case it's set to 8900 on host node

2. Create a Subnet with any CIDR:
```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeovn.io/v1","kind":"Subnet","metadata":{"annotations":{},"name":"test"},"spec":{"cidrBlock":"10.40.50.0/24","excludeIps":["10.40.50.1"],"gateway":"10.40.50.1","gatewayType":"distributed","namespaces":["test"],"natOutgoing":true,"protocol":"IPv4","routeTable":""}}
  name: test
spec:
  cidrBlock: 10.40.50.0/24
  default: false
  enableLb: true
  excludeIps:
  - 10.40.50.1
  gateway: 10.40.50.1
  gatewayNode: ""
  gatewayType: distributed
  namespaces:
  - test
  natOutgoing: true
  private: false
  protocol: IPv4
  provider: ovn
  vpc: ovn-cluster
```

3. Create a Pod with the above subnet 

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: test
  labels:
    run: test
  name: test
  namespace: test
spec:
  containers:
  - image: docker.io/library/nginx:alpine
    imagePullPolicy: IfNotPresent
    name: test
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-4jlsg
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cloudlyte-server1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-4jlsg
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace

```

4. Exec into pod to check MTU on the interface of Pod:

```
kubectl get po -n test -o wide
NAME   READY   STATUS    RESTARTS   AGE     IP           NODE                NOMINATED NODE   READINESS GATES
test   1/1     Running   0          8m58s   10.40.50.4   server1   <none>  

# kubectl exec -it pod/test -n test -- sh

/ # ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
192: eth0@if193: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu **8800** qdisc noqueue state UP
    link/ether 00:00:00:5c:bc:28 brd ff:ff:ff:ff:ff:ff
    inet 10.40.50.4/24 brd 10.40.50.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe5c:bc28/64 scope link
       valid_lft forever preferred_lft forever
/ #
```
Note: The MTU set is expected one : Node MTU - 100 , here 8900 - 100 = 8800

6. Edit the same subnet and set any MTU value:

```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubeovn.io/v1","kind":"Subnet","metadata":{"annotations":{},"name":"test"},"spec":{"cidrBlock":"10.40.50.0/24","excludeIps":["10.40.50.1"],"gateway":"10.40.50.1","gatewayType":"distributed","namespaces":["test"],"natOutgoing":true,"protocol":"IPv4","routeTable":""}}
  name: test
spec:
  cidrBlock: 10.40.50.0/24
  default: false
  enableLb: true
  excludeIps:
  - 10.40.50.1
  gateway: 10.40.50.1
  gatewayNode: ""
  gatewayType: distributed
  **mtu: 5000**
  namespaces:
  - test
  natOutgoing: true
  private: false
  protocol: IPv4
  provider: ovn
  vpc: ovn-cluster
```
7. Recreate Pod with same subnet and exec into it to check MTU on the interface:

```
kubectl get po -n test -o wide
NAME   READY   STATUS    RESTARTS   AGE   IP           NODE                NOMINATED NODE   READINESS GATES
test   1/1     Running   0          6s    10.40.50.7    server1   <none>           <none>

kubectl exec -it pod/test -n test -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
198: eth0@if199: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu **8800** qdisc noqueue state UP
    link/ether 00:00:00:5d:2c:76 brd ff:ff:ff:ff:ff:ff
    inet 10.40.50.7/24 brd 10.40.50.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::200:ff:fe5d:2c76/64 scope link
       valid_lft forever preferred_lft forever

```

Note: MTU value should be set to 5000 here but it's being set to 8800 still.

### Current Behavior

MTU value being set on subnet level is not reflecting on Pods

### Expected Behavior

MTU value should reflect inside Pods and work as expected.
