### ISSUE TITLE
[BUG] VPC NatGateway not working

### ISSUE THREAD

**Issue by CiraciNicolo** [kubeovn/kube-ovn#4314]
### Kube-OVN Version

v1.12.19

### Kubernetes Version

v1.29.6

### Operation-system/Kernel Version

"Ubuntu 22.04.4 LTS"
5.15.0-116-generic

### Description

Similar as #4241 I'm unable to use VPC NAT GW to have pods in a VPC reach internet.  Below you can find my custom configuration

### Steps To Reproduce

K8s vanilla cluster, with 3 API nodes + 2 Worker Nodes + 1 Worker node for NATGW. 
KubeOVN is installed with Cilium in chain mode.

Below configuration files:

```
---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: alpha-vpc
spec:
  namespaces:
    - alpha
  staticRoutes:
    - cidr: 0.0.0.0/0
      nextHopIP: 10.100.0.254
      policy: policyDst
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: alpha-default-subnet
spec:
  vpc: alpha-vpc
  cidrBlock: 10.100.0.0/16
  protocol: IPv4
  natOutgoing: true
  namespaces:
    - alpha
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: alpha-vpc-external-network
spec:
  protocol: IPv4
  provider: alpha-vpc-external-network.kube-system
  cidrBlock: 100.126.254.0/24
  gateway: 100.126.254.1
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: alpha-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens19",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "alpha-vpc-external-network.kube-system"
      }
    }'
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: alpha-vpc-nat-gateway
spec:
  vpc: alpha-vpc
  subnet: alpha-default-subnet
  lanIp: 10.100.0.254
  selector:
  - "node-role.kubernetes.io/vpc-gw: true"
  tolerations:
    - key: "elmec.com/vpc-gw"
      operator: "Exists"
      effect: "NoExecute"
  externalSubnets:
    - alpha-vpc-external-network
---
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: alpha-vpc-eip
spec:
  natGwDp: alpha-vpc-nat-gateway
  externalSubnet: alpha-vpc-external-network
---
kind: IptablesSnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: alpha-vpc-snat
spec:
  eip: alpha-vpc-eip
  internalCIDR: 10.100.0.0/16
```

`ens19` is the nic on the gw dedicated node with 100.126.254.0/24 subnet attached.

### Current Behavior

No ping to 1.1.1.1 in a pod into VPC:
```kubectl exec -itn alpha dnsutils -- bash
root@dnsutils:/# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
^C
--- 1.1.1.1 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2046ms
```

Ping works in vpc-nat-gw:
```
kubectl exec -itn kube-system vpc-nat-gw-alpha-vpc-nat-gateway-0 -- sh
Defaulted container "vpc-nat-gw" out of: vpc-nat-gw, vpc-nat-gw-init (init)
/kube-ovn # ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=58 time=2.68 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=58 time=2.84 ms
^C
--- 1.1.1.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1002ms
rtt min/avg/max/mdev = 2.684/2.760/2.836/0.076 ms
```

### Expected Behavior

Ping and other nw commands should work
