### ISSUE TITLE
[Feature Request] Use pod as subnet gateway

### ISSUE THREAD

**Issue by zsxsoft** [kubeovn/kube-ovn#4315]
### Description

Consider the following scenario:

The cluster can only access the public network. There is an OpenVPN server on the public network that allows connection to the enterprise's internal network.
Currently, the common solution is to deploy a Sidecar Container for any Pod that needs to connect to the internal network. However, by default, an OpenVPN client can only have one connection. If multiple Pods need to access the server, sidecar container cannot solve this problem.

Therefore, one possible solution is to deploy an OpenVPN Pod and modify the VPC's policy routing to allow the specified subnet/pod/ip to access the internal network through this Pod. 

The problem is, if the subnet that needs to access the internal network / the VPN pod frequently changes, maintaining the policy routing could become challenging(It's array not a map, cannot easily patch). In the `ovn-cluster` VPC, due to the presence of policy routes, static routing + routing table seems ineffective.

Hence, I would like to propose adding a new field, `gatewayIp` or `gatewayPod`, based on the Subnet's `gatewayType: centralized`. The current `gatewayNode` field and `gatewayType: distributed `are only suitable for scenarios where the gateway is outside the cluster, they suffer from performance issues when forwarding to the cluster's internal network. 

I hope this can be taken into consideration.

**Comment by bobz965** [comment]
I made a openvpn solution based on kube-ovn，could you please try this project？ https://github.com/kubecombo/kube-combo

**Comment by bobz965** [comment]
In my opinion, I think fip:vip is a good choice. no need to handle the vpc routes details.

**Comment by zsxsoft** [comment]
@bobz965 
I think FIP/VIP is better. `kube-combo` can't meet my needs, I don't have underlay/eip/fip environment.

**Comment by bobz965** [comment]
is your `OpenVPN server` inside the kube-ovn vpc ?

**Comment by zsxsoft** [comment]
No, server is in external

**Comment by bobz965** [comment]
you can try set up a openvpn client gw pod in the ovn-cluster vpc, and set ovn-cluster vpc spec policy based routes to dest cidr via the openvpn client gw pod.

**Comment by zsxsoft** [comment]
Yes I did that. 

My point is, if the subnet that needs to access the internal network / the VPN pod frequently changes, maintaining the policy routing could become challenging(It's array not a map, cannot easily patch).

**Comment by bobz965** [comment]
the internal network / the VPN pod frequently changes, but you can keep the openvpn client gw pod use the static IP.
policy routing controls the traffic via the gw pod.

pod --> gw-openvpn-client-pod -->OpenVPN server

policy routing only controls: pod --> gw-openvpn-client-pod

**Comment by zsxsoft** [comment]
For example

```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-1
spec:
  policyRoutes:
    - action: reroute
      match: ip4.src==10.0.1.0/24
      nextHopIP: 10.0.1.252
      priority: 10
```

Add a new subnet:

```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-1
spec:
  policyRoutes:
    - action: reroute
      match: ip4.src==10.0.1.0/24 || ip4.src == 10.0.2.0/24 || ip4.src == 10.0.3.0/24
      nextHopIP: 10.0.1.252
      priority: 10
```
It's hard to maintain. 


And this

```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: test-vpc-1
spec:
  policyRoutes:
    - action: reroute
      match: ip4.src==10.0.1.0/24 
      nextHopIP: 10.0.1.252
      priority: 10
    - action: reroute
      match: ip4.src==10.0.2.0/24 
      nextHopIP: 10.0.1.252
      priority: 10
    - action: reroute
      match: ip4.src==10.0.2.0/24 
      nextHopIP: 10.0.1.252
      priority: 10
```

It's easy to add(`PATCH {"path": "/spec/policyRoutes/-", op:  "add"}`) but hard to delete (need a mutex, then loop to get all policyRoutes to find the index, then delete)
