### ISSUE TITLE
[BUG] TPROXY fails to add iptables rules if probe use a named port

### ISSUE THREAD

**Issue by CiraciNicolo** [kubeovn/kube-ovn#4331]
### Kube-OVN Version

v1.12.19

### Kubernetes Version

v.1.9.6

### Operation-system/Kernel Version

"Ubuntu 22.04.4 LTS"
5.15.0-116-generic

### Description

The TPROXY feature is failing if a probe is using a named port instead of a port number

### Steps To Reproduce

1. Deploy an application with a liveness probe with the following syntax:
```
livenessProbe:
  httpGet:
    port: http-healthz
    path: /livez
    scheme: HTTP
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 15
  successThreshold: 1
  failureThreshold: 8
```
This example is taken from cert-manager

### Current Behavior

The probe fails and the tproxy logs reports the following error:
```
 exit status 2: iptables v1.8.7 (nf_tables): invalid port/service `http-healthz' specified
```

### Expected Behavior

Probes should works. TPROXY should not use the port name but should try to infer the port number from the ports definition. Furthermore TPROXY just stop working and no further proxies are applied in the node.

### Current workaround

Edit the deployment and use the port number
