### ISSUE TITLE
[BUG] Performance about NetworkPolicy

### ISSUE THREAD

**Issue by zsxsoft** [kubeovn/kube-ovn#4349]
### Kube-OVN Version

v1.12.19

### Kubernetes Version

v1.27.4

### Operation-system/Kernel Version

TencentOS Server 4.0
6.6.6-2401.0.1.tl4.4.x86_64

### Description

I have a cluster with 4 nodes, ~100 subnets, ~200 pods. I've found that my pods often take more than 10 minutes to obtain a DHCP lease. Therefore, I've been debugging this issue.

My `kube-ovn-controller.log` looks like:
```
I0729 00:42:15.706804       7 network_policy.go:430] UpdateNp Egress, allows is [same 2001 ips here with different order], excepts is [], log false
I0729 00:42:24.415878       7 network_policy.go:430] UpdateNp Egress, allows is [same 2001 ips here with different order], excepts is [], log false
I0729 00:42:37.562676       7 network_policy.go:430] UpdateNp Egress, allows is [same 2001 ips here with different order], excepts is [], log false
I0729 00:42:47.649768       7 network_policy.go:430] UpdateNp Egress, allows is [same 2001 ips here with different order], excepts is [], log false
I0729 00:43:05.396868       7 network_policy.go:430] UpdateNp Egress, allows is [same 2001 ips here with different order], excepts is [], log false
I0729 00:43:14.578186       7 network_policy.go:430] UpdateNp Egress, allows is [same 2001 ips here with different order], excepts is [], log false
I0729 00:43:25.556697       7 network_policy.go:430] UpdateNp Egress, allows is [same 2001 ips here with different order], excepts is [], log false
... ~100 lines later
E0729 00:51:30.973962       7 ovn-nb-acl.go:604] more than one acl with same 'parent np.net.xxxx.vm direction from-lport priority 2000 match inport == @np.net.xxxxx.vm && ip'
E0729 00:51:30.973999       7 network_policy.go:501] failed to set egress acl log for np vm/np-net-xxxxx, more than one acl with same 'parent np.net.xxxxx.vm direction from-lport priority 2000 match inport == @np.net.xxxxx.vm && ip'
I0729 00:51:33.956182       7 network_policy.go:142] handle add/update network policy vm/np-net-xxxxx
```

My dashboard "Work Queue Depth" is look like this
<img width="1900" alt="image" src="https://github.com/user-attachments/assets/b906d2c2-ff20-4f66-aa91-8658287aa8dd">

So I think my problem is about networkpolicy.

I have ~100 network policies, one is special:
```yaml
apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: egress-allow-internet-and-some-pod
  spec:
    egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
          - 10.0.0.0/8
    - to:
      - podSelector:
          matchLabels:
            allow-ingress: "true"
    policyTypes:
    - Egress
```

Others(>=100) look like this, to make pods in the same subnet can connect to each other:
```yaml
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: np-net-SUBNET-A
    namespace: vm
  spec:
    egress:
    - to:
      - podSelector:
          matchLabels:
            net-SUBNET-A: "1"
    podSelector:
      matchLabels:
        net-SUBNET-A: "1"
    policyTypes:
    - Egress
```

This seems to indicate that there are some performance issues with the NetworkPolicy under this configuration. I haven't confirmed this yet, nor have I constructed a minimal reproduction environment.

I'm attempting to use `SecurityGroup` as a replacement, hoping this could help.

### Steps To Reproduce

/

### Current Behavior

/

### Expected Behavior

/

**Comment by zsxsoft** [comment]
```bash
kubectl ko nbctl acl-list egress.allow.internet.and.some.pod.vm
from-lport  2001 (inport == @egress.allow.internet.and.some.pod.vm && ip && ip4.dst == $egress.allow.internet.and.some.pod.vm.egress.allow.IPv4.0 && ip4.dst != $egress.allow.internet.and.some.pod.vm.egress.except.IPv4.0) allow-related [after-lb]
from-lport  2001 (inport == @egress.allow.internet.and.some.pod.vm && ip && ip4.dst == $egress.allow.internet.and.some.pod.vm.egress.allow.IPv4.0 && ip4.dst != $egress.allow.internet.and.some.pod.vm.egress.except.IPv4.0) allow-related [after-lb]
from-lport  2001 (inport == @egress.allow.internet.and.some.pod.vm && ip && ip4.dst == $egress.allow.internet.and.some.pod.vm.egress.allow.IPv4.0 && ip4.dst != $egress.allow.internet.and.some.pod.vm.egress.except.IPv4.0) allow-related [after-lb]
from-lport  2001 (inport == @egress.allow.internet.and.some.pod.vm && ip && ip4.dst == $egress.allow.internet.and.some.pod.vm.egress.allow.IPv4.0 && ip4.dst != $egress.allow.internet.and.some.pod.vm.egress.except.IPv4.0) allow-related [after-lb]
from-lport  2001 (inport == @egress.allow.internet.and.some.pod.vm && ip && ip4.dst == $egress.allow.internet.and.some.pod.vm.egress.allow.IPv4.0 && ip4.dst != $egress.allow.internet.and.some.pod.vm.egress.except.IPv4.0) allow-related [after-lb]
from-lport  2001 (inport == @egress.allow.internet.and.some.pod.vm && ip && ip4.dst == $egress.allow.internet.and.some.pod.vm.egress.allow.IPv4.0 && ip4.dst != $egress.allow.internet.and.some.pod.vm.egress.except.IPv4.0) allow-related [after-lb]
from-lport  2001 (inport == @egress.allow.internet.and.some.pod.vm && ip && ip4.dst == $egress.allow.internet.and.some.pod.vm.egress.allow.IPv4.0 && ip4.dst != $egress.allow.internet.and.some.pod.vm.egress.except.IPv4.0) allow-related [after-lb]
from-lport  2001 (inport == @egress.allow.internet.and.some.pod.vm && ip && ip4.dst == $egress.allow.internet.and.some.pod.vm.egress.allow.IPv4.0 && ip4.dst != $egress.allow.internet.and.some.pod.vm.egress.except.IPv4.0) allow-related [after-lb]
from-lport  2001 (ip4.dst == 10.144.182.1) allow-stateless [after-lb]
from-lport  2001 (ip4.dst == 10.18.134.1) allow-stateless [after-lb]
from-lport  2001 (ip4.dst == 10.182.50.1) allow-stateless [after-lb]
from-lport  2001 (ip4.dst == 10.19.6.1) allow-stateless [after-lb]
from-lport  2001 (ip4.dst == 10.67.142.1) allow-stateless [after-lb]
from-lport  2001 (ip4.dst == 10.70.72.1) allow-stateless [after-lb]
from-lport  2001 (ip4.dst == 10.75.178.1) allow-stateless [after-lb]
from-lport  2001 (ip4.dst == 172.21.0.1) allow-stateless [after-lb]
from-lport  2000 (inport == @egress.allow.internet.and.some.pod.vm && ip) drop [after-lb]
from-lport  2000 (inport == @egress.allow.internet.and.some.pod.vm && ip) drop [after-lb]
from-lport  2000 (inport == @egress.allow.internet.and.some.pod.vm && ip) drop [after-lb]
from-lport  2000 (inport == @egress.allow.internet.and.some.pod.vm && ip) drop [after-lb]
from-lport  2000 (inport == @egress.allow.internet.and.some.pod.vm && ip) drop [after-lb]
from-lport  2000 (inport == @egress.allow.internet.and.some.pod.vm && ip) drop [after-lb]
from-lport  2000 (inport == @egress.allow.internet.and.some.pod.vm && ip) drop [after-lb]
from-lport  2000 (inport == @egress.allow.internet.and.some.pod.vm && ip) drop [after-lb]
  to-lport  2001 (ip4.src == 10.144.182.1) allow-stateless
  to-lport  2001 (ip4.src == 10.18.134.1) allow-stateless
  to-lport  2001 (ip4.src == 10.182.50.1) allow-stateless
  to-lport  2001 (ip4.src == 10.19.6.1) allow-stateless
  to-lport  2001 (ip4.src == 10.67.142.1) allow-stateless
  to-lport  2001 (ip4.src == 10.70.72.1) allow-stateless
  to-lport  2001 (ip4.src == 10.75.178.1) allow-stateless
  to-lport  2001 (ip4.src == 172.21.0.1) allow-stateless
```

**Comment by hongzhen-ma** [comment]
1、The first log shows that there's sth wrong with the  netpol vm/np-net-xxxxx.  Is it possible to provide the content about netpol vm/np-net-xxxxx?
2、Is it convenient to provide the complete log file of kube-ovn-controller? The log file exists in directory /var/log/kube-ovn on the node where the kube-ovn-controller pod is located.

**Comment by zsxsoft** [comment]
`np-net-xxx` is `np-net-subnet-a` attached in the main thread.

```yaml
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: np-net-SUBNET-A
    namespace: vm
  spec:
    egress:
    - to:
      - podSelector:
          matchLabels:
            net-SUBNET-A: "1"
    podSelector:
      matchLabels:
        net-SUBNET-A: "1"
    policyTypes:
    - Egress
 ```
