### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by zhangyan1022** [kubeovn/kube-ovn#4353]
### Description

我根据kube-ovn文档配置vpc网关
# 1. 第一步：enable vpc网关：
![image](https://github.com/user-attachments/assets/f135ed06-1888-4fc9-b69f-430e8dcfeb05)

# 2. 第二步：配置外部网络
```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 10.10.6.1/24
  gateway: 10.10.6.1  # IP address of the physical gateway
  excludeIps:
  - 10.10.6.0..10.10.6.10
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "eno8403",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }'
```
# 3. 第三步：创建vpc
```
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc-x
spec:
  staticRoutes:
    - cidr: 0.0.0.0/0
      nextHopIP: 10.0.1.254
      policy: policyDst
  namespaces:
  - vpcw
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: vpcx-net1
spec:
  vpc: vpc-x
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  namespaces:
    - vpcw

```
# 4. 第四步：创建网关pod
```
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: gw1
  namespace: vpcw
spec:
  vpc: vpc-x
  subnet: vpcx-net1
  lanIp: 10.0.1.254
  selector:
    - "kubernetes.io/hostname: kube-ovn-worker"
    - "kubernetes.io/os: linux"
  externalSubnets:
    - ovn-vpc-external-network

```
# 5. 第五步：创建nat规则
```
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: eipd01
spec:
  natGwDp: gw1
  externalSubnet: ovn-vpc-external-network
---
kind: IptablesDnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: dnat01
spec:
  eip: eipd01
  externalPort: '8888'
  internalIp: 10.0.1.10
  internalPort: '80'
  protocol: tcp
---
kind: IptablesSnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: snat01
spec:
  eip: eips01
  internalCIDR: 10.0.1.0/24
```
# 6. 第六步：创建测试pod
------------------------------------------------
整体网络如下显示
![image](https://github.com/user-attachments/assets/67560693-a01e-4aea-91b7-c19a96cc465b)

# 7. 发现的问题
上述配置完开始测试。
在gw网关中ping 10.0.1.1可以平通
在gw网关中ping 外部网络 可以ping通

gw网关和测试pod相互无法ping通。
