### ISSUE TITLE
[BUG] slr无法正常使用

### ISSUE THREAD

**Issue by yanruogu** [kubeovn/kube-ovn#4376]
### Kube-OVN Version

v1.12.19

### Kubernetes Version

v1.28.10

### Operation-system/Kernel Version

ubuntu22.04/5.15.0-60-generic

### Description

通过slr创建的vip在自定义vpc内无法连通

### Steps To Reproduce

1. 创建vpc：
```yaml
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: tenant-vpc-1
spec:
  namespaces:
  - tenant-1
  staticRoutes:
    - cidr: 0.0.0.0/0
      nextHopIP: 10.17.0.254
      policy: policyDst
```
3. 创建subnet：
```yaml
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: tenant-subnet-1
spec:
  vpc: tenant-vpc-1
  cidrBlock: 10.17.0.0/24
  gateway: 10.17.0.254
  protocol: IPv4
  namespaces:
    - tenant-1
```
5. 创建外部网络： 
```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-vpc-external-network
spec:
  protocol: IPv4
  provider: ovn-vpc-external-network.kube-system
  cidrBlock: 10.200.4.0/24
  gateway: 10.200.4.254  # IP address of the physical gateway
  excludeIps:
  - 10.200.4.1..10.200.4.200
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-vpc-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "bond0",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "ovn-vpc-external-network.kube-system"
      }
    }'
```
7. 创建vpc网关： 
```yaml
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: tenant-gateway-1
spec:
  vpc: tenant-vpc-1
  subnet: tenant-subnet-1
  lanIp: 10.17.0.254
  selector:
    - "kube-ovn-gateway: true"
  externalSubnets:
    - ovn-vpc-external-network
```
9. 创建pod：
```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: tenant-1
  name: tenant-vpc-pod-1
  labels:
    app: tenant-vpc-pod-1
spec:
  containers:
    - name: tenant-vpc-pod-1
      image: registry.cn-zhangjiakou.aliyuncs.com/breezey/nginx:1.25.2
```

11. 基于slr为pod创建service：
```yaml
apiVersion: kubeovn.io/v1
kind: SwitchLBRule
metadata:
  name:  cjh-slr-nginx
  namespace: tenant-1
spec:
  vip: 1.1.1.1
  sessionAffinity: ClientIP
  namespace: tenant-1
  selector:
    - "app:tenant-vpc-pod-1"
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
```

验证：
``` 
root@yichang-10-200-4-40:~/vpc# kubectl get slr -n tenant-1
NAME            VIP       PORT(S)   SERVICE                      AGE
cjh-slr-nginx   1.1.1.1   80/TCP    tenant-1/slr-cjh-slr-nginx   6m6s
```

查看svc：
```
root@yichang-10-200-4-40:~/vpc# kubectl get svc  -n tenant-1
NAME                TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
slr-cjh-slr-nginx   ClusterIP   None         <none>        80/TCP    4m49s
```

查看svc详情： 
```
Name:              slr-cjh-slr-nginx
Namespace:         tenant-1
Labels:            <none>
Annotations:       ovn.kubernetes.io/switch_lb_vip: 1.1.1.1
                   ovn.kubernetes.io/vpc: tenant-vpc-1
Selector:          app=tenant-vpc-pod-1
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                None
IPs:               None
Port:              http  80/TCP
TargetPort:        80/TCP
Endpoints:         10.17.0.3:80
Session Affinity:  ClientIP
Events:            <none>
```

查看对应podip：
```
root@yichang-10-200-4-40:~/vpc# kubectl get pods -n tenant-1  -o wide 
NAME               READY   STATUS              RESTARTS   AGE     IP          NODE                  NOMINATED NODE   READINESS GATES
tenant-vpc-pod-1   1/1     Running             0          14m     10.17.0.3   yichang-10-200-4-19   <none>           <none>
```

在同一vpc中再启动一个pod：
```yaml
apiVersion: v1
kind: Pod
metadata:
  namespace: tenant-1
  name: test-2
  labels:
    app: test-2
spec:
  containers:
    - name: test-2
      image: registry.cn-zhangjiakou.aliyuncs.com/breezey/nginx:1.25.2
```
下面懒得贴配置了，大致的结论： 
我在这个新启动的pod中，直接curl tenant-vpc-pod-1 这个pod的地址，也就是10.17.0.3，是可以访问的，curl 1.1.1.1这个地址，会直接返回： 
curl: (28) Failed to connect to 1.1.1.1 port 80 after 3042 ms: Connection timed out

以上是在vpc内的访问，如果在宿主机节点上直接curl 1.1.1.1，也会返回同样的结果

### Current Behavior

这里面有几个问题： 
1. 凭什么slr可以随便给个ip？
2. 这个slr的随便的这个Ip是怎么在外部能访问到的？ 
3. 现在很明显，这个slr的ip在外部根本访问不到，什么原因？ 

### Expected Behavior

期望能解决上面几个问题
