### ISSUE TITLE
[BUG] 自定义路由不生效

### ISSUE THREAD

**Issue by ch3nku1** [kubeovn/kube-ovn#4418]
### Kube-OVN Version

v1.12.11

### Kubernetes Version

v1.26.9

### Operation-system/Kernel Version

Ubuntu 22.04.1 LTS/5.15.0-67-generic

### Description

自定义路由不生效

### Steps To Reproduce

```
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vlan4009
spec:
  protocol: IPv4
  provider: vlan4009.default
  cidrBlock: 172.31.0.0/17

---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan4009
  namespace: default
spec:
  config: '{
     "cniVersion": "0.3.1",
     "name": "vlan4009",
     "type": "macvlan",
     "mode": "bridge",
     "master": "br0.4009",
     "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "vlan4009.default"
      }
     }'

---
apiVersion: v1
kind: Pod
metadata:
  name: custom-routes
  annotations:
    k8s.v1.cni.cncf.io/networks: default/vlan4009
    ovn.kubernetes.io/routes: |
      [{
        "dst": "192.168.0.101/24",
        "gw": "10.16.0.1"
      }, {
        "dst": "172.31.128.0/17",
        "gw": "172.31.0.1"
      }]
spec:
  containers:
  - name: nginx
    image: docker.io/library/nginx:alpine
```

### Current Behavior

pod 内路由
/ # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.16.0.1       0.0.0.0         UG    0      0        0 eth0
10.16.0.0       0.0.0.0         255.255.0.0     U     0      0        0 eth0
172.31.0.0      0.0.0.0         255.255.128.0   U     0      0        0 net1
192.168.0.0     10.16.0.1       255.255.255.0   UG    0      0        0 eth0

### Expected Behavior

pod 内路由
/ # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.16.0.1       0.0.0.0         UG    0      0        0 eth0
10.16.0.0       0.0.0.0         255.255.0.0     U     0      0        0 eth0
172.31.0.0      0.0.0.0         255.255.128.0   U     0      0        0 net1
**172.31.128.0     172.31.0.1         255.255.128.0   U     0      0        0 net1**
192.168.0.0     10.16.0.1       255.255.255.0   UG    0      0        0 eth0

**Comment by zhangzujian** [comment]
你用法不对。试试这样配置：

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: custom-routes
  annotations:
    k8s.v1.cni.cncf.io/networks: default/vlan4009
    ovn.kubernetes.io/routes: |
      [{
        "dst": "192.168.0.101/24",
        "gw": "10.16.0.1"
      }]
    vlan4009.default.ovn.kubernetes.io/routes: |
      [{
        "dst": "172.31.128.0/17",
        "gw": "172.31.0.1"
      }]
```
