### ISSUE TITLE
Could I use same subnet in different namespace?

### ISSUE THREAD

**Issue by Icedroid** [kubeovn/kube-ovn#442]
I test vlan mod for kube-ovn, I create different namespace and subnet with different, but with same subnet. But after create pod It return error.

A vlan and subnet created as follow:
```
---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan100
spec:
  vlanId: 100
---
apiVersion: v1
kind: Namespace
metadata:
  name: test100
  labels:
    name: vlan100
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-test-vlan100
spec:
  cidrBlock: 10.0.0.0/24
  default: false
  gateway: 10.0.0.1
  natOutgoing: true
  private: true
  vlan: vlan100
  namespaces:
    - test100
```

Anther different vlan and same subnet created as follow:
```
---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan101
spec:
  vlanId: 101
---
apiVersion: v1
kind: Namespace
metadata:
  name: test101
  labels:
    name: vlan101
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ovn-test-vlan101
spec:
  cidrBlock: 10.0.0.0/24
  default: false
  gateway: 10.0.0.1
  natOutgoing: true
  private: true
  vlan: vlan101
  namespaces:
    - test101
```
