### ISSUE TITLE
[Feature Request] Load Balancing Pods within a Custom VPC and Accessing from External Networks

### ISSUE THREAD

**Issue by MuNeNICK** [kubeovn/kube-ovn#4421]
### Kube-OVN Version
v1.12.19

### Kubernetes Version
Client Version: v1.30.2+k3s1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.2+k3s1

### Description

Dear Community,

I would like to request a feature to enable load balancing of Pods within a custom VPC using OVN and allowing external access to them.
https://kubeovn.github.io/docs/stable/en/advance/ovn-eip-fip-snat/

When creating a Deployment resource within a custom VPC and setting multiple replicas, I understand that the Pod that can be specified via EIP or DNAT is just one of the replicated Pods.

I attempted to use SwitchLBRule and expose its VIP with ofip, but this approach failed.
Such as the following Issue #3130 

Additionally, I have not tested the SVC LB because the documentation mentions that it does not support custom VPCs.
https://kubeovn.github.io/docs/stable/en/guide/loadbalancer-service/

> Currently, it only supports configuration in the default VPC. Support for LoadBalancers in custom VPCs can be referred to in the VPC configuration.

As it stands, is it correct that load balancing Pods within a custom VPC and accessing them externally is not possible?
Are there any plans to implement this functionality?

Thank you.

**Comment by bobz965** [comment]
In OVN design: I think OVN router LB Rule is the best choice, which is used to provide ovn dnat.

and, kube-ovn also have a loadbalancer service feature, which is provided in the same way like `vpc nat gw pod`. I think you can try.


` SwitchLBRule and expose its VIP with ofip` is too complicated, using OVN router LB just like `ovn dnat` is much more simple.

**Comment by MuNeNICK** [comment]
@bobz965 
Thank you for your reply. 

If I understand correctly, by using OVN-DNAT, it's possible to expose Pods within the VPC to the outside while performing load balancing.

I tried the following, but it only routed to one Pod, and I couldn't connect to the other Pod.
I accessed from multiple devices, browsers, and IPs, but ` podinfo-6f48b78c46-4vfzz` is always displayed.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: vpc1
  labels:
    app: podinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:6.1.5
        ports:
        - containerPort: 9898
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
```

```
kind: OvnEip
apiVersion: kubeovn.io/v1
metadata:
  name: eip-dnat
spec:
  externalSubnet: external
  type: nat
---
kind: OvnDnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: eip-dnat1
spec:
  ovnEip: eip-dnat
  ipName: podinfo-6f48b78c46-4vfzz.vpc1
  protocol: tcp
  internalPort: "9898"
  externalPort: "9898"
---
kind: OvnDnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: eip-dnat2
spec:
  ovnEip: eip-dnat
  ipName: podinfo-6f48b78c46-57qvn.vpc1
  protocol: tcp
  internalPort: "9898"
  externalPort: "9898"
```

```
mniadmin@master01:~/test-lb$ kubectl get odnat
NAME        VPC    EIP        PROTOCOL   V4EIP             V4IP        INTERNALPORT   EXTERNALPORT   IPNAME                          READY
eip-dnat1   vpc1   eip-dnat   tcp        192.168.115.109   10.0.1.11   9898           9898           podinfo-6f48b78c46-4vfzz.vpc1   true
eip-dnat2   vpc1   eip-dnat   tcp        192.168.115.109   10.0.1.10   9898           9898           podinfo-6f48b78c46-57qvn.vpc1   true
```



If I'm doing something wrong, I would appreciate it if you could let me know.
