### ISSUE TITLE
[BUG] Hairpin traffic is not working for VMs and `externalTrafficPolicy: Local`

### ISSUE THREAD

**Issue by kvaps** [kubeovn/kube-ovn#4457]
### Kube-OVN Version

v1.12.19

### Kubernetes Version

v1.30.0

### Operation-system/Kernel Version

```
OS-IMAGE         KERNEL-VERSION
Talos (v1.7.1)   6.6.29-talos  
```

### Description

Hi, I use kube-ovn with cilium with kube-proxy replacement in chaining mode.

I have three nodes: `srv1`, `srv2`, `srv3`

I have two nginx-ingress-controller pods running on `srv1` and `srv2`

I have LoadBalancer service for nginx-ingress-controller with `externalTrafficPolicy: Local`. This service have two IPs:

```
NAME                       TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
nginx-ingress-controller   LoadBalancer   10.96.181.254   10.2.0.241    80:32668/TCP,443:31847/TCP   34d
```

I have VM running on `srv3`, and it can't access this service via `10.2.0.241`:

```
ubuntu@testvm:~$ curl 10.2.0.241
curl: (7) Failed to connect to 10.2.0.241 port 80 after 0 ms: Connection refused
```

tcpdump shows that node respond that tcp port 80 unreachable:

```
12:59:26.628915 IP 10.244.1.149.41128 > 10.2.0.241.80: Flags [S], seq 1411240999, win 65280, options [mss 1360,sackOK,TS val 545481049 ecr 0,nop,wscale 7], length 0
12:59:26.629031 IP 10.2.0.241 > 10.244.1.149: ICMP 10.2.0.241 tcp port 80 unreachable, length 72
```

I can see that packets on veth interface related to the pod with virtual machine and `ovn0` interface, but I don't see it on external interface of the node.
`srv2` node, which is actually serving this IP-address doesn't have these packets recieved as well.

If I curl from the host netwroking namespace of `srv3`, I see that everything is working fine, but packet routed through the external interface of the node:

```
/ # ip route get 10.2.0.241
10.2.0.241 dev bond0  src 10.2.0.213
```

### Steps To Reproduce

1. create three node cluster
2. install kubeovn, kubevirt and metallb
3. cordon node3
4. install ingress-nginx-controller with `--set controller.service.externalTrafficPolicy=Local`
5. uncordon node3
6. cordon node1 and node2
7. Create VM:

   ```yaml
   apiVersion: kubevirt.io/v1
   kind: VirtualMachine
   metadata:
     name: testvm
   spec:
     running: true
     template:
       spec:
         domain:
           devices:
             disks:
             - disk:
                 bus: virtio
               name: containerdisk
             - disk:
                 bus: virtio
               name: cloudinitdisk
             interfaces:
             - name: default
               bridge: {}
           resources:
             requests:
               memory: 1024M
         terminationGracePeriodSeconds: 0
         accessCredentials:
         volumes:
         - containerDisk:
             image: ghcr.io/aenix-io/cozystack/ubuntu-container-disk:v1.30.1@sha256:81caf89efe252ae2ca1990d08a3a314552d70ff36bcd4022b173c7150fbec805
           name: containerdisk
         - cloudInitNoCloud:
             userData: |-
               #cloud-config
               password: ubuntu
               chpasswd: { expire: False }
           name: cloudinitdisk
         networks:
         - name: default
           pod: {}
   ```
   
8. Login to this vm:
   
   ```
   virtctl console testvm
   ```
   
   login: `ubuntu`
   password: `ubuntu`

9. curl nginx-ingress service via external IP

### Current Behavior

```
ubuntu@testvm:~$ curl  10.2.0.241
curl: (7) Failed to connect to 10.2.0.241 port 80 after 0 ms: Connection refused
```

### Expected Behavior

```
ubuntu@testvm:~$ curl  10.2.0.241
default backend - 404
```
