### ISSUE TITLE
[BUG] LoadBalancer Service fails to get an External IP

### ISSUE THREAD

**Issue by tgdfool2** [kubeovn/kube-ovn#4462]
### Kube-OVN Version

v1.12.21

### Kubernetes Version

v1.28.13

### Operation-system/Kernel Version

Ubuntu 22.04.4 LTS
5.15.0-1063

### Description

We are trying to use `kube-ovn` to replace `MetalLB` to configure an external IP address for Ingress Nginx. The goal is to have the IP 192.168.0.71 assigned to the `ingress-nginx-controller` Service.

Deployed resources:
```
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lb-svc-attachment
  namespace: ingress-nginx
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth0",
      "mode": "bridge"
    }'
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: ingress-nginx-attach-subnet
spec:
  protocol: IPv4
  provider: lb-svc-attachment.ingress-nginx
  cidrBlock: 192.168.0.64/28
  gateway: 192.168.0.65
  excludeIps:
  - 192.168.0.65..192.168.0.70
  - 192.168.0.72..192.168.0.78
```

While creating the Service as follow:
```
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    ovn.kubernetes.io/vpc: ovn-cluster
    lb-svc-attachment.ingress-nginx.kubernetes.io/logical_switch: ingress-nginx-attach-subnet
    ovn.kubernetes.io/attachmentprovider: lb-svc-attachment.ingress-nginx
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  ports:
  - appProtocol: http
    name: http
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: LoadBalancer
```

A Pod gets created, but it fails with the following error message in the `kube-ovn-controller` Pod:
```
I0830 10:34:39.356786       7 service_lb.go:311] add eip rules for lb svc pod, [192.168.0.71/28,192.168.0.65]
E0830 10:34:42.459500       7 service_lb.go:271] failed to ExecuteCommandInContainer, errOutput: failed to exec command "arping -c 3 -s 192.168.0.71 192.168.0.65"
E0830 10:34:42.459514       7 service_lb.go:276] command terminated with exit code 1
E0830 10:34:42.459522       7 service_lb.go:313] failed to add eip for pod, err: command terminated with exit code 1
E0830 10:34:42.459531       7 service.go:529] failed to update pod attachment network for service ingress-nginx/ingress-nginx-controller: command terminated with exit code 1
E0830 10:34:42.459554       7 service.go:166] error syncing 'ingress-nginx/ingress-nginx-controller': command terminated with exit code 1, requeuing
```

While logging into the Pod and manually trying the `arping` command, here is the result:
```
# arping -c 3 -s 192.168.0.71 192.168.0.65; echo $?
ARPING 192.168.0.65 from 192.168.0.71 net1
Unicast reply from 192.168.0.65 [00:00:5E:9F:7B:35]  0.903ms
Unicast reply from 192.168.0.65 [00:00:5E:9F:7B:35]  0.922ms
Unicast reply from 192.168.0.65 [00:00:5E:9F:7B:35]  0.712ms
Unicast reply from 192.168.0.65 [00:00:5E:9F:7B:35]  0.627ms
Sent 3 probes (1 broadcast(s))
Received 4 response(s)
1
```

To me it looks good, but somehow the return code of `arping` is 1. Any idea why this is the case and how this issue could be solved?

Thank you very much for your support!

### Steps To Reproduce

See description

### Current Behavior

External IP fails to be assigned

### Expected Behavior

External IP successfully assigned
