### ISSUE TITLE
[BUG] Unable to start on Talos Linux

### ISSUE THREAD

**Issue by nniehoff** [kubeovn/kube-ovn#4526]
### Kube-OVN Version

v1.13.0

### Kubernetes Version

v1.31.1

### Operation-system/Kernel Version

Talos (v1.7.6)
6.6.43-talos

### Description

When the `ovs-ovn` daemonset tries to start the `openvswitch` container fails to start with this error:

```
/kube-ovn/start-ovs.sh: line 83: /usr/local/sbin/iptables: Operation not permitted
```

I have tried changing the securityContext to run this container privileged and as root but it still has this error.  

### Steps To Reproduce

1.  Deploy a Talos Linux cluster
2. Deploy the helm chart from the master branch
3. Use these values:

```yaml
---
cni_conf:
  CNI_CONFIG_PRIORITY: "10"
  MOUNT_LOCAL_BIN_DIR: false
func:
  ENABLE_NP: false
ipv4:
  POD_CIDR: "10.131.0.0/16"
  POD_GATEWAY: "10.131.0.1"
  SVC_CIDR: "10.128.0.0/20"
  JOIN_CIDR: "10.130.0.0/24"
  # PINGER_EXTERNAL_ADDRESS: "1.1.1.1"
  # PINGER_EXTERNAL_DOMAIN: "kube-ovn.io."
namespace: "kube-system"
DISABLE_MODULES_MANAGEMENT: true
OPENVSWITCH_DIR: "/var/kube-ovn/openvswitch"
OVN_DIR: "/var/kube-ovn/ovn"
```

I have followed the directions in the chart README I used a different path for `OPENVSWITCH_DIR` and `OVN_DIR` but I believe this should still work as I believe the primary intention is to move this path to a writeable path under /var.

### Current Behavior

Pods in both `ovs-ovn` and `kube-ovn-cni` DaemonSets fail to start correctly

### Expected Behavior

Pods should be running and healthy

**Comment by nniehoff** [comment]
I have tried these exact suggestions provided by @dosu, however, they do not resolve the issue

**Comment by nniehoff** [comment]
running iptables in the init container has the same `Operation not permitted` error.  I have tried both containers with:

```yaml
securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        allow:
          - ALL
      privileged: true
      runAsUser: 0
      runAsGroup: 0
```

with no luck.

**Comment by nniehoff** [comment]
@dosu running iptables in the init container has the same `Operation not permitted` error.  I have tried both containers with:

```yaml
securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        allow:
          - ALL
      privileged: true
      runAsUser: 0
      runAsGroup: 0
```

with no luck.

**Comment by nniehoff** [comment]
it occured to me to try symlinking iptables to /bin/true as is done for several other utilities that can't be used in talos however I have the same results with `ovs-vswitchd` which I know we can't shortcut.  @dosu any other ideas

```
/usr/share/openvswitch/scripts/ovs-ctl: 1: ovs-vswitchd: Operation not permitted
```

**Comment by nniehoff** [comment]
@dosu tried this, however, it doesn't resolve the problem

**Comment by PeterFalken** [comment]
I get an error on the Daemonset that says:
`cannot create regular file '/usr/local/bin/kubectl-ko': Read-only file system`
And the Controller fails to connect to it kubernetes endpoint.

**Comment by tamay86** [comment]
@nniehoff 
I got the same problem, almost identical configuration. Running Talos 1.8.1, kube-ovn 1.13 via Helm.
Relevant values:
```
  cni_conf:
    CNI_CONFIG_PRIORITY: "10"
  OPENVSWITCH_DIR: "/var/lib/openvswitch"
  OVN_DIR: "/var/lib/ovn"
  DISABLE_MODULES_MANAGEMENT: true
```

I tried quite a few things and got this workaround - I'm not content with it, but at least it works for now in my test lab.

What I did:
- Edited the Daemonset ovn-ovs
- Change the image to  `v1.12.28` for the `openvswitch` container (yes, the init container runs with `v1.13.0`)
- Edit the security context and change `runAsUser` to `0`

```shell
kubectl -n kube-system edit ds ovs-ovn
...
    spec:
      containers:
      - command:
        - /kube-ovn/start-ovs.sh
        image: docker.io/kubeovn/kube-ovn:v1.12.28
        name: openvswitch
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_BIND_SERVICE
            - SYS_NICE
            - SYS_ADMIN
          privileged: true
          runAsUser: 0
...
```

**Comment by PeterFalken** [comment]
I'm still getting an error, but I think that the paths are correct.
`failed to generate container "XXXXYYYZZZZ" spec: failed to generate spec: failed to mkdir "/etc/origin/openvswitch": mkdir /etc/origin: read-only file system`

I've already added the kernel parameter for openvswitch.
```
machine:
  kernel:
    modules:
    - name: openvswitch
```

These are the values I'm feeding the Helm chart:
```
global:
  images:
    kubeovn:
      tag: v1.12.28

ipv4:
  POD_CIDR: "10.244.0.0/16"
  POD_GATEWAY: "10.244.0.1"

DISABLE_MODULES_MANAGEMENT: true
OPENVSWITCH_DIR: /var/lib/openvswitch
OVN_DIR: /var/lib/ovn
cni_conf:
  MOUNT_LOCAL_BIN_DIR: false
```
