### ISSUE TITLE
[BUG] conflict, when two vpcs with different subnets, two nat gateways ( an external subnet )

### ISSUE THREAD

**Issue by cybercoder** [kubeovn/kube-ovn#4566]
### Kube-OVN Version

v1.12.25

### Kubernetes Version

v1.30.4+k3s1

### Operation-system/Kernel Version

Ubuntu 20.04.6 LTS
5.4.0-196-generic

### Description

according to [this](https://kubeovn.github.io/docs/v1.12.x/en/guide/vpc/) documentation, a custom VPC with a nat gateway works properly.

but EIP, DNAT get conflict, when the second VPC and it's NAT GW starts running.

### Steps To Reproduce

Create External (Non-OVN):

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: external1
spec:
  protocol: IPv4
  provider: external1.kube-system
  cidrBlock: 172.17.88.0/24
  gateway: 172.17.88.1  # IP address of the physical gateway
  excludeIps:
  - 172.17.88.1..172.17.88.100
---
# multus thin
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: external1
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens224",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "external1.kube-system"
      }
    }'
---
```
VPC, Internal subnet, Nat Gateway:
```yaml
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: roya-vpc-1
spec:
  namespaces:
  - roya
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: roya-subnet1
spec:
  vpc: roya-vpc-1
  cidrBlock: 10.0.1.0/24
  gateway: 10.0.1.254
  protocol: IPv4
  namespaces:
    - roya
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: roya-gw
spec:
  vpc: roya-vpc-1
  subnet: roya-subnet1
  lanIp: 10.0.1.254
  externalSubnets:
    - external1
```
Now the EIP and the POD:
```
kind: IptablesEIP
apiVersion: kubeovn.io/v1
metadata:
  name: roya-alpine-eip
spec:
  natGwDp: roya-gw
  externalSubnet: external1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginxalpine
  namespace: roya
  annotations:
    ovn.kubernetes.io/logical_router: roya-vpc-1
    ovn.kubernetes.io/logical_switch: roya-subnet1
    ovn.kubernetes.io/snat: roya-alpine-eip # seems doesn't work with custom VPC
    ovn.kubernetes.io/eip: roya-alpine-eip # seems doesn't work with custom VPC
spec:
  containers:
  - name: alpine
    image: nginx:alpine
```
It needs a custom SNAT/DNAT (seems eip,snat annotations doesn't work like default VPC):

```yaml
kind: IptablesDnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: roya-nginxalpine-dnat
spec:
  eip: roya-alpine-eip
  internalIp: 10.0.1.2
  externalPort: "80"
  protocol: tcp
  internalPort: "80"
---
kind: IptablesSnatRule
apiVersion: kubeovn.io/v1
metadata:
  name: roya-nginxalpine-snat
spec:
  eip: roya-alpine-eip
  internalCIDR: 10.0.1.0/24
```
Now, it works and curl on ```eip``` shows the Nginx page.

### Current Behavior

When we clone that configs ( except external subnet and NAD ),

- second VPC
- second Subnet ( but same CIDR )
- second NAT GW ( one side to the same external )
- second POD, EIP ( on same External )

The CURL getting timeout on the first POD ( DNAT or GWs seems conflict )

### Expected Behavior

Real isolation.

**Comment by zhangzujian** [comment]
```yaml
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: roya-subnet1
spec:
  vpc: roya-vpc-1
  cidrBlock: 10.0.1.0/24
  gateway: 10.0.1.254
  protocol: IPv4
  namespaces:
    - roya
---
kind: VpcNatGateway
apiVersion: kubeovn.io/v1
metadata:
  name: roya-gw
spec:
  vpc: roya-vpc-1
  subnet: roya-subnet1
  lanIp: 10.0.1.254
  externalSubnets:
    - external1
```

Seems field `.spec.lanIp` of the vpc nat gateway is conflict with the subnet gateway. Please change the gateway lanIp or subnet gateway and try again.
