### ISSUE TITLE
[BUG] DHCP server doesn't work!

### ISSUE THREAD

**Issue by cybercoder** [kubeovn/kube-ovn#4582]
### Kube-OVN Version

v1.12.25

### Kubernetes Version

v1.30.5+k3s1

### Operation-system/Kernel Version

ubuntu 20.04 LTS

### Description

When i enable the DHCP for a subnet with custom provider, it not works.

### Steps To Reproduce

This is my subnet:
```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet-1707237939748
spec:
  cidrBlock: 172.17.17.0/24
  default: false
  dhcpV4Options: lease_time=3600,router=172.17.17.1,server_id=169.254.0.254,server_mac=00:00:00:2E:2F:B8
  disableGatewayCheck: true
  enableDHCP: true
  excludeIps:
  - 172.17.17.1
  gateway: 172.17.17.1
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: default.1707237939748.ovn
  vpc: vpc1707237939748
```

And the ```NAD``` :
```yaml
apiVersion: v1
items:
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    name: default
    namespace: "1707237939748"
  spec:
    config: '{ "cniVersion": "0.3.0", "type": "kube-ovn", "provider": "default.1707237939748.ovn",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock" }'
```

The first KubeVirt VM NIC is connected to the default subnet. and the second to the the subnet-1707237939748 using multus.

### Current Behavior

The VM doesn't set the default gateway.
and when try to see the DHCP server, It seems the default DHCP server hasn't replaced, but there's located:
```
$ kubectl ko nbctl list dhcp_options
_uuid               : 247d72c3-41fd-4778-a0c6-d0c9a932f2a1
cidr                : "172.17.17.0/24"
external_ids        : {ls=subnet-1707237939748, protocol=IPv4, vendor=kube-ovn}
options             : {lease_time="3600", router="172.17.17.1", server_id="169.254.0.254", server_mac="00:00:00:2E:2F:B8"}
```

```
$ dhclient -d -nw enp1s0

Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/enp1s0/ae:6b:32:af:33:9a
Sending on   LPF/enp1s0/ae:6b:32:af:33:9a
Sending on   Socket/fallback
DHCPREQUEST for 172.17.17.7 on enp1s0 to 255.255.255.255 port 67 (xid=0x68d8136a)
DHCPACK of 172.17.17.7 from 169.254.75.10 (xid=0x6a13d868)
RTNETLINK answers: File exists
bound to 172.17.17.7 -- renewal in 37158937 seconds.
```

### Expected Behavior

To set the default gateway.

**Comment by zhangzujian** [comment]
> The VM doesn't set the default gateway.

What does this mean? Result of command `dhclient -d -nw enp1s0` shows that the ovn dhcp server is working on enp1s0.

**Comment by cybercoder** [comment]
> > The VM doesn't set the default gateway.
> 
> What does this mean? Result of command `dhclient -d -nw enp1s0` shows that the ovn dhcp server is working on enp1s0.

It's not that DHCP server: 169.254.75.10

**Comment by zhangzujian** [comment]
I cannot reproduce this problem in my KIND cluster. Here is my test resources:

```yaml
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: vpc1
spec: {}
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet1
spec:
  cidrBlock: 172.17.17.0/24
  default: false
  dhcpV4Options: lease_time=3600,router=172.17.17.1,server_id=169.254.0.254,server_mac=00:00:00:2E:2F:B8
  disableGatewayCheck: true
  enableDHCP: true
  excludeIps:
  - 172.17.17.1
  gateway: 172.17.17.1
  gatewayNode: ""
  gatewayType: distributed
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: nad.default.ovn
  vpc: vpc1
---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: nad
  namespace: default
spec:
  config: '{ "cniVersion": "0.3.0", "type": "kube-ovn", "provider": "nad.default.ovn",
    "server_socket": "/run/openvswitch/kube-ovn-daemon.sock" }'
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: pod1
  namespace: default
spec:
  selector:
    matchLabels:
      app: kubeovn
  template:
    metadata:
      labels:
        app: kubeovn
      annotations:
        k8s.v1.cni.cncf.io/networks: default/nad
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: pod
        imagePullPolicy: Never
        image: kubeovn/kube-ovn:v1.12.25
        securityContext:
          privileged: true
        command:
          - sleep
          - "10000"
```

Test result:

```shell
$ ip -c a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
20: eth0@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default
    link/ether 26:4c:31:f9:d2:c5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.16.0.8/16 brd 10.16.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::244c:31ff:fef9:d2c5/64 scope link
       valid_lft forever preferred_lft forever
22: net1@if23: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default
    link/ether 8a:8d:60:3c:0b:82 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.17.2/24 brd 172.17.17.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::888d:60ff:fe3c:b82/64 scope link
       valid_lft forever preferred_lft forever
$ ip a del 172.17.17.2/24 dev net1
$ ip -c a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
20: eth0@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default
    link/ether 26:4c:31:f9:d2:c5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.16.0.8/16 brd 10.16.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::244c:31ff:fef9:d2c5/64 scope link
       valid_lft forever preferred_lft forever
22: net1@if23: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default
    link/ether 8a:8d:60:3c:0b:82 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::888d:60ff:fe3c:b82/64 scope link
       valid_lft forever preferred_lft forever
$ dhcpcd net1
dhcpcd-10.0.6 starting
DUID 00:01:00:01:2e:97:9f:34:8a:8d:60:3c:0b:82
net1: IAID 60:3c:0b:82
net1: soliciting an IPv6 router
net1: soliciting a DHCP lease
net1: offered 172.17.17.2 from 169.254.0.254
net1: probing address 172.17.17.2/24
net1: leased 172.17.17.2 for 3600 seconds
net1: adding route to 172.17.17.0/24
net1: adding default route via 172.17.17.1
Dropped protocol specifier '.dhcp' from 'net1.dhcp'. Using 'net1' (ifindex=22).
$ ip -c a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
20: eth0@if21: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default
    link/ether 26:4c:31:f9:d2:c5 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.16.0.8/16 brd 10.16.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::244c:31ff:fef9:d2c5/64 scope link
       valid_lft forever preferred_lft forever
22: net1@if23: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue state UP group default
    link/ether 8a:8d:60:3c:0b:82 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.17.2/24 brd 172.17.17.255 scope global dynamic noprefixroute net1
       valid_lft 3396sec preferred_lft 2946sec
    inet6 fe80::888d:60ff:fe3c:b82/64 scope link
       valid_lft forever preferred_lft forever
$ ip -c r
default via 10.16.0.1 dev eth0
default via 172.17.17.1 dev net1 proto dhcp src 172.17.17.2 metric 1022
10.16.0.0/16 dev eth0 proto kernel scope link src 10.16.0.8
172.17.17.0/24 dev net1 proto dhcp scope link src 172.17.17.2 metric 1022
```
