### ISSUE TITLE
[BUG] Ping not working between VMs in different subnets via VPC

### ISSUE THREAD

**Issue by rrajendran17** [kubeovn/kube-ovn#4680]
### Kube-OVN Version

v1.12.28

### Kubernetes Version

v1.29.9

### Operation-system/Kernel Version

suse/sle-micro/base-5.5:2.0.4-5.8.105

### Description

Install kubeovn using install.sh provided

Check the pods running

```shell
kubectl get pods -n kube-system -o wide | grep ovn
kube-ovn-cni-rz6rg                                      1/1     Running     0             14d   172.19.98.225   renuka-dev-v131   <none>           <none>
kube-ovn-controller-85b45f7694-tbk9g                    1/1     Running     0             14d   172.19.98.225   renuka-dev-v131   <none>           <none>
kube-ovn-monitor-7c45cd8dcd-x2mqh                       1/1     Running     0             14d   172.19.98.225   renuka-dev-v131   <none>           <none>
kube-ovn-pinger-wt48g                                   1/1     Running     0             14d   10.52.0.107     renuka-dev-v131   <none>           <none>
ovn-central-844fdf4f4f-n6npg                            1/1     Running     0             14d   172.19.98.225   renuka-dev-v131   <none>           <none>
ovs-ovn-c4k27                                           1/1     Running     0             14d   172.19.98.225   renuka-dev-v131   <none>           <none>
```

2.create vpc

```yaml
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: commonvpc
```

3.create nad attachnet

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: attachnet
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "kube-ovn",
      "bridge":"cluster-1-br",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "attachnet.default.ovn"
    }'
```

4.create another nad attachnet2

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: attachnet2
  namespace: default
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "kube-ovn",
      "bridge":"cluster-1-br",
      "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
      "provider": "attachnet2.default.ovn"
    }'
```

5.create subnet using attachnet nad and attaching to commonvpc vpc

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: attachnet
spec:
  protocol: IPv4
  provider: attachnet.default.ovn
  vpc: commonvpc
  cidrBlock: 172.20.0.0/16
  gateway: 172.20.0.1
  excludeIps:
  - 172.20.0.0..172.20.0.10
``` 

6.create subnet using attachnet2 nad and attaching to commonvpc vpc

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: attachnet2
spec:
  protocol: IPv4
  provider: attachnet2.default.ovn
  vpc: commonvpc
  cidrBlock: 172.30.0.0/16
  gateway: 172.30.0.1
  excludeIps:
  - 172.30.0.0..172.30.0.10
```

7.kubectl get subnets

```txt
NAME          PROVIDER                 VPC           PROTOCOL   CIDR            PRIVATE   NAT     DEFAULT   GATEWAYTYPE   V4USED   V4AVAILABLE   V6USED   V6AVAILABLE   EXCLUDEIPS                    U2OINTERCONNECTIONIP
attachnet     attachnet.default.ovn    commonvpc     IPv4       172.20.0.0/16   false     false   false     distributed   0        65524         0        0             ["172.20.0.0..172.20.0.10"]   
attachnet2    attachnet2.default.ovn   commonvpc     IPv4       172.30.0.0/16   false     false   false     distributed   0        65524         0        0             ["172.30.0.0..172.30.0.10"]   
join          ovn                      ovn-cluster   IPv4       100.64.0.0/16   false     false   false     distributed   1        65532         0        0             ["100.64.0.1"]                
ovn-default   ovn                      ovn-cluster   IPv4       10.16.0.0/16    false     true    true      distributed   51       65482         0        0             ["10.16.0.1"]  
```

8.kubectl ko nbctl show attachnet

```txt
switch 7158370c-1a7e-4fde-ab73-36d5f3c84ab9 (attachnet)
    port attachnet-commonvpc
        type: router
        router-port: commonvpc-attachnet
    port vm1-nad1.default.attachnet.default.ovn
        addresses: ["0a:7b:13:a7:1b:d8 172.20.0.11"]
    port vm2-nad1.default.attachnet.default.ovn
        addresses: ["86:e8:59:a0:ee:2d 172.20.0.12"]

```

9.kubectl ko nbctl show attachnet2

```txt
switch 525da15e-6c55-4aa7-90dd-6639c3b9dee7 (attachnet2)
    port attachnet2-commonvpc
        type: router
        router-port: commonvpc-attachnet2
    port vm1-nad2.default.attachnet2.default.ovn
        addresses: ["2a:66:2a:8d:34:95 172.30.0.11"]

```

10.Login to ovs container to check bridge interfaces

```shell
root@harvester-node-0:/kube-ovn# ovs-vsctl show
f0477e82-12c0-4c41-9077-2bc24f7ae81b
    Bridge br-int
        fail_mode: secure
        datapath_type: system
        Port ovn0
            Interface ovn0
                type: internal
        Port d4873_37a8eec_h
            Interface d4873_37a8eec_h
        Port mirror0
            Interface mirror0
                type: internal
        Port ovn-440661-0
            Interface ovn-440661-0
                type: geneve
                options: {csum="true", key=flow, remote_ip="192.168.0.31"}
        Port br-int
            Interface br-int
                type: internal
        Port "21fa2_37a8eec_h"
            Interface "21fa2_37a8eec_h"
        Port "49333_37a8eec_h"
            Interface "49333_37a8eec_h"
    ovs_version: "3.1.6"

```

1.create a vm and attach to attachnet nad.(172.20.0.11/16)
2.create a vm and attach to attachnet nad.(172.20.0.12/16)
3.create a vm and attach to attachnet2 nad(172.30.0.11/16)
4.Ping between 172.20.0.11 to 172.20.0.12 works (same subnet - L2 works)
5.Ping between 172.20.0.11 to 172.30.0.11 fails (different subnet - L3 fails)

Though nbctl shows correct entries for both vm interface and router interface, the ping fails.
Is anymore additional config required to achieve this.

Note:This is a single host and all vms are created on the same host.

### Steps To Reproduce

1.create a vm and attach to attachnet nad.(172.20.0.11/16)
2.create a vm and attach to attachnet nad.(172.20.0.12/16)
3.create a vm and attach to attachnet2 nad(172.30.0.11/16)
4.Ping between 172.20.0.11 to 172.20.0.12 works (same subnet - L2 works)
5.Ping between 172.20.0.11 to 172.30.0.11 fails (different subnet - L3 fails)

### Current Behavior

Ping fails between interfaces of VMs in different subnet via vpc

### Expected Behavior

Ping should work between interfaces of VMs in different subnet via vpc.
