### ISSUE TITLE
[BUG] change the ```ovn.kubernetes.io/external-gw=true``` node label to false on restart!

### ISSUE THREAD

**Issue by cybercoder** [kubeovn/kube-ovn#4772]
### Kube-OVN Version

v1.12.28

### Kubernetes Version

v1.30.6+k3s1

### Operation-system/Kernel Version

not important

### Description

These are my configs:

```yaml
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: external
spec:
  defaultInterface: ether1
---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan0
spec:
  id: 0
  provider: external
---

apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: external
spec:
  protocol: IPv4
  cidrBlock: 192.168.128.0/17
  gateway: 192.168.128.2
  vlan: vlan0
  excludeIps:
  - 192.168.128.1..192.168.128.10
```

### Steps To Reproduce

1. kubectl label node <<node_name>> ovn.kubernetes.io/external-gw=true --overwrite
2. kubectl -n kube-system rollout restart deployment kube-ovn-controller # or simply delete the pod.

### Current Behavior

Reset the node label to false and all OEIP,OFIP and pings get down.
We must set all labels for nodes and restart it again.

### Expected Behavior

detect the situation!

### dirty workaround:

A cronjob:

```bash
#!/bin/bash

# Find all Kubernetes nodes with the label `node-role.kubernetes.io/compute=true`
NODES=$(kubectl get nodes -l node-role.kubernetes.io/compute=true -o jsonpath='{.items[*].metadata.name}')

# Apply the label `ovn.kubernetes.io/external-gw=true` to each node
for NODE in $NODES; do
    kubectl label node "$NODE" ovn.kubernetes.io/external-gw=true --overwrite
done

# Restart the kube-ovn-controller deployment by deleting its pod in the kube-system namespace
kubectl delete pod -n kube-system -l app=kube-ovn-controller


# Apply the label `ovn.kubernetes.io/external-gw=true` to each node
for NODE in $NODES; do
    kubectl label node "$NODE" ovn.kubernetes.io/external-gw=true --overwrite
done
```

**Comment by cybercoder** [comment]
I have used this workaround :

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  type: "distributed"
  enable-external-gw: "true"
```
Is it ok?
