### ISSUE TITLE
[BUG] Unable to create a pod after upgrading to v1.13.2.

### ISSUE THREAD

**Issue by zsxsoft** [kubeovn/kube-ovn#4840]
### Kube-OVN Version

v1.13.2

### Kubernetes Version

v1.31.2

### Operation-system/Kernel Version

TencentOS Server 4.2
6.6.47-12.tl4.x86_64

### Description

When I upgrade from v1.12.28 to v1.13.0, I've noticed that whenever my Subnet is configured with any ACL, creating a pod with a securitygroup consistently results in a "network not ready after XX ping" related log in CNI. 

<img width="866" alt="image" src="https://github.com/user-attachments/assets/d7ddb634-6c06-4d23-bbdc-229fecd91f41" />

Subnets created in 1.12.28 can still create pods in version 1.13. This issue only occurs with Subnets created in version 1.13. Additionally, if I downgrade back to version 1.12.28, the issue disappears. 

In my test environment 1.28.30 -> 1.13.0, if I remove the securitygroup annotations from the pod or delete all ACLs from the subnet, this will be ready and the pod will be created.

The following yaml can be applied in v1.28.30, it works.

In 1.28.30 -> 1.13.2, I can't do nothing to let the following yaml applied. It happened in my 2 different clusters upgraded from v1.12, and my new test cluster with v1.28.30 -> v.13.2.

<img width="886" alt="image" src="https://github.com/user-attachments/assets/f7b1afc9-d649-423f-ba46-c92a65ca0365" />

```yaml
apiVersion: kubeovn.io/v1
kind: SecurityGroup
metadata:
  name: sg-net-83747e7952934db3a1f0ab1602fd9bc2
spec:
  allowSameGroupTraffic: true
  ingressRules:
    - ipVersion: ipv4
      policy: allow
      priority: 200
      protocol: all
      remoteAddress: 0.0.0.0/0
      remoteType: address
  egressRules:
    - ipVersion: ipv4
      policy: drop
      priority: 199
      protocol: all
      remoteAddress: 10.0.0.0/8
      remoteType: address
    - ipVersion: ipv4
      policy: allow
      priority: 200
      protocol: all
      remoteAddress: 0.0.0.0/0
      remoteType: address
    - ipVersion: ipv4
      policy: allow
      priority: 100
      protocol: all
      remoteAddress: 10.232.82.0/24
      remoteType: address
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: net-83747e7952934db3a1f0ab1602fd9bc2
spec:
  acls:
  - action: allow-related
    direction: from-lport
    match: ip
    priority: 1002
  cidrBlock: 10.232.82.0/24
  default: false
  enableDHCP: true
  enableLb: true
  gateway: 10.232.82.1
  gatewayNode: ""
  gatewayType: distributed
  mtu: 1400
  natOutgoing: true
  private: false
  protocol: IPv4
  provider: ovn
  vpc: ovn-cluster
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    ovn.kubernetes.io/security_groups: sg-net-83747e7952934db3a1f0ab1602fd9bc2
    ovn.kubernetes.io/logical_switch: net-83747e7952934db3a1f0ab1602fd9bc2
spec:
  containers:
  - name: nginx
     image: nginx
```

Trace here, It looks like KubeOVN didn't match any SG in this pod so fallback to`kubeovn_deny_all`.

```
[root@k8s-master ~]# kubectl ko trace vm/minio 10.232.82.1 tcp 80
[root@k8s-master ~]# kubectl ko trace vm/minio 10.232.82.89 tcp 80
+ kubectl exec ovn-central-69c8f7b97b-csmpk -n kube-system -c ovn-central -- ovn-trace net-83747e7952934db3a1f0ab1602fd9bc2 'inport == "minio.vm" && ip.ttl == 64 && eth.src == be:23:11:83:32:ad && ip4.src == 10.232.82.5 && eth.dst == 4c:3d:a5:43:28:eb && ip4.dst == 10.232.82.89 && tcp.src == 10000 && tcp.dst == 80 && ct.new'
# ct_state=new|trk,tcp,reg14=0x6,vlan_tci=0x0000,dl_src=be:23:11:83:32:ad,dl_dst=4c:3d:a5:43:28:eb,nw_src=10.232.82.5,nw_dst=10.232.82.89,nw_tos=0,nw_ecn=0,nw_ttl=64,nw_frag=no,tp_src=10000,tp_dst=80,tcp_flags=0

ingress(dp="net-83747e7952934db3a1f0ab1602fd9bc2", inport="minio.vm")
---------------------------------------------------------------------
 0. ls_in_check_port_sec (northd.c:9039): 1, priority 50, uuid 58bb491f
    reg0[15] = check_in_port_sec();
    next;
 4. ls_in_pre_acl (northd.c:6023): ip, priority 100, uuid e0c5b3fc
    reg0[0] = 1;
    next;
 5. ls_in_pre_lb (northd.c:6227): ip, priority 100, uuid ea5b345c
    reg0[2] = 1;
    next;
 6. ls_in_pre_stateful (northd.c:6382): reg0[2] == 1, priority 110, uuid 05f7b0b4
    ct_lb_mark;

ct_lb_mark /* default (use --ct to customize) */
------------------------------------------------
 7. ls_in_acl_hint (northd.c:6511): ct.est && ct_mark.blocked == 0, priority 1, uuid 5c869d92
    reg0[10] = 1;
    next;
 8. ls_in_acl_eval (northd.c:6724): reg8[30..31] == 0 && reg0[10] == 1 && (inport == @ovn.sg.kubeovn_deny_all && ip), priority 3003, uuid cc4049b9
    reg8[17] = 1;
    ct_commit { ct_mark.blocked = 1; };
    next;
 9. ls_in_acl_action (northd.c:6842): reg8[17] == 1, priority 1000, uuid 88f0c49d
    reg8[16] = 0;
    reg8[17] = 0;
    reg8[18] = 0;
    reg8[30..31] = 0;
+ set +x
--------
Start OVS Tracing


+ kubectl exec ovs-ovn-xfdb2 -c openvswitch -n kube-system -- ovs-appctl ofproto/trace br-int in_port=105,tcp,nw_ttl=64,nw_src=10.232.82.5,nw_dst=10.232.82.89,dl_src=be:23:11:83:32:ad,dl_dst=4c:3d:a5:43:28:eb,tcp_src=1000,tcp_dst=80
Flow: tcp,in_port=105,vlan_tci=0x0000,dl_src=be:23:11:83:32:ad,dl_dst=4c:3d:a5:43:28:eb,nw_src=10.232.82.5,nw_dst=10.232.82.89,nw_tos=0,nw_ecn=0,nw_ttl=64,nw_frag=no,tp_src=1000,tp_dst=80,tcp_flags=0

bridge("br-int")
----------------
 0. in_port=105, priority 100, cookie 0x8d1ed171
    set_field:0x1c/0xffff->reg13
    set_field:0x1a->reg11
    set_field:0x1b->reg12
    set_field:0x4->metadata
    set_field:0x6->reg14
    set_field:0/0xffff0000->reg13
    resubmit(,8)
 8. metadata=0x4, priority 50, cookie 0x58bb491f
    set_field:0/0x1000->reg10
    resubmit(,73)
    73. No match.
            drop
    move:NXM_NX_REG10[12]->NXM_NX_XXREG0[111]
     -> NXM_NX_XXREG0[111] is now 0
    resubmit(,9)
 9. metadata=0x4, priority 0, cookie 0x1541808
    resubmit(,10)
10. metadata=0x4, priority 0, cookie 0x6587e4f4
    resubmit(,11)
11. metadata=0x4, priority 0, cookie 0x4173bf59
    resubmit(,12)
12. ip,metadata=0x4, priority 100, cookie 0xe0c5b3fc
    set_field:0x1000000000000000000000000/0x1000000000000000000000000->xxreg0
    resubmit(,13)
13. ip,metadata=0x4, priority 100, cookie 0xea5b345c
    set_field:0x4000000000000000000000000/0x4000000000000000000000000->xxreg0
    resubmit(,14)
14. ip,reg0=0x4/0x4,metadata=0x4, priority 110, cookie 0x5f7b0b4
    ct(table=15,zone=NXM_NX_REG13[0..15],nat)
    nat
     -> A clone of the packet is forked to recirculate. The forked pipeline will be resumed at table 15.
     -> Sets the packet to an untracked state, and clears all the conntrack fields.

Final flow: tcp,reg0=0x5,reg11=0x1a,reg12=0x1b,reg13=0x1c,reg14=0x6,metadata=0x4,in_port=105,vlan_tci=0x0000,dl_src=be:23:11:83:32:ad,dl_dst=4c:3d:a5:43:28:eb,nw_src=10.232.82.5,nw_dst=10.232.82.89,nw_tos=0,nw_ecn=0,nw_ttl=64,nw_frag=no,tp_src=1000,tp_dst=80,tcp_flags=0
Megaflow: recirc_id=0,eth,tcp,in_port=105,dl_src=00:00:00:00:00:00/01:00:00:00:00:00,dl_dst=4c:3d:a5:43:28:eb,nw_dst=0.0.0.0/1,nw_frag=no
Datapath actions: ct(zone=28,nat),recirc(0x212)

===============================================================================
recirc(0x212) - resume conntrack with default ct_state=trk|new (use --ct-next to customize)
Replacing src/dst IP/ports to simulate NAT:
 Initial flow:
 Modified flow:
===============================================================================

Flow: recirc_id=0x212,ct_state=new|trk,ct_zone=28,eth,tcp,reg0=0x5,reg11=0x1a,reg12=0x1b,reg13=0x1c,reg14=0x6,metadata=0x4,in_port=105,vlan_tci=0x0000,dl_src=be:23:11:83:32:ad,dl_dst=4c:3d:a5:43:28:eb,nw_src=10.232.82.5,nw_dst=10.232.82.89,nw_tos=0,nw_ecn=0,nw_ttl=64,nw_frag=no,tp_src=1000,tp_dst=80,tcp_flags=0

bridge("br-int")
----------------
    thaw
        Resuming from table 15
15. ct_state=+new-est+trk,metadata=0x4, priority 7, cookie 0x879f1bd7
    set_field:0x80000000000000000000000000/0x80000000000000000000000000->xxreg0
    set_field:0x200000000000000000000000000/0x200000000000000000000000000->xxreg0
    resubmit(,16)
16. ip,reg0=0x200/0x200,reg8=0/0xc0000000,reg14=0x6,metadata=0x4, priority 3003, cookie 0x22e6c0cd
    set_field:0x2000000000000/0x2000000000000->xreg4
    resubmit(,17)
17. reg8=0x20000/0x20000,metadata=0x4, priority 1000, cookie 0x88f0c49d
    set_field:0/0x1000000000000->xreg4
    set_field:0/0x2000000000000->xreg4
    set_field:0/0x4000000000000->xreg4
    set_field:0/0xc000000000000000->xreg4

Final flow: recirc_id=0x212,ct_state=new|trk,ct_zone=28,eth,tcp,reg0=0x285,reg11=0x1a,reg12=0x1b,reg13=0x1c,reg14=0x6,metadata=0x4,in_port=105,vlan_tci=0x0000,dl_src=be:23:11:83:32:ad,dl_dst=4c:3d:a5:43:28:eb,nw_src=10.232.82.5,nw_dst=10.232.82.89,nw_tos=0,nw_ecn=0,nw_ttl=64,nw_frag=no,tp_src=1000,tp_dst=80,tcp_flags=0
Megaflow: recirc_id=0x212,ct_state=+new-est-rel-rpl+trk,ct_mark=0/0x1,eth,ip,in_port=105,dl_dst=4c:3d:a5:43:28:eb,nw_frag=no
Datapath actions: drop
[root@k8s-master ~]#
```

### Steps To Reproduce

IDK

### Current Behavior

/

### Expected Behavior

/
