### ISSUE TITLE
[BUG] kube-ovn-cni adds ip6tables rules for an IPv4 subnet

### ISSUE THREAD

**Issue by zhangzujian** [kubeovn/kube-ovn#4843]
### Kube-OVN Version

v1.12/v1.13/master

### Kubernetes Version

v1.30

### Operation-system/Kernel Version

4.19

### Description

In a dual-stack cluster, kube-ovn-cni reports error for an IPv4 subnet:

```log
E1217 19:11:30.524462 1527044 gateway_linux.go:799] failed to create iptables rule "-m comment --comment ovn-subnet-gateway,g-g2-c2-ares-dualstack-ipv4 -s 10.100.21.0/24": running [/usr/local/sbin/ip6tables -t filter -C FORWARD -m comment --comment ovn-subnet-gateway,g-g2-c2-ares-dualstack-ipv4 -s 10.100.21.0/24 --wait]: exit status 2: ip6tables v1.8.10 (legacy): host/network `10.100.21.0' not found
```

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: g-g2-c2-ares-dualstack-ipv4
spec:
  cidrBlock: 10.100.21.0/24
  default: false
  enableLb: true
  excludeIps:
  - 10.100.21.1
  gateway: 10.100.21.1
  gatewayNode: ""
  gatewayType: distributed
  namespaces: []
  natOutgoing: true
  private: false
  protocol: IPv4
  provider: ovn
  vpc: ovn-cluster
```

### Steps To Reproduce

Creates an IPv4 subnet in a dual-stack cluster.

### Current Behavior

kube-ovn-cni executes ip6tables to add a rule in the FORWARD chain.

### Expected Behavior

Do not create ip6tables rules for the IPv4 subnet.
