### ISSUE TITLE
[BUG] 跨主机容器无法互相访问，geneve设备上没有抓到回包

### ISSUE THREAD

**Issue by zghyy** [kubeovn/kube-ovn#4881]
### Kube-OVN Version

v1.12.11

### Kubernetes Version

```shell
[root@infra-arm-master0001 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:17:29Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/arm64"}
```

### Operation-system/Kernel Version

```shell
[root@infra-arm-master0001 ~]# awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release
"CentOS Linux 7 (AltArch)"
[root@infra-arm-master0001 ~]# uname -r
4.18.0-193.28.1.el7.aarch64
```

### Description

跨主机的Pod无法互通，目前排查下来发现主机之间的geneve隧道这块可能存在问题，因为节点上ovn0网卡的join-cluster网络也不通，但是网关能通

### Steps To Reproduce

当前环境有创建provider-networks，并创建了一个Subnet给kubevirt，用于分配underlay的IP。目前准备用ovn-default这个池来创建overlay的容器(非VM)使用
1. 由于给kubevirt分配时通过net-attach-def指定了multus的资源，所以创建了新的net-attach-def
```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: ovn-overlay
  namespace: default
spec:
  config: '{ "cniVersion": "0.3.0", "type": "kube-ovn", "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
    "provider": "ovn-overlay.default.ovn" }'
```
2. 创建了两个Deployment并指定其使用该net-attach-def来分配网络
```yaml
以上省略...
template:
      metadata:
        annotations:
          ovn-overlay.default.ovn.kubernetes.io/logical_switch: ovn-default
          v1.multus-cni.io/default-network: default/ovn-overlay
        creationTimestamp: null
        labels:
          app: nginx-deployment
      spec:
        containers:
        - image: library/nginx:1.21
          imagePullPolicy: IfNotPresent
          name: nginx
以下部分省略....
```

### Current Behavior

<img width="1563" alt="image" src="https://github.com/user-attachments/assets/887513de-8ec2-410d-b7fe-a8f42b344531" />
我准备使用ovn-default来创建容器使用时发现容器无法互相ping通。因为默认的网络使用了geneve隧道方案，所以尝试两台主机之间访问join-cluster这个网络也不通。（有尝试过抓对应的geneve网卡，没有抓到回包

### Expected Behavior

节点之间可以通过join-cluster这个网络互通，节点上ovn-default分配的容器也能正常互相访问
