### ISSUE TITLE
[Feature Request] Allow underlay external subnet to custom VPC without making default external network mandatory

### ISSUE THREAD

**Issue by abasitt** [kubeovn/kube-ovn#4888]
### Description

I am following this [guide](https://kubeovn.github.io/docs/stable/en/advance/ovn-eip-fip-snat/) to attach a unique external underlay subnet to a custom VPC. But seems like it is only possible to make it work if we have default external subnet defined. 
In the custom VPC, there is an option to add extraExternalSubnets but no option to exclude default external network. 

I think we should have option.

- No dependency on default external network for custom vpc. User should be able to define and attach external underlay network to custom VPC without modifying kube-controller and cni to add default external network first.
- Able to add extraExternalSubnets and can exclude default external network.

My use-case is assign different vlans to different VPC as external networks and I want to isolate. I was able to workaround this by creating a dummy vlan as default external network. 

E.g.
My goal is to add a custom externalsubnet to a custom vpc101.

If i make enablexternal:false and just leave addexternalsubnet, nothing gets added.
```
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: vpc101
spec:
  namespaces:
  - vpc101
  enableExternal: false # want to exclude default external network external204
  extraExternalSubnets: # want to include custom external network unique to this vpc
  - external
---
kubectl ko nbctl show vpc101
router 2f8ddb7c-bf8f-4193-b7da-6f87d1891643 (vpc101)
    port vpc101-vpc101-subnet1
        mac: "7a:e8:95:37:bd:28"
        networks: ["192.168.0.1/24"]
```

If I change enableexternal:true and addextraexternal subnet will add both default and additional extra subnet.
```
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: vpc101
spec:
  namespaces:
  - vpc101
  enableExternal: true
  extraExternalSubnets:
  - external
---
kubectl ko nbctl show vpc101
router 2f8ddb7c-bf8f-4193-b7da-6f87d1891643 (vpc101)
    port vpc101-external204
        mac: "0e:0e:8a:00:c2:c9"
        networks: ["10.5.204.103/24"]
        gateway chassis: [0fb6cd0a-9801-4870-9557-067070358015]
    port vpc101-vpc101-subnet1
        mac: "7a:e8:95:37:bd:28"
        networks: ["192.168.0.1/24"]
    port vpc101-external
        mac: "86:e9:20:8d:18:4d"
        networks: ["10.9.129.152/16"]
        gateway chassis: [0fb6cd0a-9801-4870-9557-067070358015]
```

**Comment by bobz965** [comment]
Thanks four you info, I will try to make it.

**Comment by romanprog** [comment]
Hi
We’re running kube-ovn in OVN EIP FIP mode for a multitenant project with numerous VPCs. The main issue we face is that VPC creation automatically allocates an address from the default external network. We are waiting for a solution. Thank you.

**Comment by zbb88888** [comment]
@romanprog Hi, i will try to make it in these two weeks

**Comment by zbb88888** [comment]
https://github.com/kubeovn/kube-ovn/pull/5268

**Comment by zbb88888** [comment]
> Thank you [@zbb88888](https://github.com/zbb88888)

I will add some e2e later

**Comment by abasitt** [comment]
@zbb88888 will these changes allow to me to use logical port for default vpc ovn egress also ? ..
e.g. https://kubeovn.github.io/docs/v1.13.x/en/vpc/ovn-eip-fip-snat/ expect a physical nic and create a br-external using that physical link. If i try to provide a logical link e.g. vlan, it will throw error that link not found. I think it will be great if it works like additional network and works with logical links also ?

I have a single node cluster and to emulate external-network, i had to manually add veth pair like this :(

> ip link add ovs-ext1 type veth peer name ovs-ext2
>  ip link add set ovs-ext1 up
>  ip link set ovs-ext1 up
>  ip link set ovs-ext2 up

and then add the link to the provider network using ovs-vsctl command on the gateway node. e.g.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  external-gw-nodes: "external-node1,external-node2"
  external-gw-nic: "ovs-ext2"
```

**Comment by zbb88888** [comment]
I think you can create a tap on the  node, and then plug it into br-external. 
I tested this in the `provider-network vlan subnet` way.

**Comment by abasitt** [comment]
Can you share an example please?

**Comment by abasitt** [comment]
Thank you. I think this is fine. The problem is with ovn eip expecting a dedicated nic on the physical host instead of using logical port. Let's say i want to use vlan0 as external network e.g. your example with below.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  external-gw-nodes: "external-node1,external-node2"
  external-gw-nic: "vlan0"
```

The kube-ovn-cni pod will complain, vlan0 doesn't exist on the host.. I may be able to create a different tap0 interface dedicated for external may be? e.g. tap1 ? is that what are you suggesting ?
