### ISSUE TITLE
[Feature Request] Provide option to disable default gateway creation or set handling precedence

### ISSUE THREAD

**Issue by tz1112** [kubeovn/kube-ovn#4966]
### Description

In the declaration of a subnet, a gateway can be specified manually. If no value is set for the gateway parameter, the first valid IP address of the specified subnet range seems to be allocated to establish cluster-internal connectivity by default (e.g.: given CIDR 192.168.100.0/24, 192.168.100.1 is allocated unless specified otherwise). In some use cases, manual handling of the gateway is required (for example for integration of custom routing procedures  or custom ovn-handling). In these cases it would be helpful to disable the allocation of the default gateway IP, for example by providing an option to set field subnet.spec.gateway to None. Alternatively, it would be helpful to set precedence to custom resources with the same IP as the gateway. Consider the following scenario: If the gateway is set to a specific IP (e.g. 192.168.100.254) and a custom resource in the network is using the same address, network traffic does never reach the custom resource (as traffic is routed to the gateway). For some custom routing procedures, traffic being forwarded to the custom resource is required.  
The current workaround in our project is to handle custom routing by propagating an arbitrary gateway to all hosts in the subnet manually, nevertheless the default gateway is still created (either at subnet.spec.gateway or the default .1 address) and responds to requests. This is automatically detected by some applications, which leads to interference with our production workflow. It would help us a lot if there was an option to disable the gateway creation entirely or forward all traffic to a custom resource with the same IP address as the gateway. See the minimal example below with further explanations for details.

### Who will benefit from this feature?

People with custom cluster-internal routing requirements

### Anything else?

Minimum example:

```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: example-subnet
spec:
  protocol: IPv4
  provider: example.default.ovn
  cidrBlock: 192.168.100.0/24
  gateway: 192.168.100.254/24   // if no gateway is set here, 192.168.100.1 is allocated as default gateway. If the gateway is set to 192.168.100.254 and we place our custom router at that IP, the ovn-controller responds instead of our custom router, breaking the workflow
  excludeIps:
  - 192.168.100.0..192.168.100.10
  namespaces:
  - example-namespace

---

apiVersion: v1
kind: Pod
metadata:
  name: host
  namespace: example-namespace
  annotations:
    ovn.kubernetes.io/ip_address: 192.168.100.222
    ovn.kubernetes.io/routes: |
          [{
            "gw": "192.168.100.254"   // curently, a custom router is placed at this address. Nevertheless, the default gateway at 192.168.100.1 is created and responds to requests
          }]
spec:
  containers:
  - name: host
    image: docker.io/library/nginx:alpine
```

**Comment by zhangzujian** [comment]
We can add routes in the subnet CRD like this:

```yaml
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: example-subnet
spec:
  protocol: IPv4
  provider: example.default.ovn
  cidrBlock: 192.168.100.0/24
  gateway: 192.168.100.1
  excludeIps:
  - 192.168.100.0..192.168.100.10
  namespaces:
  - example-namespace
  routes:
  - dst: 0.0.0.0/0
    gw: 192.168.100.254
  - dst: 1.1.1.0/24
    gw: 192.168.100.1
```

Routes specified in the `.spec.routes` field will be automatically configured in the pods.

What do you think about this implementation?

**Comment by tz1112** [comment]
Thank you very much for your quick response.

Your suggestion is very well-suited to our specific requirements, thank you! It would make a lot of manual route tweaking obsolete in our current environment. 

If I may add an additional request: we have not found a reliable way to modify a pods DNS server using manifests yet. In the pod annotations, label k8s.v1.cni.cncf.io/network-status specifies a DNS entry, but this value never gets populated. By default, the ovn.kubernetes.io/* labels do not contain a DNS entry either; adding this value manually does not seem to have any effect (which was expected, just an educated guess on our side). From my perspective, adding a DNS entry in the subnet CDR would be a very helpful addition, to support use cases where a custom DNS resolver in a subnet should be queried. I think simple substitution or addition to preexisting values in /etc/resolv.conf (or comparable config files of similar services) *should* be sufficient.  
If there are existing approaches to this problem already which we have missed so far or if you want me to create a dedicated issue for this feature request, please let me know. 


Suggested CRD addition (.spec.dns)
```
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: example-subnet
spec:
  protocol: IPv4
  provider: example.default.ovn
  cidrBlock: 192.168.100.0/24
  gateway: 192.168.100.1
  dns: 192.168.100.1
  excludeIps:
  - 192.168.100.0..192.168.100.10
  namespaces:
  - example-namespace
  routes:
  - dst: 0.0.0.0/0
    gw: 192.168.100.254
  - dst: 1.1.1.0/24
    gw: 192.168.100.1
``` 

Thanks again for your great support so far!
