### ISSUE TITLE
[BUG] when kube-ovn deployed in underlay mode, networkpolicy does not work.

### ISSUE THREAD

**Issue by thomasnew** [kubeovn/kube-ovn#5043]
### Kube-OVN Version

v1.13.1-stable

### Kubernetes Version

Client Version: v1.28.15
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.15

### Operation-system/Kernel Version

ubuntu@a-master-1:~/yaml$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### Description

配置：

1. 创建两个pod A，pod B，其中pod A起一个service A（clusterIP，端口为80）；
2. pod B 上打label ： tag=client
3. pod A上打label： tag=frontend
4. 在设置了如下的networkpolicy，policy中没有放开 80端口和8000端口；

在pod B中访问service A 80 和“pod A port 8000 ” ，都可以访问成功；

```yaml
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: client-workloads
  namespace: default
spec:
  podSelector:
    matchLabels:
      tag: client
  egress:
    - ports:
        - port: 443
          protocol: TCP
        - port: 8443
          protocol: TCP
      to:
        - podSelector:
            matchLabels:
              tag: frontend
  policyTypes:
    - Egress
```

### Steps To Reproduce

1. 创建两个pod A，pod B，其中pod A起一个service A（clusterIP，端口为80）；
2. pod B 上打label ： tag=client
3. pod A上打label： tag=frontend
4. 在设置了如下的networkpolicy，policy中没有放开 80端口和8000端口；

### Current Behavior

可以访问成功

### Expected Behavior

在networkpolicy中未放开80和8000端口情况下，不能访问成功。
