### ISSUE TITLE
[BUG] layer2_forward have no effect

### ISSUE THREAD

**Issue by kvaps** [kubeovn/kube-ovn#5061]
### Kube-OVN Version

v1.13.2

### Kubernetes Version

v1.30.3

### Operation-system/Kernel Version

6.12.9-talos

### Description

`ovn.kubernetes.io/layer2_forward=false` is not blocking egress traffic from pod with wrong source-ip.
I guess the default behavior should block it?

### Steps To Reproduce

1. Install Kube-OVN and Cilium in chaining mode
2. Disable `enable-source-ip-verification` option in cilium (details https://github.com/cilium/cilium/issues/33889)
3. Create VM:

```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: virtual-machine-vpn-test
  namespace: tenant-kvaps
spec:
  dataVolumeTemplates:
  - metadata:
      name: virtual-machine-vpn-test
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 30Gi
        storageClassName: replicated
        volumeMode: Block
      source:
        http:
          url: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img
  running: true
  template:
    metadata:
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
        ovn.kubernetes.io/layer2_forward: "true"
    spec:
      accessCredentials:
      - sshPublicKey:
          source:
            secret:
              secretName: virtual-machine-vpn-test-ssh-keys
      architecture: amd64
      domain:
        devices:
          disks:
          - disk:
              bus: scsi
            name: systemdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - name: default
        machine:
          type: q35
      networks:
      - name: default
      terminationGracePeriodSeconds: 30
      volumes:
      - dataVolume:
          name: virtual-machine-vpn-test
        name: systemdisk
      - cloudInitNoCloud:
          secretRef:
            name: virtual-machine-vpn-test-cloud-init
        name: cloudinitdis
```

4. Exec into this VM and enable forwarding:

```
sysctl -w net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o enp1s0 -j MASQUERADE
```

5. Get IP for this virtual machine

Create pod with the custom route:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-routes
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        ovn.kubernetes.io/routes: |
          [{
            "gw": "10.244.6.136"
          }]
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:alpine
```

6. Exec into this pod

```
kubectl exec -ti custom-routes-6ffbd9b6fd-cpmnd -- sh
```

7. Try accessing external network

```
ping 8.8.8.8
curl icanhazip.com
```

It will be working.

8. Now edit VM and remove this annotation:

```yaml
ovn.kubernetes.io/layer2_forward: "true"
```

9. Restart the VM

```
virtctl stop virtual-machine-vpn-test
virtctl start virtual-machine-vpn-test
```

7. Try accessing external network from the pod again

```
ping 8.8.8.8
curl icanhazip.com
```

It is still working

### Current Behavior

You can access the external network from pod via VM in both ways:

- `ovn.kubernetes.io/layer2_forward` set to `true`
- `ovn.kubernetes.io/layer2_forward` set to `false` or unspecified

### Expected Behavior

You should not be able to do this, until `ovn.kubernetes.io/layer2_forward` set to `true`.

As virtual machine forward packets with external source-ip.

```bash
# pod starts pinging 8.8.8.8
15:54:21.739219 fa13882615d1_h P   IP 10.244.6.163 > 8.8.8.8: ICMP echo request, id 146, seq 0, length 64
# packet comming to the router vm
15:54:21.742666 a7a63286962b_h Out IP 10.244.6.163 > 8.8.8.8: ICMP echo request, id 146, seq 0, length 64
# router vm masquerades it
15:54:21.743652 a7a63286962b_h P   IP 10.244.6.136 > 8.8.8.8: ICMP echo request, id 146, seq 0, length 64
# then packet coming outside
15:54:21.744846 ovn0  In  IP 10.244.6.136 > 8.8.8.8: ICMP echo request, id 146, seq 0, length 64
15:54:21.744912 bond0.200 Out IP 91.223.132.53 > 8.8.8.8: ICMP echo request, id 146, seq 0, length 64
15:54:21.744915 bond0 Out IP 91.223.132.53 > 8.8.8.8: ICMP echo request, id 146, seq 0, length 64
15:54:21.744921 eno12399np0 Out IP 91.223.132.53 > 8.8.8.8: ICMP echo request, id 146, seq 0, length 64
# response recieved by the node
15:54:21.757117 enp139s0f1np1 In  IP 8.8.8.8 > 91.223.132.53: ICMP echo reply, id 146, seq 0, length 64
15:54:21.757121 bond0 In  IP 8.8.8.8 > 91.223.132.53: ICMP echo reply, id 146, seq 0, length 64
15:54:21.757124 bond0.220 In  IP 8.8.8.8 > 91.223.132.53: ICMP echo reply, id 146, seq 0, length 64
15:54:21.757157 ovn0  Out IP 8.8.8.8 > 10.244.6.136: ICMP echo reply, id 146, seq 0, length 64
# node sends it back to router vm
15:54:21.758012 a7a63286962b_h Out IP 8.8.8.8 > 10.244.6.136: ICMP echo reply, id 146, seq 0, length 64
# router vm sends it back to the pod
15:54:21.758514 a7a63286962b_h P   IP 8.8.8.8 > 10.244.6.163: ICMP echo reply, id 146, seq 0, length 64

<it should drop it right here>
```

**Comment by zhangzujian** [comment]
This option works as expected because it does nothing but adding an `unknown` address to the logical switch port. It does not affect layer 3 and above.

I think what you need is a security function such as network policy.

**Comment by kvaps** [comment]
I just tried to enable `ovn.kubernetes.io/port_security=true`, and my config turned to:

```yaml
_uuid               : e23d02c8-af3d-4aea-8009-d93a82559f93
addresses           : ["c2:98:0b:74:43:0a 10.244.6.136", unknown]
dhcpv4_options      : []
dhcpv6_options      : []
dynamic_addresses   : []
enabled             : []
external_ids        : {ls=ovn-default, pod="tenant-kvaps/virtual-machine-vpn-test", vendor=kube-ovn}
ha_chassis_group    : []
mirror_rules        : []
name                : virtual-machine-vpn-test.tenant-kvaps
options             : {}
parent_name         : []
port_security       : ["c2:98:0b:74:43:0a 10.244.6.136"]
tag                 : []
tag_request         : []
type                : ""
up                  : true
```

This way it does not allow vm to send packets not related to `10.244.6.136`.

1. Souldn't

```
ovn.kubernetes.io/layer2_forward: "true"
ovn.kubernetes.io/port_security: "true"
```

also update port_security to this:

```yaml
port_security       : ["c2:98:0b:74:43:0a 10.244.6.136", unknown]
```

2. Is there any way to enable pod_security for all, except specific pods?
