### ISSUE TITLE
[Feature Request] Ability to configure ovn.kubernetes.io/routes per namespace

### ISSUE THREAD

**Issue by kvaps** [kubeovn/kube-ovn#5062]
### Description

Hello, it would be nice to configure common routes for all pods in namespace, by adding global annotation in namespace object:

```yaml
    ovn.kubernetes.io/routes: |
      [{
        "gw": "10.244.6.136"
      }]
```
