### ISSUE TITLE
[BUG] False positive GC lost LSP errors for multus VMs

### ISSUE THREAD

**Issue by cruickshankpg** [kubeovn/kube-ovn#5087]
### Kube-OVN Version

v1.13.4

### Kubernetes Version

v1.28.6

### Operation-system/Kernel Version

"Ubuntu 22.04.5 LTS" 6.8.0-47-generic

### Description

We get worrying errors from GC for almost all of our VMs instructing us to delete the pod and recreate:

```
2025-03-19T09:14:58.248257369Z stderr F E0319 09:14:58.247743       7 gc.go:430] lsp lost for pod vm-a.test-ns, please delete the pod and retry
```

The VM pod does still actually have network connectivity and its LSP and IP but they are under different names that have the multus provider suffix.

```
 $k get ip  vm-a.test-ns.subnet-a.test-ns.ovn
NAME                                V4IP       V6IP   MAC                 NODE                  SUBNET
vm-a.test-ns.subnet-a.test-ns.ovn   10.0.0.2          6a:54:77:54:67:1c   sto-1-a-bm-a1-rvffq   subnet-a

$k ko nbctl list logical_switch_port vm-a.test-ns.subnet-a.test-ns.ovn
_uuid               : ecfd2080-dec1-4490-9a91-c6f503b76093
addresses           : ["6a:54:77:54:67:1c 10.0.0.2"]
dhcpv4_options      : []
dhcpv6_options      : []
dynamic_addresses   : []
enabled             : []
external_ids        : {associated_sg_default-securitygroup="false", ls=subnet-a, pod="test-ns/vm-a", vendor=kube-ovn}
ha_chassis_group    : []
mirror_rules        : []
name                : vm-a.test-ns.subnet-a.test-ns.ovn
options             : {}
parent_name         : []
port_security       : []
tag                 : []
tag_request         : []
type                : ""
up                  : true
```

Our VMs do not use the default network and instead use multus provided networks so no LSP is created with format `${name}.${namespace}` so I think these errors are benign but did scare some of our engineers :) We don't see these logs for VMs that get created in the default network.

I think this is because https://github.com/kubeovn/kube-ovn/blob/master/pkg/controller/gc.go#L971-L972 unconditionally adds the `util.OvnProvider` format LSP to check.

### Steps To Reproduce

this assumes kubevirt is installed

1. create subnet and network-attachment-definition with matching providers
2. create VM that uses subnet :
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-a
  namespace: test-ns
spec:
  running: true
  template:
    spec:
      ...
        devices:
          interfaces:
          - bridge: {}
            name: default
      networks:
      - multus:
          default: true
          networkName: test-ns/subnet-a
        name: default
      ...
```
3. Wait for 6 minutes for GC to happen and then check kube-ovn-controller logs

### Current Behavior

LSP lost for pod errors are raised by GC for LSPs that never existed

### Expected Behavior

no errors raised
