### ISSUE TITLE
[BUG] unable to route LoadBalancer traffic to underlay pods

### ISSUE THREAD

**Issue by patriziobassi** [kubeovn/kube-ovn#5112]
### Kube-OVN Version

v1.12.6

### Kubernetes Version

v1.30

### Operation-system/Kernel Version

"Ubuntu 22.04.4 LTS"
5.15.0-126-generic

### Description

we have a setup where k8s workers have 3 different nics:

1) management nic (ens3), with the default gw, used for ssh for instance
2) podnet, used by kube-ovn for underlay traffic for pods
3) vipnet, used by metallb to announce LoadBalancer IPs and receive traffic.

when an external client connects to the LB ip, it get correctly routed to the K8s worker announcing the traffic (externalTrafficPolicy Local/Cluster).
Metallb configure ipvs to route to the underlay pod address correctly, but then the traffic gets lost.

with tcpdump we see the traffic like this:

17:26:58.994530 vipnet In  IP <externalclientIP>.42144 > <loadbalancerIP>.6379: Flags [S], seq 1139930890, win 35840, options [mss 8960,sackOK,TS val 435725208 ecr 0,nop,wscale 9], length 0
17:26:58.994637 ens3  Out IP <k8sworker IP on ens3>.11999 > <underlay pod ip>.6379: Flags [S], seq 1139930890, win 35840, options [mss 8860,sackOK,TS val 435725208 ecr 0,nop,wscale 9], length 0

So the worker doesn't have a rule to route the traffic to the "podnet" interface which is the interface kube-ovn knows and uses to allocate IPs to pods and thus forwards to the ens3 interface where the worker has the default gateway: basically the traffic is leaving the worker instead of being processed internally. so it's lost.

When using the LoadBalancer with POD in the overlay network we *do not* get this problem because the kernel routing table already has ovn0 interface:
<ovn-default network> via 100.64.0.1 dev ovn0 src <k8sworker IP on ens3>
100.64.0.0/16 dev ovn0 proto kernel scope link src 100.64.0.5

If we manually try to add a routing rule with "ip r add ....." kube-ovn-cni will immediately delete it.

How to add a "sink" in kube-ovn in order to catch with traffic with underlay networks too?

thank you

### Steps To Reproduce

.

### Current Behavior

.

### Expected Behavior

.

**Comment by zbb88888** [comment]
did you use the "U2O" function?

**Comment by changluyi** [comment]
https://github.com/kubeovn/kube-ovn/pull/4894

This pr may help you solve the underlay + metallb scenario

**Comment by patriziobassi** [comment]
> did you use the "U2O" function?

Yes we do

**Comment by patriziobassi** [comment]
> [#4894](https://github.com/kubeovn/kube-ovn/pull/4894)
> 
> This pr may help you solve the underlay + metallb scenario

Thank you! 
Will It be backported to 1.12 branch?

**Comment by patriziobassi** [comment]
> > Will It be backported to 1.12 branch?
> 
> [@patriziobassi](https://github.com/patriziobassi) This is a significant change affecting both the data plan and the control plan, so we will not backport it to the stable release.

@oilbeater i see. i understood the 1.13 branch was the stable one too. So can we expect this fix to land in the 1.13.x branch or is it targetting 1.14x?

thank you a lot

**Comment by oilbeater** [comment]
@patriziobassi you are right, 1.13 is also a stable branch, we will only land this fix to 1.14.

**Comment by patriziobassi** [comment]
@oilbeater before closing it i would like to test. which release is already shipping the fix? just master, is there any 1.14.x release?

**Comment by oilbeater** [comment]
@patriziobassi we plan to release v.1.14.0 next month.

**Comment by patriziobassi** [comment]
> [@patriziobassi](https://github.com/patriziobassi) we plan to release v.1.14.0 next month.

ok, i see in dockerhub there is already a build with that tag, i may give a try so, in case it doesn't work, i may report and maybe get it fixed.


btw in the installation guide i still see reference to 1.13
https://kubeovn.github.io/docs/v1.14.x/en/start/underlay/#download-script but for sure it will be fixed when the release is officially out.

**Comment by patriziobassi** [comment]
Hi @oilbeater 

can you please reopen this issue?

i saw a new documentation regarding metallb and underlay
https://kubeovn.github.io/docs/v1.14.x/en/advance/with-metallb/ where the requisite is to expose via LoadBalancer objects the same interface and subnet (of course with excludeIps) of the underlay subnet.

in our case we wanted to have a dedicated interface (let's call it vipnet) for LoadBalancer IPs and for underlay pods.

I wonder that's a way to make the traffic from the vipnet to the br-provider bridge in order to reach the pods.

thanks

**Comment by patriziobassi** [comment]
Thank you for reopening!

so let me share the layout:

a worker node that 3 interfaces:
Thank you for reopening!

so let me share the layout:

a worker node that 3 interfaces:

1) ens3: for management (ssh) and used by kubeovn for ovn0 and geneve traffic
2) podnet: from linux point of view it is unnumbered, it's just configured up, and it is the underlay subnet we configure in kubeovn 

```
---                                                                                                                                                              
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: pod-provnet
spec:
  defaultInterface: podnet
---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: pod-vlan
spec:
  id: 0
  provider: pod-provnet
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: pod-subnet
spec:
  cidrBlock: 10.xx.xx.0/24
  gateway: 10.xx.xx.1
  vlan: pod-vlan
  protocol: IPv4
  default: false
  excludeIps:
    - 10.xx.xx.1..10.xx.xx.10
  private: false
  gatewayType: distributed
  natOutgoing: false
  disableGatewayCheck: true
  u2oInterconnection: true
  u2oInterconnectionIP: 10.xx.xx.2
```

3) vipnet
as for podnet, it looks unnumbered from linux main routing and it's configured only in metal lb to annouce LoadBalancer IPs. It it also unknown to kube-ovn.

then in order to route the traffic we used policy based routing in linux (ubuntu) to perform:

```
100.64.0.0/16 is the default ovn0 
10.252.0.0/16 is the overlay pod network

we have the route managed by kubeovn
10.252.0.0/16 via 100.64.0.1 dev ovn0 src 10.xxxx.xxxx.xxx
100.64.0.0/16 dev ovn0 proto kernel scope link src 100.64.0.8

#ip rule show
0:      from all lookup local
98:     from <vipnet-cidr> to 100.64.0.0/16 lookup main
99:     from <vipnet-cidr> to 10.252.0.0/16 lookup main
100:    from <vipnet-cidr> to <podnet-cidr> lookup main
101:    from <vipnet-cidr> lookup k8slb
32766:  from all lookup main
32767:  from all lookup default
```


When we expose a pod in overlay using a LoadBalancer service it works: k8s leverages a ipvs entry to route the traffic gets routed to the overlay network.
When we expose a pod in underlay the traffic gets to the pod (we could see it with tcpdump), the pod replies with a SYN ACK, which gets lost.

So taking the idea from the documentation for 1.14 metallb integration we may declare the "vipnet" as a kubeovn subnet/cidr, excluding all the IPs would be used by metallb but then we need a patch/link to route the traffic from vipnet to podnet and viceversa.

if something unclear, please ask and i will provide more details
