### ISSUE TITLE
[BUG] Distributed type external gateway not work

### ISSUE THREAD

**Issue by donghee-park-rsk** [kubeovn/kube-ovn#5272]
### Kube-OVN Version

v1.13.4

### Kubernetes Version

v1.31.6

### Operation-system/Kernel Version

Rocky Linux 8.9 (Green Obsidian)

### Description

I set underlay network like below.
(refered  [https://kubeovn.github.io/docs/stable/en/vpc/ovn-eip-fip-snat/](url) )
```
apiVersion: kubeovn.io/v1
kind: ProviderNetwork
metadata:
  name: external0
spec:
  defaultInterface: eth0
---
apiVersion: kubeovn.io/v1
kind: Vlan
metadata:
  name: vlan0
spec:
  id: 0
  provider: external0
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: external0
spec:
  protocol: IPv4
  cidrBlock: 10.9.0.0/16
  gateway: 10.9.0.1
  vlan: vlan0
  excludeIps:
    - 10.9.0.1..10.9.220.20
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ovn-external-gw-config
  namespace: kube-system
data:
  enable-external-gw: "true"
  external-gw-nodes: "vnode-117-74,vnode-117-75"        # gateway node name
  type: "distributed"
  external-gw-nic: "eth0"
  external-gw-addr: "10.9.0.1/16"
```

And then set the overlay network.
(refered [https://kubeovn.github.io/docs/stable/en/vpc/ovn-l3-ha-based-ecmp-with-bfd/](url) )
nodes eip
```
kind: OvnEip
apiVersion: kubeovn.io/v1
metadata:
  name: vnode-117-74
spec:
  externalSubnet: external0
  type: lsp

---
kind: OvnEip
apiVersion: kubeovn.io/v1
metadata:
  name: vnode-117-75
spec:
  externalSubnet: external0
  type: lsp
```

```
apiVersion: v1
kind: Namespace
metadata:
  name: vpc1
---
kind: Vpc
apiVersion: kubeovn.io/v1
metadata:
  name: vpc1
spec:
  namespaces:
  - vpc1
  enableExternal: true
  enableBfd: true # bfd switch can be switched at will
  #enableBfd: false 
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: vpc1-subnet1
spec:
  cidrBlock: 192.168.0.0/24
  default: false
  disableGatewayCheck: false
  disableInterConnection: true
  enableEcmp: true  # enable ecmp
  gatewayNode: ""
  gatewayType: distributed
  #gatewayType: centralized
  natOutgoing: false
  private: false
  protocol: IPv4
  provider: ovn
  vpc: vpc1
  namespaces:
  - vpc1
```

Then create the pod at vnode-117-75 and oeip, ofip for that pod.
I want this pod work with its node since I set vnode-117-75 to distributed type external gateway.
* But it go through vnode-117-74.

* Also, when I shutdown vnode-117-74, pod cannot reach outside network.

### Steps To Reproduce

1. Set underlay network
2. Set overlay network and bind to external network.
3. Create pod and test networking

### Current Behavior

Not distribute the gateway

### Expected Behavior

Distributed external gateway
