### ISSUE TITLE
[BUG] KubeVirt VMs (virt-launcher pods) do not get traffic from VIPs defined as SwitchLBRule

### ISSUE THREAD

**Issue by morete** [kubeovn/kube-ovn#5337]
### Kube-OVN Version

v1.13.3

### Kubernetes Version

v1.30.0

### Operation-system/Kernel Version

Ubuntu 22.04.5 LTS   5.15.0-134-generic
containerd://1.7.23

### Description

Considerations:
- We are using Kube-OVN with custom VPCs.
- We can reproduce it on 2 different environments running same OS/Kernel/Kubernetes/containerd/Kube-OVN versions.

Creating a `SwitchLBRule` with label selector matching KubeVirt VM pods (virt-launcher) get the correct `Endpoints` defined in K8S and in OVN NB DB including the health check definition in OVN NB DB but it never gets a Service Monitor defined in OVN SB DB, if I create a regular "netshoot" pod matching same labels it is added to the VIP backends and it actually gets the service monitor defined in OVN SB DB. So KubeVirt VMs cannot be targeted as VIP backends.

### Steps To Reproduce

* Create namespace : tenant-3
* Create vpc: tenant-3
* Create subnet: tenant-3-mgmt
* Create 2 VMs looking like:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu-host-01
  namespace: tenant-3
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: ubuntu-host-01
      namespace: tenant-3
    spec:
      source:
        registry:
          pullMethod: node
          url: docker://quay.io/containerdisks/ubuntu:22.04
      storage:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
        storageClassName: standard
        volumeMode: Block
  runStrategy: Always
  template:
    metadata:
      annotations:
        kubevirt.io/allow-pod-bridge-network-live-migration: "true"
        ovn.kubernetes.io/logical_switch: tenant-3-mgmt
      labels:
        cluster.x-k8s.io/cluster-name: kubernetes
        cluster.x-k8s.io/role: worker
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values:
                - south
      architecture: amd64
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
        machine:
          type: q35
        memory:
          guest: 8Gi
        resources: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: ubuntu-host-01
        name: rootdisk
      - cloudInitNoCloud:
          userData: |-
            #cloud-config

            password: ubuntu
            chpasswd: { expire: False }
            ssh_pwauth: true

            package_update: true
            package_upgrade: true
            packages:
            - qemu-guest-agent
            runcmd:
            - [ systemctl, start, qemu-guest-agent ]
        name: cloudinitdisk
  updateVolumesStrategy: Migration
```

* Create test pod:
```
$ cat vip-test-1749138104.yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ovn.kubernetes.io/logical_switch: tenant-3-mgmt
  labels:
    cluster.x-k8s.io/cluster-name: kubernetes
    cluster.x-k8s.io/role: worker
  name: vip-test-1749138104
  namespace: tenant-3
spec:
  containers:
    - command:
        - sleep
        - infinity
      image: nicolaka/netshoot
      name: vip-test-1749138104
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
```

* Define SLR:
```
apiVersion: kubeovn.io/v1
kind: SwitchLBRule
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: kubernetes
    cluster.x-k8s.io/tenant-service-name: nginx-service-2
    cluster.x-k8s.io/tenant-service-namespace: default
  name: ad9a6bacea9284bec97ca6b3cfb3715b
spec:
  namespace: tenant-3
  ports:
  - name: ""
    port: 80
    protocol: TCP
    targetPort: 30633
  selector:
  - cluster.x-k8s.io/role:worker
  - cluster.x-k8s.io/cluster-name:kubernetes
  vip: 192.168.162.99
```

SLR will create a `Service`:
```
$ kubectl get svc slr-ad9a6bacea9284bec97ca6b3cfb3715b -oyaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    ovn.kubernetes.io/switch_lb_vip: 192.168.162.99
    ovn.kubernetes.io/vpc: tenant-3
  creationTimestamp: "2025-06-05T09:50:24Z"
  name: slr-ad9a6bacea9284bec97ca6b3cfb3715b
  namespace: tenant-3
  resourceVersion: "2115867130"
  uid: 02a0c5bb-b104-490e-a92e-8ca034e16668
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 30633
  selector:
    cluster.x-k8s.io/cluster-name: kubernetes
    cluster.x-k8s.io/role: worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

`Service` will create `Endpoints`
```
$ kubectl get endpoints slr-ad9a6bacea9284bec97ca6b3cfb3715b -oyaml
apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2025-06-04T20:28:32Z"
  creationTimestamp: "2025-06-05T09:50:24Z"
  labels:
    service.kubernetes.io/headless: ""
  name: slr-ad9a6bacea9284bec97ca6b3cfb3715b
  namespace: tenant-3
  resourceVersion: "2121489702"
  uid: 9adbcab7-9523-408b-9f51-3cde5a78f0b9
subsets:
- addresses:
  - ip: 192.168.162.69
    nodeName: host2
    targetRef:
      kind: Pod
      name: virt-launcher-ubuntu-host-01-8w2tl
      namespace: tenant-3
      uid: d0d92d34-e103-48ce-92ae-97f7181d4dbd
  - ip: 192.168.162.83
    nodeName: host3
    targetRef:
      kind: Pod
      name: virt-launcher-ubuntu-host-02-jkfrn
      namespace: tenant-3
      uid: 2697930a-8e27-4ee1-b6c7-272407976d7e
  - ip: 192.168.162.86
    nodeName: host7
    targetRef:
      kind: Pod
      name: vip-test-1749138104
      namespace: tenant-3
      uid: 6d7380de-a7ce-4298-bee0-ab5c340c6f7d
  ports:
  - port: 30633
    protocol: TCP
```

* Verify pods ips and compare with `Endpoints`
```
$ kubectl get pods -o yaml | grep -i -e "^    name:" -e podIp:|grep -B1 -e 192.168.162.86 -e 192.168.162.83 -e 192.168.162.69
    name: vip-test-1749138104
    podIP: 192.168.162.86
    name: virt-launcher-ubuntu-host-01-8w2tl
    podIP: 192.168.162.69
    name: virt-launcher-ubuntu-host-02-jkfrn
    podIP: 192.168.162.83
```

* List OVN Northbound Load Balancers:
```
$ kubectl ko nbctl find load_balancer name=vpc-tenant-3-tcp-load
_uuid               : e3d0d1c4-59d8-4c48-b5a0-8b5fdfd100b3
external_ids        : {}
health_check        : [c7b93598-d159-4640-9a8b-d58fccb2a732]
ip_port_mappings    : {"192.168.162.69"="virt-launcher-ubuntu-host-01-8w2tl.tenant-3:192.168.162.79", "192.168.162.83"="virt-launcher-ubuntu-host-02-jkfrn.tenant-3:192.168.162.79", "192.168.162.86"="vip-test-1749138104.tenant-3:192.168.162.79"}
name                : vpc-tenant-3-tcp-load
options             : {}
protocol            : tcp
selection_fields    : []
vips                : {"192.168.162.99:80"="192.168.162.69:30633,192.168.162.83:30633,192.168.162.86:30633"}
```

* List OVN Northbound Load Balancer Health Checks
```
$ kubectl ko nbctl list Load_Balancer_Health_Check c7b93598-d159-4640-9a8b-d58fccb2a732
_uuid               : c7b93598-d159-4640-9a8b-d58fccb2a732
external_ids        : {switch_lb_subnet=tenant-3-mgmt}
options             : {failure_count="3", interval="5", success_count="3", timeout="20"}
vip                 : "192.168.162.99:80"
```

* List Service Monitors defined in OVN Southbound DB:
```
$ kubectl ko sbctl find service_monitor port=30633
_uuid               : dca9c53a-6680-442e-ac6a-9bfaf24075a1
chassis_name        : "46747e2a-8238-4423-8b55-8e76a603a51c"
external_ids        : {}
ip                  : "192.168.162.86”
logical_port        : vip-test-1749138104.tenant-3
options             : {failure_count="3", interval="5", success_count="3", timeout="20"}
port                : 30633
protocol            : tcp
src_ip              : "192.168.162.79"
src_mac             : "86:c8:c1:72:ae:80"
status              : online
```

At some point I also tried defining a vip in kubeovn to see if that would change something but it did not... I created it like:
```
apiVersion: kubeovn.io/v1
kind: Vip
metadata:
  name: slr-ad9a6bacea9284bec97ca6b3cfb3715b
spec:
  subnet: tenant-3-mgmt
  type: switch_lb_vip
  v4ip: "192.168.162.99"
```

### Current Behavior

Only one Service Monitor is defined in OVN Southbound DB matching the non-VM pod while the 2 VM pods are missing the Service Monitors even when considered VIP backends.

If the test pod is deleted a `kubectl ko trace` targeting the VIP returns `Datapath actions: drop`

### Expected Behavior

All 3 target pods listed as Service Endpoints and being VIP backend targets in OVN Northbound Load Balancer definition should get a Service Monitor defined in OVN Southbound DB and eventually should get traffic/requests targeting the VIP.
