### ISSUE TITLE
[Feature Request] Extend the capability of Kube-OVN for it to be used as a non-primary CNI plugin

### ISSUE THREAD

**Issue by starbops** [kubeovn/kube-ovn#5360]
### Description

The [Harvester HCI project](https://github.com/harvester/harvester) is currently undergoing a significant integration effort to incorporate Kube-OVN into its ecosystem, providing users with advanced networking features ([ref](https://github.com/harvester/harvester/issues/7397)). However, not every part of the integration plan works as smoothly as expected. We have tried very hard to overcome these issues on our side, but unfortunately, they seem to require support or changes from the upstream, i.e., in the Kube-OVN project.

Currently, we've identified several areas that could pose issues for the integration effort. These are rooted in the premise that Kube-OVN is the primary CNI plugin in a Kubernetes cluster. To name a few:

#### ovn-cni initialization failure

This was described in #5078 in detail and has already been resolved.

#### Make the default Subnet `ovn-default` optional

Since the pod network is still using the CNI plugin other than Kube-OVN, it seems unnecessary to keep the `ovn-default` Subnet. Otherwise, all the pods running on the cluster consume IP addresses from the `ovn-default` Subnet (though it does no harm actually). For instance, the pod honors the IP allocation from Canal but not Kube-OVN, leaving those Kube-OVN-generated annotations ineffective (but still occupied an IP address from the Subnet):

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 6859c02d1c3d49f74b7a4193a6f04d0b2e34a56bfa0b82ee5a0c791a3af477f0
    cni.projectcalico.org/podIP: 10.52.0.32/32   # ip allocated from canal
    cni.projectcalico.org/podIPs: 10.52.0.32/32
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "10.52.0.32"                       # the actual pod ip
          ],
          "default": true,
          "dns": {}
      }]
    ovn.kubernetes.io/allocated: "true"
    ovn.kubernetes.io/cidr: 10.52.0.0/16
    ovn.kubernetes.io/gateway: 10.52.0.1
    ovn.kubernetes.io/ip_address: 10.52.0.77     # not being used
    ovn.kubernetes.io/logical_router: ovn-cluster
    ovn.kubernetes.io/logical_switch: ovn-default
    ovn.kubernetes.io/mac_address: c6:f6:0b:86:67:10
    ovn.kubernetes.io/pod_nic_type: veth-pair
    ovn.kubernetes.io/routed: "true"
  ...
```

Whether users can delete the default Subnet `ovn-default`, or not create it at all during installation, is a question.

#### Namespace-based IP address allocation

This is the primary way Kube-OVN determines which Pod belongs to which subnet. The mechanism itself is fine when Kube-OVN is the primary CNI; the problem lies in the subsequent decision. For instance, VpcNatGateway also has the implicit premise that the instantiated gateway pod will attach to the Subnet where it is associated with through its namespace. The external network attachment relies on the NAD object, however.

![Image](https://github.com/user-attachments/assets/7cce55c1-dd55-4c60-8334-89eece75ad60)

In our case, the external network is attached, and the IP address is configured correctly, but the target tenant network we want to bridge is not, because it's getting shadowed, quite like the above case, it's just that the Subnet is not `ovn-default`:

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: cef4a827f110cf3bffaabcc77922ec0264125f9f07aa1ab4f7c3f1caa7fc385f
    cni.projectcalico.org/podIP: 10.52.0.176/32
    cni.projectcalico.org/podIPs: 10.52.0.176/32
    ext-net.kube-system.kubernetes.io/allocated: "true"
    ext-net.kube-system.kubernetes.io/cidr: 10.115.0.0/21
    ext-net.kube-system.kubernetes.io/gateway: 10.115.7.254
    ext-net.kube-system.kubernetes.io/ip_address: 10.115.0.101
    ext-net.kube-system.kubernetes.io/routes: '[{"dst":"0.0.0.0/0","gw":"10.115.7.254"}]'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "k8s-pod-network",
          "ips": [
              "10.52.0.176"
          ],
          "default": true,
          "dns": {}
      },{
          "name": "kube-system/ext-net",
          "interface": "net1",
          "ips": [
              "10.115.0.101"
          ],
          "mac": "0a:7f:3d:73:96:24",
          "dns": {},
          "gateway": [
              "10.115.7.254"
          ]
      }]
    k8s.v1.cni.cncf.io/networks: kube-system/ext-net
    ovn.kubernetes.io/allocated: "true"
    ovn.kubernetes.io/cidr: 192.168.250.0/24
    ovn.kubernetes.io/gateway: 192.168.250.254
    ovn.kubernetes.io/ip_address: 192.168.250.254
    ovn.kubernetes.io/logical_router: gamma-vpc
    ovn.kubernetes.io/logical_switch: gamma-net
    ovn.kubernetes.io/mac_address: 82:87:a2:76:4c:0f
    ovn.kubernetes.io/pod_nic_type: veth-pair
    ovn.kubernetes.io/routed: "true"
    ovn.kubernetes.io/routes: '[{"dst":"10.53.0.0/16","gw":"192.168.250.254"}]'
    ovn.kubernetes.io/vpc_cidrs: '["192.168.250.0/24"]'
    ovn.kubernetes.io/vpc_nat_gw: gateway-2011
    ovn.kubernetes.io/vpc_nat_gw_init: "true"
  ...
```

#### VPC NAT Gateway needs to support attaching to more than one NAD

This is the subsequent trial of the above case. In order to attach to the target tenant network, we tried to hack the gateway pod's annotations by modifying the created StatefulSet manually:

<img width="990" alt="Image" src="https://github.com/user-attachments/assets/4d4761ae-2575-40c1-aafc-4b5c0e7ec850" />

After that, the gateway pod indeed attached to the tenant network and had the IP address assigned, but the the gateway pod was not initialized properly:

```
vpc-nat-gw-gateway-2011-0:/kube-ovn# iptables-legacy-save -t nat
# Generated by iptables-save v1.8.11 on Fri Jun 13 08:47:13 2025
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
COMMIT
# Completed on Fri Jun 13 08:47:13 2025
```

---

I'm sure there are many more potential issues to be found. These are just something we've encountered during the integration work.

We are eager to enable these use cases and are happy to engage in discussions and contribute to the development of this initiative with developers and the community to make it happen. The plan is to extend the capabilities of Kube-OVN to be utilized as a secondary CNI plugin, and hopefully, all the proposed changes don't break any existing use cases.

Thank you for your time.

### Who will benefit from this feature?

Users who want to leverage Kube-OVN using Multus to bring more advanced networking features to their Kubernetes cluster that already incorporates another CNI plugin as the primary one.

### Anything else?

Specifically, Harvester uses Canal as its primary CNI plugin. Additionally, it utilizes Multus and the bridge CNI to enable flexible network configuration for VM workloads. To install Kube-OVN, Harvester relies on [kubeovn-operator](https://github.com/harvester/kubeovn-operator) to look after the lifecycle management of the Kube-OVN setup. After installation, the CNI configs and binaries look like the following:

```
$ ls -l {/etc/cni/net.d,/opt/cni/bin}
/etc/cni/net.d:
total 28
-rw-------  1 root root  774 Jun 13 04:38 00-multus.conf
-rw-r--r--  1 root root  769 Jun 13 04:37 10-canal.conflist
-rw-r--r--  1 root root  324 Jun 13 06:11 90-kube-ovn.conflist
-rw-r--r--. 1 root root   54 Jan 13  2020 99-loopback.conf.sample
-rw-------  1 root root 2057 Jun 13 04:37 calico-kubeconfig
drwxr-xr-x  2 root root 4096 Jun 13 04:38 multus.d
drwxr-xr-x  2 root root 4096 Jun 13 04:42 whereabouts.d

/opt/cni/bin:
total 309944
-rwxr-xr-x 1 root root  5053056 Jun 13 04:37 bandwidth
-rwxr-xr-x 1 root root  5148736 Jun 13 04:37 bond
-rwxr-xr-x 1 root root  5485088 Jun 13 04:37 bridge
-rwxr-xr-x 1 root root 49861840 Jun 13 04:37 calico
-rwxr-xr-x 1 root root 49861840 Jun 13 04:37 calico-ipam
-rwxr-xr-x 1 root root 10817408 Jun 13 04:37 dhcp
-rwxr-xr-x 1 root root  5177248 Jun 13 04:37 dummy
-rwxr-xr-x 1 root root  5513408 Jun 13 04:37 firewall
-rwxr-xr-x 1 root root  2626808 Jun 13 04:37 flannel
-rwxr-xr-x 1 root root  5128224 Jun 13 04:37 host-device
-rwxr-xr-x 1 root root  4618848 Jun 13 04:37 host-local
-rwxr-xr-x 1 root root  5193664 Jun 13 04:37 ipvlan
-rwxr-xr-x 1 root root 32678040 Jun 13 06:11 kube-ovn
-rwxr-xr-x 1 root root  4101235 Jun 13 06:11 loopback
-rwxr-xr-x 1 root root  4889956 Jun 13 06:11 macvlan
-rwxr-xr-x 1 root root 38855736 Jun 13 04:38 multus
-rwxr-xr-x 1 root root  4694781 Jun 13 06:11 portmap
-rwxr-xr-x 1 root root  5337664 Jun 13 04:37 ptp
-rwxr-xr-x 1 root root  2897040 Jun 13 04:37 sbr
-rwxr-xr-x 1 root root  2432144 Jun 13 04:37 static
-rwxr-xr-x 1 root root  5232160 Jun 13 04:37 tap
-rwxr-xr-x 1 root root  2802320 Jun 13 04:37 tuning
-rwxr-xr-x 1 root root  5189568 Jun 13 04:37 vlan
-rwxr-xr-x 1 root root  3004880 Jun 13 04:37 vrf
-rwxr-xr-x 1 root root 50720920 Jun 13 04:42 whereabouts
```
