### ISSUE TITLE
[BUG] SwitchLBRules stop working after a while when declaring VIP beforehand

### ISSUE THREAD

**Issue by SkalaNetworks** [kubeovn/kube-ovn#5377]
### Kube-OVN Version

v1.14.0

### Kubernetes Version

1.32.3 Talos

### Operation-system/Kernel Version

Talos Linux

### Description

If a SLR is created with IP X and the VIP X has been created beforehand, the SLR doesn't work reliably and inter-node loadbalancing is broken with timeouts.

### Steps To Reproduce

1. Install Kube-OVN in latest version
2. Create the following Namespace/VPC/Subnet combo

```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: test

---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: "test-subnet"
spec:
  cidrBlock: 10.0.0.0/24
  default: true
  namespaces:
    - test
  vpc: test

---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: test
spec:
  namespaces:
    - test
```
3. Create a VIP

```yaml
apiVersion: kubeovn.io/v1
kind: Vip
metadata:
  name: vip
spec:
  subnet: test-subnet
  type: switch_lb_vip
  v4ip: 10.0.0.100
```

5. Observe the VIP is created and there's 2 LSP created, one is set to virtual and one is "normal"
6. Create debug pods and targets pods
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: test
spec:
  selector:
    matchLabels:
      name: debug
  replicas: 4
  template:
    metadata:
      labels:
        name: debug
    spec:
      containers:
      - name: debug
        image: hashicorp/http-echo
        args: ["-listen", ":5555", "-text", "Welcome to $POD_HOST"]
        env:
          - name: POD_HOST
            valueFrom:
              fieldRef:
                fieldPath: metadata.name

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: helper
  namespace: test
spec:
  selector:
    matchLabels:
      name: helper
  template:
    metadata:
      labels:
        name: helper
    spec:
      containers:
      - name: debug
        image: nicolaka/netshoot
        command: ["sh", "-c", "while true; do sleep 3600; done"]
```

6. We now have pods from which we can do the requests to the LB (Helpers) and targets (Debug) that respond on port 555
7. Create the SLR
```yaml
apiVersion: kubeovn.io/v1
kind: SwitchLBRule
metadata:
  name: slr
spec:
  vip: 10.0.0.100
  sessionAffinity: ClientIP
  namespace: test
  selector:
    - name:debug
  ports:
  - name: test
    port: 5555
    targetPort: 5555
    protocol: TCP
```
8. Enter a debug pod, run curl 10.0.0.10:5555, observe it works
9. Spam a few more times, it seems like it does loadbalance
10. Wait about 2 minutes
11. Rerun the curl, observe timeouts, observe that spamming requests ends up working when the loadbalancer redirects us to a pod running on the same node as the one making the calll

### Current Behavior

VIPs for SLRs created in advance cause problems.

### Expected Behavior

VIPs can be created beforehand without problem (isn't their whole purpose to reserve the LB in the IPAM)?

**Comment by SkalaNetworks** [comment]
I'm honestly confused by the doc on what the VIPs are meant to do when declaring SLRs. I thought they were used to reserve IPs in the IPAM to avoid a possible conflict, but they actually reserve LSPs.

If the SLR is created with no VIP beforehand, it seems to work just fine. But is there no risk that a VM/Pod steals the VIP? It doesn't seem accounted in the IPAM, which means anything can take that IP and cause a conflict.

Also, when not declaring VIPs beforehand, there's no trace fo LSP/LRPs in OVN DBs, so declaring a LB + a VIP probably creates a big conflict with ARP responding to one or the other in some shape or form.

**Comment by SkalaNetworks** [comment]
It seems like VIPs are meant to not be part of any subnet within the VPC, otherwise it blows up and there's no ARP response.

So if I do this:
- Create an SLR with VIP 10.0.0.100 in Subnet 10.0.0.0/24, with target Pods and Source pods within that subnet
- Run a curl to 10.0.0.100

I get 0 response. If I set the VIP to 1.1.1.1 (outside the Subnet) it works.

But if I do this:
- Create a VIP 10.0.0.100
- Create an SLR that target VIP 10.0.0.100
- CURL
It works, but only for a few minutes before the ARP dies

**Comment by SkalaNetworks** [comment]
![Image](https://github.com/user-attachments/assets/8f33ad80-ec07-4f0f-a409-547ed88b7296)


Just found this in the OVN docs, if I understand correctly, VIP should always be outside the Subnet of the LS?

**Comment by zbb88888** [comment]
how about trying 

```bash

apiVersion: kubeovn.io/v1
kind: Vip
metadata:
  name: slr-01
spec:
  subnet: ovn-default
  type: switch_lb_vip # the VIP inside the subnet

```

**Comment by SkalaNetworks** [comment]
@zbb88888 is using the default subnet on purpose? I kinda want to only do VIPs in custom VPC/Subnets

I can try not defining an IPv4

**Comment by zbb88888** [comment]
> VIPs in custom VPC/Subnets
Please try ` type: switch_lb_vip ` in your custom VPC/Subnets.

**Comment by SkalaNetworks** [comment]
@zbb88888 I tried not specifying an IPv4. I let Kube-OVN allocate one, and then used it as the SLR's VIP. It didn't really seem to change anything. It ended up crashing the entire network of the VM, it couldn't even resolve its gateway anymore.

I noticed the name of the VIP is templated using the name of the namespace. If none is provided, it the templating seems wrong. I tried specifying a namespace in the VIP, and the name of the LSP seems better.

```yaml
apiVersion: kubeovn.io/v1
kind: Vip
metadata:
  name: vip
spec:
  subnet: spx-fd659e2f-fdf4-5c1f-8bc1-9b5eea779ddf
  namespace: spx-a970529d-c1f2-41e0-acd5-fd8e9bea117c
  type: switch_lb_vip
```

Sadly it didn't change anything, the network of the VM ended  up crashing. Deleting the SLR/VIP immediatly restores connectivity to the VM.

I'm tring to find a reliable way to trigger the bug. I'm unsure if it's linked to Kube-OVN's GC or to OVN. I'm also unsure why we generate an LSP with the same MAC as the LRP.

One VIP set with option `switch_lb_vip` will both generate an LSP connected to the router, and a virtual LSP.
