### ISSUE TITLE
Multi-nic Kube-ovn issue

### ISSUE THREAD

**Issue by tarun28jain** [kubeovn/kube-ovn#604]
Hi,

We are trying to add multiple interfaces to the pod following the documentation "https://github.com/alauda/kube-ovn/blob/release-1.2/docs/multi-nic.md"
Installed Kubeovn 1.2 on my K8s setup and defalt interface is working correctly.
Then as suggested in documentation, i created a macvlan type of NetworkAttachmentDefinition and created a subnet

```
# kubectl describe net-attach-def macvlan
Name:         macvlan
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  k8s.cni.cncf.io/v1
Kind:         NetworkAttachmentDefinition
Metadata:
  Creation Timestamp:  2020-12-16T08:12:40Z
  Generation:          1
  Managed Fields:
    API Version:  k8s.cni.cncf.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:config:
    Manager:         kubectl
    Operation:       Update
    Time:            2020-12-16T08:12:40Z
  Resource Version:  2198997
  Self Link:         /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/macvlan
  UID:               18709db9-e688-41ee-aa2d-33599fcaad57
Spec:
  Config:  { "cniVersion": "0.3.0", "type": "macvlan", "master": "eth0", "mode": "bridge", "ipam": { "type": "kube-ovn", "server_socket": "/run/openvswitch/kube-ovn-daemon.sock", "provider": "macvlan.default" } }


# kubectl describe subnet macvlan
Name:         macvlan
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  kubeovn.io/v1
Kind:         Subnet
Metadata:
  Creation Timestamp:  2020-12-16T08:13:00Z
  Finalizers:
    kube-ovn-controller
  Generation:  3
  Managed Fields:
    API Version:  kubeovn.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"kube-ovn-controller":
      f:spec:
        f:default:
        f:gatewayNode:
        f:gatewayType:
        f:natOutgoing:
        f:private:
        f:underlayGateway:
      f:status:
        .:
        f:activateGateway:
        f:availableIPs:
        f:usingIPs:
    Manager:      kube-ovn-controller
    Operation:    Update
    Time:         2020-12-16T08:13:00Z
    API Version:  kubeovn.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:cidrBlock:
        f:excludeIps:
        f:gateway:
        f:protocol:
        f:provider:
    Manager:         kubectl
    Operation:       Update
    Time:            2020-12-16T08:13:00Z
  Resource Version:  2199055
  Self Link:         /apis/kubeovn.io/v1/subnets/macvlan
  UID:               6529f5e0-531f-4500-addd-fa90601bca50
Spec:
  Cidr Block:  10.60.0.0/16
  Default:     false
  Exclude Ips:
    10.60.0.0..10.60.0.10
  Gateway:           10.60.0.1
  Gateway Node:
  Gateway Type:      distributed
  Nat Outgoing:      false
  Private:           false
  Protocol:          IPv4
  Provider:          macvlan.default
  Underlay Gateway:  false
Status:
  Activate Gateway:
  Available I Ps:    65523
  Using I Ps:        0
Events:              <none>
```

Then created pod using "macvlan" network but interface is not visible inside the container
POD YAML:
```
apiVersion: v1
kind: Pod
metadata:
  name: pod-macvlan
  namespace : default
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan
spec:
  containers:
  - name: busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    args:
      - sleep
      - "1000"
    ports:
      - containerPort: 80

	  
# kubectl exec -it pod-macvlan -- ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
204: eth0@if205: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1400 qdisc noqueue
    link/ether 00:00:00:08:58:49 brd ff:ff:ff:ff:ff:ff
    inet 10.16.0.3/16 brd 10.16.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```

Although in describe pod, it says there are 2 ips associated in annotations
```
# kubectl describe pod pod-macvlan
Name:         pod-macvlan
Namespace:    default
Priority:     0
Node:         rsumaster01/172.19.104.205
Start Time:   Wed, 16 Dec 2020 03:13:06 -0500
Labels:       <none>
Annotations:  k8s.v1.cni.cncf.io/networks: macvlan
              macvlan.default.kubernetes.io/allocated: true
              macvlan.default.kubernetes.io/cidr: 10.60.0.0/16
              macvlan.default.kubernetes.io/gateway: 10.60.0.1
              macvlan.default.kubernetes.io/ip_address: 10.60.0.11
              macvlan.default.kubernetes.io/logical_switch: macvlan
              macvlan.default.kubernetes.io/mac_address: 00:00:00:B4:A9:F8
              ovn.kubernetes.io/allocated: true
              ovn.kubernetes.io/cidr: 10.16.0.0/16
              ovn.kubernetes.io/gateway: 10.16.0.1
              ovn.kubernetes.io/ip_address: 10.16.0.3
              ovn.kubernetes.io/logical_switch: ovn-default
              ovn.kubernetes.io/mac_address: 00:00:00:08:58:49
              ovn.kubernetes.io/network_types: geneve
              ovn.kubernetes.io/routed: true
Status:       Running
IP:           10.16.0.3
IPs:
  IP:  10.16.0.3
Containers:
  busybox:
    Container ID:  docker://e6bcaf7fbe2f7775512994796c0aef94a16432d0705dea1d54a52b737858000e
    Image:         busybox:latest
    Image ID:      docker-pullable://busybox@sha256:bde48e1751173b709090c2539fdf12d6ba64e88ec7a4301591227ce925f3c678
    Port:          80/TCP
    Host Port:     0/TCP
    Args:
      sleep
      1000
    State:          Running
      Started:      Wed, 16 Dec 2020 20:11:00 -0500
    Last State:     Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 16 Dec 2020 19:54:19 -0500
      Finished:     Wed, 16 Dec 2020 20:10:59 -0500
    Ready:          True
    Restart Count:  61
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-5jcvg (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-5jcvg:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-5jcvg
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason   Age                 From                  Message
  ----    ------   ----                ----                  -------
  Normal  Pulled   12s (x62 over 16h)  kubelet, rsumaster01  Container image "busybox:latest" already present on machine
  Normal  Created  12s (x62 over 16h)  kubelet, rsumaster01  Created container busybox
  Normal  Started  12s (x62 over 16h)  kubelet, rsumaster01  Started container busybox
```

Kindly let me know in case i missed anything here.

**Comment by oilbeater** [comment]
Can you check the cni config files in `/etc/cni/net.d` to make sure multus conf with high alphabet order

**Comment by tarun28jain** [comment]
This is my multus conf

```
# cat /etc/cni/net.d/00-multus.conf
{ "cniVersion": "0.3.1", "name": "multus-cni-network", "type": "multus", "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig", "delegates": [ { "name":"kube-ovn", "cniVersion":"0.3.1", "plugins":[ { "type":"kube-ovn", "server_socket":"/run/openvswitch/kube-ovn-daemon.sock" }, { "type":"portmap", "capabilities":{ "portMappings":true } } ] } ] }
```

I tried creating a macvlan network attachment definition with IPAM type as "host-local" and then i am able to see interface attached in my sample pod.
While if i use type as "kube-ovn" in IPAM, interface is not visible.

**Comment by oilbeater** [comment]
the multus conf should have `"provider": "macvlan.default" ` in macvlan ipam options

**Comment by mayuri2016** [comment]
Can you give more specifics? Is this provider should be added in multus conf? Currently multus conf doesnt have any ipam options. Macvlan networkattachdef already having this defined under ipam.

**Comment by tarun28jain** [comment]
Hi,

I am able to run pod using pod using procedure as mentioned in documentation "https://github.com/alauda/kube-ovn/blob/release-1.2/docs/multi-nic.md".

**Although 1 issue which i observed using IPAM type as "kubeovn" in described below**

- When i launch a pod with 2 interfaces from macvlan crd with annotation 
        `k8s.v1.cni.cncf.io/networks: macvlan, macvlan`
pod comes up correctly with 2 interfaces but same ip is assigned to both the interfaces.

I tried this scenario multiple times and same issue is seen everytime.

**Comment by hongzhen-ma** [comment]
> Hi,
> 
> I am able to run pod using pod using procedure as mentioned in documentation "https://github.com/alauda/kube-ovn/blob/release-1.2/docs/multi-nic.md".
> 
> **Although 1 issue which i observed using IPAM type as "kubeovn" in described below**
> 
> * When i launch a pod with 2 interfaces from macvlan crd with annotation
>   `k8s.v1.cni.cncf.io/networks: macvlan, macvlan`
>   pod comes up correctly with 2 interfaces but same ip is assigned to both the interfaces.
> 
> I tried this scenario multiple times and same issue is seen everytime.

The problem reported really exists. But as the attachment cni, it is processed by macvlan to assigned ip to pod, maybe this is a bug for macvlan cni.

And for Kube-OVN used as attachment cni, because Kube-OVN uses annotation to record ip address assigned to pod , so the attachment definitions can not be the same, just like `k8s.v1.cni.cncf.io/networks: attachnet, attachnet`.

```
apple@bogon ovn-test % kubectl get pod -n test1 -o wide
NAME                    READY   STATUS              RESTARTS   AGE   IP       NODE              NOMINATED NODE   READINESS GATES
test-84f67dfbc8-2pgm6   0/1     ContainerCreating   0          14m   <none>   kube-ovn-worker   <none>           <none>
apple@bogon ovn-test %
apple@bogon ovn-test % kubectl get pod -n test1 -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      attachnet.test1.ovn.kubernetes.io/allocated: "true"
      attachnet.test1.ovn.kubernetes.io/cidr: 192.117.0.0/16
      attachnet.test1.ovn.kubernetes.io/gateway: 192.117.0.1
      attachnet.test1.ovn.kubernetes.io/ip_address: 192.117.0.12
      attachnet.test1.ovn.kubernetes.io/logical_router: ovn-cluster
      attachnet.test1.ovn.kubernetes.io/logical_switch: ovn-subnet
      attachnet.test1.ovn.kubernetes.io/mac_address: 00:00:00:66:80:EC
      attachnet.test1.ovn.kubernetes.io/network_type: geneve
      k8s.v1.cni.cncf.io/networks: attachnet, attachnet
      ovn.kubernetes.io/allocated: "true"
      ovn.kubernetes.io/cidr: 10.16.0.0/16
      ovn.kubernetes.io/gateway: 10.16.0.1
      ovn.kubernetes.io/ip_address: 10.16.0.12
      ovn.kubernetes.io/logical_router: ovn-cluster
      ovn.kubernetes.io/logical_switch: ovn-default
      ovn.kubernetes.io/mac_address: 00:00:00:66:21:75
      ovn.kubernetes.io/network_type: geneve
      ovn.kubernetes.io/pod_nic_type: veth-pair
      ovn.kubernetes.io/routed: "true"
    creationTimestamp: "2021-11-18T06:27:06Z"
    generateName: test-84f67dfbc8-
    labels:
      app: test
      pod-template-hash: 84f67dfbc8
    name: test-84f67dfbc8-2pgm6
    namespace: test1
```
