### ISSUE TITLE
使用固定出口网关时，K8S Service type=NodePort,  externalTrafficPolicy: Local ， 非网关节点应答数据包无法原路返回

### ISSUE THREAD

**Issue by Mrtao1028** [kubeovn/kube-ovn#682]
设置 [externalTrafficPolicy: Local](https://kubernetes.io/docs/tutorials/services/source-ip/) 时, 非网关节点应答数据包返回异常
表现同 [container hostPort](https://github.com/alauda/kube-ovn/issues/681)
------------------------------------
不设置 `externalTrafficPolicy: Local` 时表现正常
-----------------------------------
测试yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: gateway-check
  namespace: kube-public
spec:
  type: NodePort
  # https://kubernetes.io/docs/tutorials/services/source-ip/
  externalTrafficPolicy: Local
  selector:
    app: gateway-check-nginx
  ports:
  - name: web
    port: 80
    targetPort: 80
    nodePort: 30080
  - name: websecure
    port: 443
    targetPort: 443
    nodePort: 30443
```
