### ISSUE TITLE
OVN DB 高可用测试无法生效

### ISSUE THREAD

**Issue by ackfin** [kubeovn/kube-ovn#758]
版本：kube-ovn 1.6.2
docker：Server Version: 19.03.14
kubernetes：v1.20.2

测试操作方式
启动了 3 个 ovn-central，使用 kubectl -n kube-system delete pod ovn-central-xxx 删除 1 一个 pod 后，ovn-central 显示正常。
但 kube-ovn-controller 显示异常

```
# kubectl -n kube-system get pod -o wide
NAME                                   READY   STATUS    RESTARTS   AGE   IP            NODE         NOMINATED NODE   READINESS GATES
kube-ovn-cni-7grjt                     1/1     Running   0          56m   10.1.0.66     10.1.0.66    <none>           <none>
kube-ovn-cni-hszff                     1/1     Running   0          56m   10.1.0.249    10.1.0.249   <none>           <none>
kube-ovn-cni-qftn4                     1/1     Running   0          56m   10.1.0.65     10.1.0.65    <none>           <none>
kube-ovn-controller-85df56fbb5-qwjc7   0/1     Running   4          56m   10.1.0.249    10.1.0.249   <none>           <none>
kube-ovn-controller-85df56fbb5-vhgmh   0/1     Running   4          56m   10.1.0.66     10.1.0.66    <none>           <none>
kube-ovn-pinger-9n5hs                  1/1     Running   0          56m   172.22.0.39   10.1.0.65    <none>           <none>
kube-ovn-pinger-k2v6d                  1/1     Running   0          56m   172.22.0.40   10.1.0.249   <none>           <none>
kube-ovn-pinger-x2lc2                  1/1     Running   0          56m   172.22.0.44   10.1.0.66    <none>           <none>
ovn-central-85bff6b7cb-22h5f           2/2     Running   0          26m   10.1.0.66     10.1.0.66    <none>           <none>
ovn-central-85bff6b7cb-d7hj5           2/2     Running   0          37m   10.1.0.249    10.1.0.249   <none>           <none>
ovn-central-85bff6b7cb-f9hfb           2/2     Running   0          56m   10.1.0.65     10.1.0.65    <none>           <none>
ovs-ovn-k5nfz                          1/1     Running   0          56m   10.1.0.65     10.1.0.65    <none>           <none>
ovs-ovn-v8b77                          1/1     Running   0          56m   10.1.0.66     10.1.0.66    <none>           <none>
ovs-ovn-x4zt2                          1/1     Running   0          56m   10.1.0.249    10.1.0.249   <none>           <none>
```

```
# kubectl get deploy -n kube-system
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
kube-ovn-controller   0/2     2            0           58m
ovn-central           3/3     3            3           58m
```

kube-ovn-controller 事件日志
```
# kubectl -n kube-system describe pod kube-ovn-controller-85df56fbb5-vhgmh 
Name:                 kube-ovn-controller-85df56fbb5-vhgmh
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 10.1.0.66/10.1.0.66
Start Time:           Fri, 23 Apr 2021 16:09:21 +0800
Labels:               app=kube-ovn-controller
                      component=network
                      pod-template-hash=85df56fbb5
                      type=infra
Annotations:          <none>
Status:               Running
IP:                   10.1.0.66
IPs:
  IP:           10.1.0.66
Controlled By:  ReplicaSet/kube-ovn-controller-85df56fbb5
Containers:
  kube-ovn-controller:
    Container ID:  docker://9ec4c8c96e8570a4bbfcb591b25d991d3248464b1d21bff6355de037e715bc57
    Image:         kubeovn/kube-ovn:v1.6.2
    Image ID:      docker-pullable://kubeovn/kube-ovn@sha256:f1ff9f6ce33ca424d2d1788c61dba888bbae697ef8cb8689e55f6d788b2335f2
    Port:          <none>
    Host Port:     <none>
    Command:
      /kube-ovn/start-controller.sh
    Args:
      --default-cidr=172.21.0.0/16
      --default-exclude-ips=
      --node-switch-cidr=100.65.0.0/16
      --network-type=geneve
      --default-interface-name=
      --default-vlan-id=100
    State:          Running
      Started:      Fri, 23 Apr 2021 17:07:11 +0800
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Fri, 23 Apr 2021 17:00:25 +0800
      Finished:     Fri, 23 Apr 2021 17:07:11 +0800
    Ready:          False
    Restart Count:  5
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      200m
      memory:   200Mi
    Liveness:   exec [bash /kube-ovn/kube-ovn-controller-healthcheck.sh] delay=300s timeout=45s period=7s #success=1 #failure=5
    Readiness:  exec [bash /kube-ovn/kube-ovn-controller-healthcheck.sh] delay=0s timeout=45s period=3s #success=1 #failure=3
    Environment:
      ENABLE_SSL:      false
      POD_NAME:        kube-ovn-controller-85df56fbb5-vhgmh (v1:metadata.name)
      KUBE_NAMESPACE:  kube-system (v1:metadata.namespace)
      KUBE_NODE_NAME:   (v1:spec.nodeName)
      OVN_DB_IPS:      10.1.0.66,
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from ovn-token-cdvjr (ro)
      /var/run/tls from kube-ovn-tls (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-ovn-tls:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-ovn-tls
    Optional:    true
  ovn-token-cdvjr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ovn-token-cdvjr
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/os=linux
Tolerations:     op=Exists
Events:
  Type     Reason     Age   From     Message
  ----     ------     ----  ----     -------
  Warning  Unhealthy  30m   kubelet  Liveness probe failed: cat: /var/run/ovn/ovn-nbctl.pid: No such file or directory
2021-04-23T08:39:48Z|00001|unixctl|WARN|failed to connect to /var/run/ovn/ovn-nbctl..ctl
ovn-nbctl: /var/run/ovn/ovn-nbctl..ctl: could not connect to ovn-nb daemon (No such file or directory); unset OVN_NB_DAEMON to avoid using daemon
  Warning  Unhealthy  30m  kubelet  Readiness probe failed: 2021-04-23T08:39:48Z|00001|fatal_signal|WARN|terminating with signal 15 (Terminated)
Terminated
  Warning  Unhealthy  30m  kubelet  Liveness probe failed: 2021-04-23T08:39:48Z|00001|fatal_signal|WARN|terminating with signal 15 (Terminated)
Terminated
  Warning  Unhealthy  30m  kubelet  Readiness probe failed: cat: /var/run/ovn/ovn-nbctl.pid: No such file or directory
2021-04-23T08:39:48Z|00001|unixctl|WARN|failed to connect to /var/run/ovn/ovn-nbctl..ctl
ovn-nbctl: /var/run/ovn/ovn-nbctl..ctl: could not connect to ovn-nb daemon (No such file or directory); unset OVN_NB_DAEMON to avoid using daemon
  Warning  Unhealthy  30m  kubelet  Readiness probe failed: cat: /var/run/ovn/ovn-nbctl.pid: No such file or directory
2021-04-23T08:39:50Z|00001|unixctl|WARN|failed to connect to /var/run/ovn/ovn-nbctl..ctl
ovn-nbctl: /var/run/ovn/ovn-nbctl..ctl: could not connect to ovn-nb daemon (No such file or directory); unset OVN_NB_DAEMON to avoid using daemon
  Warning  Unhealthy  30m  kubelet  Liveness probe failed: cat: /var/run/ovn/ovn-nbctl.pid: No such file or directory
2021-04-23T08:39:52Z|00001|unixctl|WARN|failed to connect to /var/run/ovn/ovn-nbctl..ctl
ovn-nbctl: /var/run/ovn/ovn-nbctl..ctl: could not connect to ovn-nb daemon (No such file or directory); unset OVN_NB_DAEMON to avoid using daemon
  Warning  Unhealthy  30m  kubelet  Readiness probe failed: cat: /var/run/ovn/ovn-nbctl.pid: No such file or directory
2021-04-23T08:39:53Z|00001|unixctl|WARN|failed to connect to /var/run/ovn/ovn-nbctl..ctl
ovn-nbctl: /var/run/ovn/ovn-nbctl..ctl: could not connect to ovn-nb daemon (No such file or directory); unset OVN_NB_DAEMON to avoid using daemon
  Warning  Unhealthy  30m  kubelet  Readiness probe failed: cat: /var/run/ovn/ovn-nbctl.pid: No such file or directory
2021-04-23T08:39:56Z|00001|unixctl|WARN|failed to connect to /var/run/ovn/ovn-nbctl..ctl
ovn-nbctl: /var/run/ovn/ovn-nbctl..ctl: could not connect to ovn-nb daemon (No such file or directory); unset OVN_NB_DAEMON to avoid using daemon
  Warning  Unhealthy  30m  kubelet  Liveness probe failed: cat: /var/run/ovn/ovn-nbctl.pid: No such file or directory
2021-04-23T08:39:59Z|00001|unixctl|WARN|failed to connect to /var/run/ovn/ovn-nbctl..ctl
ovn-nbctl: /var/run/ovn/ovn-nbctl..ctl: could not connect to ovn-nb daemon (No such file or directory); unset OVN_NB_DAEMON to avoid using daemon
  Normal   Pulled     29m (x2 over 60m)   kubelet  Container image "kubeovn/kube-ovn:v1.6.2" already present on machine
  Normal   Created    29m (x2 over 60m)   kubelet  Created container kube-ovn-controller
  Normal   Started    29m (x2 over 60m)   kubelet  Started container kube-ovn-controller
  Normal   Killing    10m (x4 over 29m)   kubelet  Container kube-ovn-controller failed liveness probe, will be restarted
  Warning  Unhealthy  3s (x149 over 30m)  kubelet  (combined from similar events): Readiness probe failed: 2021-04-23T09:10:00Z|00001|fatal_signal|WARN|terminating with signal 14 (Alarm clock)
/kube-ovn/kube-ovn-controller-healthcheck.sh: line 4:   104 Alarm clock             OVN_NB_DAEMON=/var/run/ovn/ovn-nbctl.$(cat /var/run/ovn/ovn-nbctl.pid).ctl ovn-nbctl --timeout=15 lr-list > /dev/null
```

新的 pod 无法创建，报错 
```
 Warning  FailedCreatePodSandBox  89s (x85 over 24m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "d6fedba3e27847747d416db9eacd34de0946c9d16388d388d2038f486f60a751" network for pod "web-2": networkPlugin cni failed to set up pod "web-2_default" network: request ip return 500 no address allocated to pod default/web-2, please see kube-ovn-controller logs to find errors
```

**Comment by oilbeater** [comment]
看一下 kube-ovn-controller 有没有什么错误日志

**Comment by ackfin** [comment]
无法看到日志
```
# kubectl get pod -n kube-system 
NAME                                   READY   STATUS    RESTARTS   AGE
kube-ovn-cni-7grjt                     1/1     Running   0          10h
kube-ovn-cni-hszff                     1/1     Running   0          10h
kube-ovn-cni-qftn4                     1/1     Running   0          10h
kube-ovn-controller-85df56fbb5-b7rm6   0/1     Running   0          4m5s
kube-ovn-controller-85df56fbb5-q24cg   0/1     Running   1          8m3s
kube-ovn-pinger-9n5hs                  1/1     Running   0          10h
kube-ovn-pinger-k2v6d                  1/1     Running   0          10h
kube-ovn-pinger-x2lc2                  1/1     Running   0          10h
ovn-central-85bff6b7cb-22h5f           2/2     Running   0          10h
ovn-central-85bff6b7cb-d7hj5           2/2     Running   0          10h
ovn-central-85bff6b7cb-f9hfb           2/2     Running   0          10h
ovs-ovn-k5nfz                          1/1     Running   0          10h
ovs-ovn-v8b77                          1/1     Running   0          10h
ovs-ovn-x4zt2                          1/1     Running   0          10h
# kubectl -n kube-system logs kube-ovn-controller-85df56fbb5-b7rm6
# 
# kubectl -n kube-system logs kube-ovn-controller-85df56fbb5-q24cg
# 
```

**Comment by ackfin** [comment]
找到原因了：
一、操作步骤
1. 一开始创建 kube-ovn 是使用 https://raw.githubusercontent.com/alauda/kube-ovn/release-1.6/dist/images/install.sh 这个脚本创建的单个 ovn-central 和 kube-ovn-controller 。
2. 后面通过 kubectl edit deploy ovn-central -n kube-system 把副本数改为 3。
3. 然后通过 kubectl -n kube-system delete pod ovn-central-xxx 删除 1 一个 pod 后，ovn-central 显示正常，
但 kube-ovn-controller 显示异常。

二、原因是 https://raw.githubusercontent.com/alauda/kube-ovn/release-1.6/dist/images/install.sh 这个脚本部署单机 kube-ovn-controller 硬编码了 ovn-central 的地址（ - name: OVN_DB_IPS value: $addresses ），通过 kubectl -n kube-system delete pod ovn-central-xxx 刚好删除这个 ip 的 ovn-central  后，kube-ovn-controller 连接不上，就显示异常了，但是没有报错日志。
```
            - name: OVN_DB_IPS
              value: $addresses
```
```
cat <<EOF > kube-ovn.yaml
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kube-ovn-controller
  namespace: kube-system
  annotations:
    kubernetes.io/description: |
      kube-ovn controller
spec:
  replicas: $count
  selector:
    matchLabels:
      app: kube-ovn-controller
  strategy:
    rollingUpdate:
      maxSurge: 0%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-ovn-controller
        component: network
        type: infra
    spec:
      tolerations:
      - operator: Exists
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: kube-ovn-controller
              topologyKey: kubernetes.io/hostname
      priorityClassName: system-cluster-critical
      serviceAccountName: ovn
      hostNetwork: true
      containers:
        - name: kube-ovn-controller
          image: "$REGISTRY/kube-ovn:$VERSION"
          imagePullPolicy: $IMAGE_PULL_POLICY
          command:
          - /kube-ovn/start-controller.sh
          args:
          - --default-cidr=$POD_CIDR
          - --default-exclude-ips=$EXCLUDE_IPS
          - --node-switch-cidr=$JOIN_CIDR
          - --network-type=$NETWORK_TYPE
          - --default-interface-name=$VLAN_INTERFACE_NAME
          - --default-vlan-id=$VLAN_ID
          env:
            - name: ENABLE_SSL
              value: "$ENABLE_SSL"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OVN_DB_IPS
              value: $addresses
          volumeMounts:
            - mountPath: /var/run/tls
              name: kube-ovn-tls
          readinessProbe:
            exec:
              command:
                - bash
                - /kube-ovn/kube-ovn-controller-healthcheck.sh
            periodSeconds: 3
            timeoutSeconds: 45
          livenessProbe:
            exec:
              command:
                - bash
                - /kube-ovn/kube-ovn-controller-healthcheck.sh
            initialDelaySeconds: 300
            periodSeconds: 7
            failureThreshold: 5
            timeoutSeconds: 45
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 1000m
              memory: 1Gi
      nodeSelector:
        kubernetes.io/os: "linux"
      volumes:
        - name: kube-ovn-tls
          secret:
            optional: true
            secretName: kube-ovn-tls

```
三、建议脚本里去掉 kube-ovn-controller Deployment 里的 - name: OVN_DB_IPS value: $addresses 配置项，让 kube-ovn-controller 直接连接 ovn-central  的 service 地址。
