### ISSUE TITLE
networkpolicy doesn't work as expected!

### ISSUE THREAD

**Issue by gjj2016** [kubeovn/kube-ovn#871]
kube-ovn version: 1.7

kubenetes version: 1.17.3

i have three nodes in my k8s cluster, there is:
```
[docker@test-160 ~]$ kubectl get no
NAME             STATUS                     ROLES         AGE    VERSION
11.142.232.152   Ready                      <none>        190d   v1.17.3
11.142.232.160   Ready                      master        411d   v1.17.3
11.142.232.161   Ready                      <none>        411d   v1.17.3
```

here is my k8s namespace:
```
[docker@test-160 ~]$ kubectl get ns --show-labels
NAME              STATUS   AGE    LABELS
aatest            Active   7d5h   name=aatest            
```

a deployment is created in the above namespace:
```
[docker@test-160 ~]$ kubectl get deploy -owide  -naatest            
NAME            READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS      IMAGES                                                     SELECTOR
testnginx       1/1     1            1           48d   container1      11.142.232.181:8021/library/nginx:1.17.10-20200703         name=testnginx
```

the pod info:
```
[docker@test-160 ~]$ kubectl get pod -owide   -naatest            
NAME                             READY   STATUS    RESTARTS   AGE     IP             NODE             NOMINATED NODE   READINESS GATES
testnginx-78d46b6c46-m6jjd       1/1     Running   0          9h      172.26.3.162   11.142.232.160   <none>           <none>
```

and a networkpolicy is set:
```
[docker@test-160 ~]$ kubectl get netpol -naatest test-networkpolicy -oyaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: test-networkpolicy
  namespace: aatest
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: aatest
  podSelector: {}
  policyTypes:
  - Ingress
```

**Here is my question**: in my understanding, pod `testnginx-78d46b6c46-m6jjd` should be only accessed by pod in namespace `aatest`, but why can i access the pod ip `172.26.3.162` from k8s node `11.142.232.152`. here is :
```
[docker@test-152 ~]$ ping 172.26.3.162
PING 172.26.3.162 (172.26.3.162) 56(84) bytes of data.
64 bytes from 172.26.3.162: icmp_seq=1 ttl=64 time=0.126 ms
64 bytes from 172.26.3.162: icmp_seq=2 ttl=64 time=0.063 ms
^C
--- 172.26.3.162 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1031ms

```
anybody can help me? it really confused me.
