### ISSUE TITLE
Failed to create service in dual stack

### ISSUE THREAD

**Issue by nic1225** [kubeovn/kube-ovn#891]
Failed to create service using yaml file below

```
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip6
  namespace: ls1
spec:
  clusterIP: fd00:10:96::52
  clusterIPs:
  - fd00:10:96::52
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
targetPort: 80
```

Error message

[root@k3s--3 ~]# k apply -f clusterIp6.yaml
The Service "cluster-ip6" is invalid: spec.ipFamilies[0]: Invalid value: []string{"fd00:10:96::52"}: ipfamily IPv6 is not configured on cluster
